### ISSUE TITLE
input validation for template questions

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#100]
Arguments supplied to template variables should be validated by batfish-client before being sent off to coordinator.

**Comment by dhalperi** [comment]
My belief is that this is the affected code: https://github.com/batfish/batfish/blob/master/projects/batfish-client/src/org/batfish/client/Client.java#L262

Specifically, we can probably write a method like

```java
static void validate(String jsonValue, Variable variable) throws BatfishException {
// throws if the json-encoded value is not a valid setting of the variable.
}
```

More parameters may be needed if there is additional context needed to validate.
