### ISSUE TITLE
Trivial tests?

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#1070]
basic/example-iptables-protection.ref
basic/example-iptables-reachability.ref
basic/multipath-host1.ref
basic/multipath-host2.ref
basic/outliers3.ref
java-smt/env2-local2.ref
java-smt/ospf3-deterministic.ref

Ratul's improved testing in #1066 has revealed that all these have essentially empty ref files. For many of these (multipath, reachability, outliers) this seems like it's probably a bug. Most tests should have some answer to confirm that they're working.

We should follow up on each of these tests to confirm what they're testing and if they've rotted over time.

* if the goal is 0 answers, switch to comparing the summary instead?
* if there used to be answers, but are no longer, investigate why?
* other?

Also suggest ensuring that test names/ref names are updated to indicate what is expected.

**Comment by dhalperi** [comment]
FYI @anothermattbrown

**Comment by ratulm** [comment]
Related: If you come across tests that were commented out because of non-deterministic answers, consider uncommenting them in comparesummary mode if they yield consistent summaries. Its not ideal (we should still limit non-determinism), but at least some aspects will get tested.
