### ISSUE TITLE
Provide way to see parsing errors from client without inducing crash

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#109]
Currently the only way to see parsing ERRORs (not warnings) is to use options such that the parsing step crashes. There should be a way to see errors for failed configs without inducing a crash.

**Comment by virtuald** [comment]
This seems fairly important, as the only message it seems one currently gets is "failed to parse". 👎

**Comment by dhalperi** [comment]
If you're compiling from head, you can try it now. Pass the `verboseError=true` flag: `get initinfo verboseError=true`

**Comment by virtuald** [comment]
I just saw #189, I'm a week back, will update. :)

**Comment by virtuald** [comment]
Shows errors, which is great. However, seems like it would be good if there was a message shown when there's an error saying... `Execute 'get initinfo verboseError=true' to see error messages`... as that isn't the most intuitive way to retrieve errors.
