### ISSUE TITLE
Disjoint subnets check

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#1103]
In most cases, it is desirable that if two connected subnets anywhere in the network overlap, they are the same length, i.e. they are the same network.
It would be useful to flag violations of this property.
E.g. you probably would not want some interface to have IP 192.168.0.1/16 and another interface somewhere to have 192.168.0.2/24. At minimum this would create a weird situation for topology inference.

**Comment by dhalperi** [comment]
Closing this deprecated issue. Since then, we have actually found that interfaces with asymmetric lengths will peer as long as both IPs are in the host space of the prefixes, and this is not actually that uncommon.
