### ISSUE TITLE
Support for SNAT in reachability analysis, traceroute

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#112]
Add support for SNAT packet transformation in reachability analysis as well as virtual traceroute. Depends on #106.

**Comment by arifogel** [comment]
Supported in traceroute by 62cdff8b98025230e999ae7773d17226b5a9af8d

**Comment by dhalperi** [comment]
Still unhandled in the Z3 parts of the stack.

**Comment by jkhourybbn** [comment]
@dhalperi what do you mean by still unhandled in Z3? My understanding is if we add header variables before transformation and after transformation, one can reason about transformations in general (including SNAT)?

**Comment by ratulm** [comment]
@arifogel, is this on the horizon?

**Comment by arifogel** [comment]
@jkhourybbn 
This is an important problem for us, but we don't know when we will be able to get to it. You are welcome to take a stab at this. The relevant code is located within `org.batfish.z3` and subpackages.

You can add variables to accomplish transformation. You will need to be careful about the actual query you are asking. Currently, reachability analysis with Z3 is done as follows:
1. Define a bunch of relations on a header. Let's call these packet relations.
2. Define a bunch of rules connecting some packet relations to others.
3. Define a query packet relation that is true when some criteria are met.
4. Inject symbolic packet at some node, i.e. manually populate the origination packet relation.
5. Apply rules to compute the constraints on elements of the query relation.
6. Find one concrete model satisfying the constraints on the query relation.
7. Run a traceroute on packet represented by concrete model, injecting it at node corresponding to manually-populated origination packet relation.

The major complication here is that thus far all relations are on the same set - the set of packet headers.
To answer questions involving transformation, some relations (including query relation) will need to be defined on the set of pairs of packet headers. 

Let me know if you need any help along the way.

**Comment by dhalperi** [comment]
SNAT is supported throughout the stack now. However, destination NAT is not.
