### ISSUE TITLE
spaces in directory names

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#113]
a bunch of things break when the local repository root has a space in it.

**Comment by ratulm** [comment]
The problem occurs when running with the jar:
ramahajan$ java -jar projects/allinone/out/allinone.jar 
ConfigDir = /Users/ramahajan/work%20with%20space/batfish/projects/allinone/out
retFile = /Users/ramahajan/work%20with%20space/batfish/projects/allinone/out/allinone.properties
config file is /Users/ramahajan/work%20with%20space/batfish/projects/allinone/out/allinone.properties
org.batfish.allinone: Initialization failed: Error loading configuration from /Users/ramahajan/work%20with%20space/batfish/projects/allinone/out/allinone.properties

**Comment by arifogel** [comment]
Fixed by 735ecce
