### ISSUE TITLE
ACL reachability shows only 1 result when devices share an ACL

### ISSUE THREAD

**Issue by corinaminer** [batfish/batfish#1144]
When checking for unreachable ACL lines, devices that share an identical ACL are grouped together. If that ACL is found to have unreachable lines, only the group's first device is listed in the answer, instead of all devices that share the problematic ACL.

**Comment by ratulm** [comment]
Curious: The initial grouping happens by ACL names, independent of whether the definitions themselves are the same? The grouping seems like a useful information reduction tactic, as long that does not lead to a false positive/negative.

**Comment by corinaminer** [comment]
In response to @ratulm, we're using `CompareSameName` to decide ACL equivalency, so we do one ACL reachability analysis for each group of same-named ACLs whose lines are syntactically equivalent.

This issue is resolved by the new ACL reachability version introduced in #1418. (Still happens the same way in the old version of ACL reachability, but that should be deprecated.)
