### ISSUE TITLE
Making access-groups refer  or IP or MAC access lists depending on Configuration Format

### ISSUE THREAD

**Issue by haverma** [batfish/batfish#1153]
As discussed in PR #1151, we should be allowing MAC or IP access lists to be associated with service groups depending on the Configuration Format. We are not sure of the ground truth ATM but this will be needed when we are sure of the semantics.

**Comment by dhalperi** [comment]
We do this well for newer parsers (NX-OS), and we know how to do it when we move IOS, Arista, etc. out of the current hybrid parser. Calling it good.
