### ISSUE TITLE
[pathanalysis] Traceroute hops should refer to actual route objects

### ISSUE THREAD

**Issue by progwriter** [batfish/batfish#1176]
Right now `FlowTraceHop.getRoutes()` returns a set of strings. 
This makes reasoning about routes that affect the traceroute quite difficult.
It would be helpful to have route objects (e.g., `ConnectedRoute`) so that we can do more accurate BGP session reachability

**Comment by dhalperi** [comment]
I believe this is roughly solved in the new traceroute. (set `debugflags` request parameter to `traceroute`).
