### ISSUE TITLE
Detect and handle recursive ACLs

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#1184]
ACLs can now refer to each other by name via `PermittedByAcl`, which creates the possibility of an infinitely recursive ACL. This should be detected and handled gracefully.

**Comment by dhalperi** [comment]
No one's working on this, seems actually worth doing though.

**Comment by corinaminer** [comment]
Resolved for ACL reachability as of #1585. May eventually want to refactor the ACL cycle-finding code out of ACL reachability so we can handle infinitely recursive ACLs in the datamodel itself.

**Comment by dhalperi** [comment]
Closing, integrating with #1255
