### ISSUE TITLE
parsing issues

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#1205]
@dhalperi here is a GNS3 config file with parsing problems

this is just a sample that we have working in GNS3, no proprietary material

[gns3-sample.cfg.zip](https://github.com/batfish/batfish/files/1925889/gns3-sample.cfg.zip)

**Comment by dhalperi** [comment]
Hi @jkhourybbn ,

Thanks for posting the file. From the init info (`get initinfo` at java client), there are only three lines that do not parse. Additionally, that same output tells you the Parser context in which the parser was operating when it did not find a next command (usually correct, but not perfect).

I think you should have the information you need to make parser changes. Happy to help review, when you're ready.
