### ISSUE TITLE
Ability to grab config files for a specific testrig.

### ISSUE THREAD

**Issue by conor0456** [batfish/batfish#123]
Current js client relies on the underlying structure of the batfish directory to get the text of each config file. An API call to coordinator currently exists to get a list of all config files for a given testrig, but not the file text. It would be beneficial to have a filetext element in the answer of that API call.

**Comment by ratulm** [comment]
@kidsbear - maybe this is a good test case for the APIs you are developing? using the REST like structure, users should be able to navigate the entire testrig.

cc: @dhalperi

**Comment by kidsbear** [comment]
@ratulm Is the config files here refer to the raw configuration files uploaded by clients?

**Comment by ratulm** [comment]
Yes. They sit under specific paths like: /containers/<container-name>/testrigs/<testrig-name>/testrig/...

**Comment by kidsbear** [comment]
Ok, I can add a function call to existing WorkMgrService now, and add it to the new API later.

**Comment by ratulm** [comment]
i am not sure if its worth adding to the old APIs if we are going to deprecate them soon. lets discuss tomorrow.
