### ISSUE TITLE
Add support for `PermittedByAcl` in `NamedStructureEquivalenceSets`

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#1253]
If two acls are textually equivalent, but refer to other acls of the same name but are not equivalent, then the first pair are not equivalent either.

**Comment by dhalperi** [comment]
I believe @millstein 's preferred interpretation actually does not want to consider transitive equivalence. E.g., we have the same ACL structure definition, but you and I may have different local address spaces. That should still be considered equivalent for the purposes of outlier detection.
