### ISSUE TITLE
Questions bug

### ISSUE THREAD

**Issue by haverma** [batfish/batfish#1264]
Moved to the correct repo

**Comment by ratulm** [comment]
If a node is using telnet, it is not using ssh v2, right?

**Comment by haverma** [comment]
Yes, that is correct, but I found it a little confusing that we are reporting that nodes are not using ssh v2 when they are not using ssh at all(may be this was intended that they should not use ssh by operator). I guessed this question implies reporting nodes that are configured to use ssh but not via v2 as that is not a good practice. But if even just using telnet to access nodes is a bad practice, then this issue will not be valid.

**Comment by haverma** [comment]
Moving to the correct repo
