### ISSUE TITLE
Disable vlan interfaces with no active switchports using them

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#127]
Currently, vlan interfaces are considered to be up independently of interfaces that may use them. However, any vlan interface not used by an active switchport interface via trunking or access mode should not be up.

**Comment by lpapillon** [comment]
Please note that this check should also take into account the following:
If a vlan has " no autostate" in its config, then it's always up regardless of how many ports are in this vlan.
Example:
interface Vlan112
    no autostate

**Comment by arifogel** [comment]
Fixed by d4c87fedbd4f03b5bacae06b646aadde67cb0644
