### ISSUE TITLE
Justify skipping Juniper SRX inbound filters in ACL reachability

### ISSUE THREAD

**Issue by corinaminer** [batfish/batfish#1275]
Currently in [Batfish.java](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java), `answerAclReachability()` skips Juniper SRX inbound filters, because "they can't really contain operator error" (according to the comment). Should ensure that this is justified.

**Comment by dhalperi** [comment]
Alternately, don't bother and just stop skipping -- any reason to think this isn't a premature optimization?
