### ISSUE TITLE
remote AS is not always a single integer

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#1331]
With passive BGP sessions, it is legal to accept a list / range of AS numbers, and this is common in some of the newer designs. We will need to update the data model and extractors to handle this.

**Comment by dhalperi** [comment]
Example: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/unicast/configuration/guide/l3_cli_nxos/l3_bgp.html

**Comment by progwriter** [comment]
Just making a note that this will probably have to be addressed along with #1228 to keep data structures clean.

**Comment by dhalperi** [comment]
Several recent PRs (like batfish/batfish#2517) have added this support. Closing, please open new PRs for additional features.
