### ISSUE TITLE
Reachability could skip encoding ORIG_SRC_IP when there are no src nats

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#1408]
Idea from a hack session.

Not high priority; assigning to let you add comments as you see fit.

**Comment by anothermattbrown** [comment]
It's definitely worth doing at somepoint, since the equality constraint between SRC_IP and ORIG_SRC_IP is encoded inefficiently in NOD (this is a known limitation of difference-of-cubes).

**Comment by dhalperi** [comment]
Based on where reachability is heading, I think this is almost certainly not worth even remembering. @anothermattbrown  -- should we close?

**Comment by anothermattbrown** [comment]
Yeah not likely to be needed. Anyway we can remember it without the issue. Closing.
