### ISSUE TITLE
Cisco ASA: need support for `network-object ip mask`

### ISSUE THREAD

**Issue by progwriter** [batfish/batfish#1428]
Support for `network-object ip/prefixlen` in cidr notation is there, but not for `network-object ip mask`.
Sample config to reproduce:
```
object-group FOO
   group-object BAR
   network-object 1.1.1.1 255.255.255.255
   group-object BAZ
```

**Comment by sfraint** [comment]
Parsing fixed in #1437 and data model implementation in #1451
