### ISSUE TITLE
Verify ArubaOS defaults

### ISSUE THREAD

**Issue by erikljungman** [batfish/batfish#1548]
Many of the ArubaOS defaults are unverified - Cisco IOS defaults used wherever the ArubaOS defaults are unverified

Defaults needing verification:
 - IS-IS EL1 default administrative cost
 - IS-IS EL2 default administrative cost
 - IS-IS L1 default administrative cost
 - IS-IS L2 default administrative cost
 - OSPF default administrative cost
 - OSPF E1 default administrative cost
 - OSPF E2 default administrative cost
 - OSPF IA default administrative cost
 - RIP default administrative cost
 - summary administrative cost
 - default switchport mode
 - default metric
 - reference OSPF bandwidth
 - default bandwidth

Link to ArubaOS 6.4 documentation:
https://www.arubanetworks.com/techdocs/ArubaOS_64x_WebHelp/Web_Help_Index.htm#ArubaFrameStyles/Preface/Preface.htm%3FTocPath%3DAbout%2520this%2520Guide%7C_____0

**Comment by dhalperi** [comment]
Stale, todos are in the code still.
