### ISSUE TITLE
juniper deactivate line pruner messes with ref tracking

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#1620]
DeactivateLinePruner deletes the deactivated lines before they are visited, so things referenced in those deleted lines are marked as unused.

Thoughts? @arifogel (cc: @sfraint)

**Comment by arifogel** [comment]
Reference tracking in Juniper (and Palo Alto, Vyos) could be done in the first walk of the parse tree, outside of `ConfigurationBuilder`.

Should structures referenced only by deactivated lines should be considered unused?

Is there a sound way to define and reference structures via deactivated lines?

**Comment by dhalperi** [comment]
Is there something fundamentally different about `deactivate` vs `shutdown`? We don't currently consider shutdown interfaces as not using the things the refer to.

**Comment by dhalperi** [comment]
> Reference tracking in Juniper (and Palo Alto, Vyos) could be done in the first walk of the parse tree, outside of ConfigurationBuilder.

I would not like the idea of moving reference tracking outside of `ConfigurationBuilder`. Should all be in the same place.

**Comment by arifogel** [comment]
OK well then we need every enter/exit function to know whether we are in deactivate context in `ConfigurationBuilder`.
