### ISSUE TITLE
Property auto completion should not require a container name

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#1625]

**Comment by corinaminer** [comment]
How deeply does it currently require a container? Could make sense to require container name in the API for user verification.

**Comment by ratulm** [comment]
It is quite shallow. Need to remove the checks for container being there and its accessibility by API key.

Whether it is a valid use is a separate check to whether that user can access a particular container.

**Comment by dhalperi** [comment]
This seems like an unnecessary optimization, honestly. I'm okay rejecting unauthenticated API calls even for things that are network-independent.

**Comment by ratulm** [comment]
fwiw, parboiled-based autocompletion gets us this already.
