### ISSUE TITLE
Unify environment creation APIs, add validation/finalization

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#163]
Currently environment creation can be done one of two ways, neither of which is fully featured:
  1. Upload a whole directory as a new environment, which coordinator plops down without doing any validation.
  2. Submit the name of a base testrig/environment, and submit node/interface/edge blacklists. Batfish receives these and creates a delta environment off of the base environment for the same testrig. Then it creates blacklist files and writes them to the environment, potentially overwriting any existing blacklists.

In case 1, we are unable to supply base information. In case 2, we are unable to provide all of the things an environment might contain, e.g. changed configs, dumped routes, dumped bgp advertisements.

We should unify these 2 into a two step process with 1 environment-related API call to coordinator, and 1 new batfish command.
The coordinator API call should accept a base testrig and an environment zip. The base environment would be optional. Blacklists, etc. should be packaged in the zip before coordinator receives them.
We should add a new batfish command to validate and finalize an environment. Clients should call this command after initializing a new environment via coordinator before using the new environment.
Environment validation will initially consist of:
  - checking blacklists for references to non-existent nodes/interfaces/edges
  - processing provided routing and bgp tables
  - processing provided changed configs
  - providing pass/fail answer (strictness wrt parsing should be configurable)

**Comment by arifogel** [comment]
Partially implemented in 0.28.0. Validation is missing.

**Comment by virtuald** [comment]
I suspect you can add #209 to the list of things to be checked.

**Comment by arifogel** [comment]
@virtuald #209 is not related to environment creation, but to testrig creation.

**Comment by dhalperi** [comment]
Believed to be done. If reopening, please provide specific examples of things that are not properly validated.
