### ISSUE TITLE
New traceroute

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#1650]
In branch traceroute2, I moved the old traceroute code and had it generate tables. But now that we are touching it, it could use further modernization to make it consistent with the new reachability stuff. 

- [ ] Provide more control over how/where the packet is injected (e.g., ingress interface should be specifiable).
- [ ] Simplify how those controls are articulated (e.g., use the new specifiers)

[nice to have]

- [ ] If the specifiers correspond to multiple starting points or multiple destination addresses, do multiple traceroutes

@anothermattbrown - Would you be up for this?

**Comment by anothermattbrown** [comment]
Yes, I'll do that. I suppose we should also use the new IpSpace specifiers for source IPs too; what do you think?

**Comment by ratulm** [comment]
Yeah. That makes sense too. That control (and consistency with reachabilit)
is good. Thanks.
