### ISSUE TITLE
Edge classes should have equals() based on an appropriate identifier

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#1688]
Currently most Edge classes inherit `equals` from `ComparableStructure`, meaning that equality is based entirely on name. This probably not the right behavior for all contexts. @progwriter what are the important use cases? Is there a single implementation that is always correct?

**Comment by progwriter** [comment]
I can think of two types of Edge classes:
1. Internal Edge classes used to represent topologies (e.g., IpEdge)
2. Verbose edges used to answer the `neighbors` question.

Ideally for:
1. We use Edge classes as attribute containers and equality depends on all of those attributes; All topologies/graphs use a graph object with appropriate vertex/edge types (e.g., a guava network with `OspfNeighborId` and `OspfEdgeData`).
2. Verbose edges contain either 
     - flattened attributes relevant to the `neighbors` question or 
     - references to `*Neighbor` objects. 
    The latter is the state of affairs for VerboseEdges now and would require a deep equals.

**Comment by dhalperi** [comment]
The work victor described above is done.
