### ISSUE TITLE
Zone.equals should compare names of IpAccessList only

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#1689]
`Zone`'s implementation of `equals` should not depend on the lines of its filters -- just their names. Consider changing the filter fields to be `String` names rather than the entire `IpAccessList` objects.

**Comment by dhalperi** [comment]
I don't think this is right -- if we want to have some other semantic comparison of zones we should a different comparator. Things are sad when java equals is not object equality.

**Comment by dhalperi** [comment]
(For edges, we added an EdgeId type classes.)
