### ISSUE TITLE
IpsecVpns need unique identifiers

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#1690]
`IpsecVpn`s should be identified by a unique identifier that can unambiguously identify the vpn in the data model, e.g. the pair of (hostname, vpn name).  Comparisons of `IpsecVpn` objects (e.g. in a set) should be based on these identifiers.

**Comment by anothermattbrown** [comment]
I think what you're proposing is what was originally intended. The problem is likely my sentence: 

> Comparisons of IpsecVpn objects (e.g. in a set) should be based on these identifiers.

Should instead be: Comparisons of IpsecVpn objects (e.g. in a set) should be _replaced with comparisons_ on these identifiers.

**Comment by dhalperi** [comment]
+1 yessir, thanks.

**Comment by dhalperi** [comment]
`IpsecVpn` is gone from the public datamodel. The Juniper data model has such a class, but it is only stored in `Map<String, IpsecVpn>` etc., which is correct.
