### ISSUE TITLE
Eliminate overlapping classes from dependencies 

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#170]
Current maven build spews warnings about overlapping classes. For each such class, we should choose a representative jar and exclude those classes from all other jars. This should eliminate the warnings.

**Comment by dhalperi** [comment]
This is largely complete. I removed the biggest offender: grizzly-http-all. The remaining offender is from xstream, and it has two dependencies with most classes not in common and I think both are used.

This is probably bad practice by the xmlpull (likely) and/or xstream folks, but I think can't be solved easily. Luckily, the shade process only includes one copy of the jar in the shaded bundle.
