### ISSUE TITLE
add caching to Synthesizer for efficiency

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#171]
When executing a query, ```batfish.standard()``` creates many NOD jobs (one per ingress), each of which ends up completely regenerating the NOD program even though the program is identical. So in the example rig, we are generating the program 15 times (instead of one)

One way to mitigate this is to add caching to the ```z3.Synthesizer``` to reuse the same statements and program -- since all the jobs are using the same synthesizer instance

**Comment by arifogel** [comment]
So we still need to have unique Z3 contexts for each job. And as I recall, the real cost is in the Z3 jobs. Synthesizer regeneration time is negligible in comparison, so you are unlikely to get any real performance boost by trying to cache them.

**Comment by jkhourybbn** [comment]
Makes sense, just benchmarked this, the synthesizer takes about 20 ms to generate a program. It could be useful to cache it anyway since it is not changing. Closing for now.
