### ISSUE TITLE
Smt-reachability: confusing interaction between failures and negate

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#1724]
It's unclear what the meaning is (or should be) when `failures` and `negate=True` parameters are passed to `smt-reachability`. Is/should the `failures` constraint be negated? Negating the `failures` can be useful to generating examples that witness the query with `negate=False`. The current behavior doesn't seem to correspond to either choice. Need to clarify the intent, and then make sure the implementation matches the intent.

**Comment by rabeckett** [comment]
Not sure if this is the right way to view it, but I think of the smt-reachability question as an assertion and `negate=True` as flipping the entire assertion.

So if you have something like `smt-reachability negate=True failures=1, dstIps=[...]` I would interpret that to mean "It is not the case that the destination is reachable for any combination of up to 1 failure". A counter example could be a failure that violates reachability, or a destination that is not reachable to begin with etc.

**Comment by rabeckett** [comment]
What kind of issue are you running into?

**Comment by anothermattbrown** [comment]
Got it -- I was thrown off by `failures=n` meaning "at most n failures", rather than "exactly n failures". My `smt-reachability negate=True, failures=1, ...` query returned a counterexample with 0 failures.

**Comment by anothermattbrown** [comment]
To be clear, should the meaning be:
- (It is not the case that the destination is reachable) for any combination of up to 1 failure
- It is not the case that (the destination is reachable for any combination of up to 1 failure)

i.e. is the negation outside or inside the quantifier over the number of failures?

The second meaning would imply that any query is verifiable if and only if its negation is not. It appears that the first meaning is what is currently implemented.

**Comment by rabeckett** [comment]
I was thinking of the second case (outside the quantifier) since it lets you find an example satisfying the query in the way batfish does. But honestly, both seem useful depending on what you want to check. I'm guessing `negate=True` only flips the the property assertion -- so it would make sense if it implemented the first one currently.

**Comment by anothermattbrown** [comment]
Here's the relevant code, from `PropertyChecker.java`:

```
// ... elided
enc.computeEncoding();
// ... elided
if (question.getDiffType() != null) {
  // elided code related to differential query; doesn't reference q.getNegate()
} else {
  // Not a differential query; just a query on a single version of the network.
  BoolExpr allProp = enc.mkTrue();
  for (String router : srcRouters) {
    BoolExpr r = prop.get(router);
    if (q.getNegate()) {
      r = enc.mkNot(r);
    }
    allProp = enc.mkAnd(allProp, r);
  }
  enc.add(enc.mkNot(allProp));
}
```

- The call to `enc.computeEncoding()` establishes to constraint on the number of failures. 
- We conjoin the (negated) property instance specific to each source router of interest.
- We then negate the conjoined (negated) properties because we're verifying, not asking for examples.
- The end result is `networkEncoding && !(P1 && P2 ...)` for a non-negated query, or
- `networkEncoding && !(!P1 && !P2 && ...)` for a negated query.

We obviously don't want to negate the `networkEncoding` part, because that would allow/require the solver to make arbitrary changes to the network. We may want to consider moving the failure constraint out of the network encoding though so it can be negated.
