### ISSUE TITLE
Make batfish systemd unit depend on coordinator systemd unit

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#176]
In the RPM/DEB building scripts, we install batfish and the batfish coordinator as system services. Right now they are not linked, so we have to restart each service independently.

It would be good to link them, so that we can restart a single service and have them all restart.

**Comment by arifogel** [comment]
This needs further discussion, actually. Doing this may interfere with the ability to have coordinator and batfish on different machines.

**Comment by dhalperi** [comment]
We probably don't want to do this.
