### ISSUE TITLE
automatically trigger testrig parsing when a question is asked

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#185]
automatically trigger parsing a testrig when a question is asked, if the testrig hasn't already been parsed? (like we do for data plane generation.)

with asynch clients, there may be testrigs that have not been parsed (e.g., because the client was killed right after the upload happened). then, we ask question of this testrig, we currently get:
  FATAL ERROR: Missing compiled vendor-independent configurations for this test-rig)

we can do more complicated logic, e.g., the UI checks readiness before issuing the command to answer, but that seems unnecessary front end complexity if the backend can handle things.

**Comment by arifogel** [comment]
Implemented by PR #186

**Comment by arifogel** [comment]
Merged
