### ISSUE TITLE
Juniper ospf: extract default-metric for an area

### ISSUE THREAD

**Issue by progwriter** [batfish/batfish#1858]
Example: `set protocols ospf area 0.0.0.48 stub default-metric 10`

**Comment by dhalperi** [comment]
Did #1856 solve this?

**Comment by progwriter** [comment]
No, this discovered as I was implementing #1856 
Parsing happens, extraction does not.

**Comment by progwriter** [comment]
default-metric in this context actually defines whether area is a total stub or not (in addition to setting the metric on the default route that is injected) so this is quite important: https://www.juniper.net/documentation/en_US/junos/topics/topic-map/ospf-stub-and-not-so-stubby-areas.html#jd0e192

**Comment by anothermattbrown** [comment]
Fixed by #2047 and #2048
