### ISSUE TITLE
Routes2: better strategy for determining next-hop-node

### ISSUE THREAD

**Issue by progwriter** [batfish/batfish#1862]
Currently we take next hop IP of the route and attempt to pull out a node using computed `ipOwners`. 
If there are more and one owner of the ip, we pick the lexicographically lower node to display in the table.
This works great in the common case (1 owner per IP) but is not always correct.

**Comment by corinaminer** [comment]
Still not fixed, plus determining next hop node for BGP routes from unnumbered peers is going to complicate things further: those routes' next hop nodes will need to be inferred from their next hop interfaces, as their next hop IPs are just the standard BGP unnumbered next hop IP.

This issue only pertains to the Routes question, right? Specifically [computeNextHopNode()](https://github.com/batfish/batfish/blob/master/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L107)

**Comment by progwriter** [comment]
> This issue only pertains to the Routes question, right?

Yes.
