### ISSUE TITLE
EIGRP: Support route tags

### ISSUE THREAD

**Issue by mkremerbbn** [batfish/batfish#1945]
Both internal and external EIGRP routes can have configurable administrative tags.

https://tools.ietf.org/html/rfc7868
https://www.cisco.com/c/en/us/support/docs/ip/enhanced-interior-gateway-routing-protocol-eigrp/16406-eigrp-toc.html
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_eigrp/configuration/xe-3s/ire-xe-3s-book/ire-en-rou-tags.html

**Comment by progwriter** [comment]
Believe to be fixed in #4251, tags can now be set/matched on.
