### ISSUE TITLE
router eigrp missing a lot of parsing

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#1953]
EIGRP is being implemented piecemeal by @mkremerbbn and others. Right now, there's large gaps in the grammar.

For example this simple snippet is largely unparsed:

```
router eigrp 100
  network 10.0.0.0 0.0.0.7
  redistribute bgp 65000 metric 60000 100 255 1 1500 route-map FILTER_BGP_TO_EIGRP
  passive-interface default
  no passive-interface GigabitEthernet0/0/1
!
```

In addition to missed functionality, this results in missed references: route-map `FILTER_BGP_TO_EIGRP` and interface `GIgabitEthernet0/0/1`.

Using this issue as a tracking bug.

**Comment by dhalperi** [comment]
#1956 added grammars and route-map reference tracking for the redistribution lines for 7 protocols (bgp, connected, eigrp, isis, ospf, rip, static)

**Comment by mkremerbbn** [comment]
Everything described in the ticket is parsed, and references to route maps are tracked. References to interfaces are not tracked.
