### ISSUE TITLE
Provide unmanaged switch in topology 

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#201]
It would be useful to be able to add unmanaged switches to a topology. Currently, it seems that the only way to do this in an explicit topology is by connecting all devices on the subnet in a mesh. However, as the number of devices on that switch increase, the number of connections would increase by quite a bit.

**Comment by arifogel** [comment]
So one current way to do this would be to write e.g. a ciso-ish or juniper-ish config that has, at minimum:
  - A hostname
  - A single vlan interface
  - A bunch of switchport interfaces on that vlan in access mode

To resolve this ticket, we will add a new configuration type for switches generally.

**Comment by arifogel** [comment]
I forgot to mention - you will obviously also need to add edges to/from the appropriate switchport interfaces in your explicit topology.

**Comment by arifogel** [comment]
An example config follows. Let's say the file is named `switch1.cfg` and it is located in the `configs` folder of the testrig.
```
!
hostname switch1
!
interface Vlan1
   no shutdown
!
interface Ethernet0
   no shutdown
   switchport
   switchport mode access
   switchport access vlan 1
!
interface Ethernet1
   no shutdown
   switchport
   switchport mode access
   switchport access vlan 1
!
...
!
```

**Comment by virtuald** [comment]
That configuration seems like just the ticket! I'll give it a shot tonight and see how it goes.

**Comment by asydney** [comment]
Update:

I created a simple star topology in CORE with 2 hosts and a switch. Batfish is aware of the correct topology. However, a traceroute between hosts fails. 

Attached is the testrig used. The "Readme" details the files which exist in the testrig and the "log" file provides the output for the following batfish commands:

1. get neighbors                                                    
2. get nodes nodeRegex="host1", summary=false                       
3. get nodes nodeRegex="host2", summary=false
4. get nodes nodeRegex="sw", summary=false                       
5. get Routes                                                       
6. get Traceroute 

REF: Testrig
[testrig_managed_switch.tar.gz](https://github.com/batfish/batfish/files/1403344/testrig_managed_switch.tar.gz)

Can you either a) provide feedback on why the traceroute fails or b) provide a working setup with a L2 managed switch?

Adding @jkhoury and @virtuald to this one.

**Comment by virtuald** [comment]
Strictly speaking, we only need an unmanaged switch configuration. However, managed is fine too if it gets the job done.

**Comment by dhalperi** [comment]
@arifogel can you take a look at this?

**Comment by jkhourybbn** [comment]
Thanks @arifogel -- we are looking forward to your input

**Comment by jkhourybbn** [comment]
We don't see any support for Layer 2 (unmanaged or managed switch, VLANs #783) in Batfish which is ubiquitous in enterprise networks. Any plans to add this layer 2 support?

**Comment by agember** [comment]
This workaround also fails with smt-reachability questions, because the SMT code assumes direct layer-3 adjacencies. It would be great to have support for indirect layer-3 adjacencies as discussed in #783.

**Comment by dhalperi** [comment]
At the moment, Batfish does not have a simple "drop-in" primitive for "there's an unmanaged switch here with these wires". But if you have a L2 device with configuration and a physical L1 topology, Batfish should do the right thing. For more information, see #783.
