### ISSUE TITLE
Quagga ospf6 configuration fails

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#203]
The example at http://www.nongnu.org/quagga/docs/docs-multi/OSPF6-Configuration-Examples.html fails to load, verbose errors saying:

```
    Error context lines:
       1:      interface eth0
       2:       ipv6 ospf6 instance-id 0
       3:      !
    >>>4:      router ospf6
       5:       router-id 212.17.55.53
       6:       area 0.0.0.0 range 2001:770:105:2::/64
       7:       interface eth0 area 0.0.0.0
       8:      !
       9:      
```

I also tried adding a number to make it `router ospf6 1`, as I noticed your cisco examples all have a number after the `router ospf` declaration (which doesn't seem to be required by quagga?), but that didn't help.

**Comment by dhalperi** [comment]
Closing as outdated; no one is seriously trying to use Quagga right now (I think).
