### ISSUE TITLE
quagga does not require OSPF process numbers

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#204]
Looking at their docs at http://www.nongnu.org/quagga/docs/docs-multi/OSPF-router.html#OSPF-router, it appears that quagga forbids specifying an OSPF process number, but your grammar requires it. Something like this would fail:

```
router ospf
  router-id 1.2.3.4
  network 1.2.3.4/24 area 0
!
```

Whereas this parses without error:

```
router ospf 1
  router-id 1.2.3.4
  network 1.2.3.4/24 area 0
!
```

**Comment by dhalperi** [comment]
Closing as outdated; no one is seriously trying to use Quagga right now (I think).

This issue could be fixed by modification to the parser and extractor -- e.g., for quagga could just always be process 0/1.
