### ISSUE TITLE
Eclipse projects out of date?

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#205]
Lots and lots of errors. Now that you're maven-based?, it might make sense to remove the eclipse projects and tell users to just import the project the same way they import any other maven project.

For the record, I ran `mvn eclipse:eclipse` and the compile errors went away.

**Comment by dhalperi** [comment]
You should not run `mvn eclipse:eclipse` -- you should just open the Eclipse project that's checked in.

There are instructions for this on the wiki; please give them a try!  https://github.com/batfish/batfish/wiki/Building-and-running-Batfish-service#eclipse

**Comment by virtuald** [comment]
Opening the eclipse project that's checked in does not work.

**Comment by virtuald** [comment]
As instructed in the wiki, I ran `batfish_build_all`, opened Eclipse, imported the projects into Eclipse, and Eclipse reported lots of compile errors.

* Eclipse is set to auto-build, but I cleaned and forced a rebuild and it still gave me lots of compile errors
* I did see lots of building happening, and when it was all done there were still lots of compile errors
* Eclipse Neon, but upgraded to Eclipse Oxygen and that didn't work too. I'm on OSX.

**Comment by virtuald** [comment]
Looking at the diffs... I note some of the .classpath entries have `org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER` in them... do your configs require m2eclipse to be installed? It's not mentioned in the wiki, and I don't have it installed.

**Comment by dhalperi** [comment]
Eclipse supports Maven out of the box starting from ... a while ago.

I just went through the steps manually and had no issues. Try this:

`batfish-parent` > `Maven` > `Update Project`

and then manually rebuild the entire project.

<img width="1436" alt="screen shot 2017-07-11 at 1 46 55 pm" src="https://user-images.githubusercontent.com/526415/28184387-1095e7ae-67c8-11e7-9399-aa08b88cd9f0.png">

**Comment by virtuald** [comment]
There is no maven menu entry for me. Eclipse is plugin-based, if one installs eclipse from the bare minimum (which is what I do), then the maven plugins are not necessarily included.

I've generally avoided m2e in the past because it was so buggy, but I'll go ahead and install it and try again.

**Comment by dhalperi** [comment]
Fair, sorry for the confusion! I've always installed the default Eclipse IDE.

Here's a screenshot of my list of plugins filtered to Maven:

<img width="1436" alt="screen shot 2017-07-13 at 12 43 07 pm" src="https://user-images.githubusercontent.com/526415/28184615-e8b6d67a-67c8-11e7-8661-4a37ef4a1e83.png">

**Comment by virtuald** [comment]
Works, I'll update the wiki.

**Comment by dhalperi** [comment]
Awesome, thanks Dustin!
