### ISSUE TITLE
BATFISH_TOPOLOGY parsing is completely broken

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#210]
I was trying to figure out why my topology kept causing crashes, and got rid of all of the invalid hosts (#209), and finally it dawned on me that the contents of `Topology.java:_interfaceEdges` all contain keys that have `"` in them -- so it appears that you can't actually use quotes at all ([unlike what the wiki says](https://github.com/batfish/batfish/wiki/Packaging-testrigs-for-analysis#format-for-the-topology-file)).

Looking at all your examples, it seems like you no longer use this file format, as everything is in GNS form? Is there anything testing this, or should it not be used anymore?

... and really, it should be json anyways instead of a custom file format ;)

**Comment by virtuald** [comment]
In addition to the parsing being completely broken, it looks like the information being ingested isn't sensible either? For example, if I use this topology:

```
BATFISH_TOPOLOGY
r1:eth0, h1:eth0
h1:eth0, r1:eth0
```

Everything definitely matches, but I still get a crash at BdpDataPlane.java:118 because `nextHopInInt` is null. If I look at `nextHop._interfaces`, I see it's rendered as `{Ethernet0=Interface<Ethernet0>}` ... which is strange, because Ethernet0 appears nowhere in any of my configurations. Any idea what's going on here?

**Comment by ratulm** [comment]
Ethernet0 appears because we normalize interface names internally. On Cisco routers, there are multiple ways to refer to the same interface. 

We'll look into the topology format issue.

**Comment by virtuald** [comment]
Interesting, because `nextHopInIntName` shows as `eth0`. Maybe the normalization isn't being applied uniformly?

**Comment by ratulm** [comment]
@virtuald, thanks for the bug report.  Can you please attach a zipped test rig that causes this behavior? It'll make it easier to fix the issue.

**Comment by virtuald** [comment]
Here you go: [testrig.zip](https://github.com/batfish/batfish/files/1150669/testrig.zip)

**Comment by virtuald** [comment]
It initializes the test rig without errors, but when I issue a basic command that's when it crashes.

```
init-testrig test_rigs/testrig.zip
get #checkreachability 10.0.4.201 tcp
```

Note that the topology.net in the testrig I attached doesn't have quotes in them, and it still crashes. If you add double or single quotes to the topology.net file, then as mentioned above the items in `Topology.java:_interfaceEdges` also have quotes in them, which is probably incorrect.

**Comment by ratulm** [comment]
@ari, i am assigning this issue to you. i poked around but this goes into the guts of BDP that you are best positioned to handle. 

related issues, also assigned to you: #207 #209

**Comment by ratulm** [comment]
for starters, i'll make topology specification JSON based. we'll touch other issues after that.

**Comment by virtuald** [comment]
One thought now that you're using maven... if your users want to continue to put comments in the topology file (I don't care myself, but your old format did), you may consider yaml instead. Snakeyaml is pretty easy to use for serializing/deserializing java objects.

(I also sorta wish the vendor-independent serialized configs were yaml, but I found the text representation option so it's not so bad...)

**Comment by ratulm** [comment]
We use JSON all over the place, so hard to take a dependency on another formatting language for now. More importantly, inferred topology (when not explicitly specified) is output in JSON. I ended up using the same format for inputting explicit topology.

**Comment by ratulm** [comment]
PR #258 

You are welcome to add support for another format if that really simplifies your life. The relevant code will go in parseTopologyPath() in Batfish.java. Closing for now.
