### ISSUE TITLE
CompareSameNameQuestion with parameter missing=TRUE throws an exception

### ISSUE THREAD

**Issue by SivaKesava1** [batfish/batfish#2107]
In CompareSameNameQuestionPlugin Batfish provides an option to create an equivalence class for nodes that are missing a structure of a given name by allowing users to set "missing=TRUE" but it throws "org.json.JSONException: Unparsable JSON string: null" exception.  This happens because of the following method in NamedStrucutreEquivalenceSets.java.
```
 checkJsonStringEquals(String lhs, String rhs) {
      try {
        JSONAssert.assertEquals(lhs, rhs, false);
        return true;
      } catch (Exception e) {
        throw new BatfishException("JSON equality check failed", e);
      }

```

**Comment by ratulm** [comment]
hey, @SivaKesava1 - can you provide more detail? what command were you running? on what data? thanks.

**Comment by SivaKesava1** [comment]
Data -  test_rigs/example
Command - get comparesamename missing=TRUE
 
The JSONException would arise for any data when the missing=TRUE is passed.

**Comment by ratulm** [comment]
Ok, thanks.

Hey, @vasu018 - Are you able to take a look? I suspect checking for null is needed someplace.

**Comment by SivaKesava1** [comment]
A small Suggestion- I believe for the "get comparesamename"  question to work with missing=TRUE, the "clean() method in NamedStructureEquivalenceSets.java" should also be modified along with adding the null check at some place.  The clean() method "Removes structures with only one equivalence class" but when missing=TRUE is added there would be at least two equivalence classes (one for non-existent ones and the others for exisiting ones) so the filter in the clean() method has to be modified.

Possible fix for the filter:
```
.filter( e ->  !(e.getValue().size() == 1
                        | (e.getValue().size() == 2
                            & e.getValue().first().getNamedStructure() == null))) 
```
instead of the existing  filter:
``` .filter( e ->  e.getValue().size() != 1)```



Thanks
Siva

**Comment by ratulm** [comment]
Thanks. Since you've come this far, feel free to send a PR to show what you mean. We may just merge that then.

**Comment by vasu018** [comment]
Sorry, the notification went off my radar. I will take a look at this bug today and into siva's suggestion even.

**Comment by SivaKesava1** [comment]
Probably I need to look deeper to send a PR as I was just looking at how to make this question work. 

I have another question- There is "get unusedstructures" question in Batfish so is there any method defined to remove/clean those unused structures from the Configurations and then run other questions like "get outliers" or "get comparesamename" as I feel that would be more accurate.

Thanks in advance for your help- siva

**Comment by ratulm** [comment]
That seems like a reasonable idea, but there is no automated way to do it
at the moment. For now, you might be able to accomplish what you want using
Python/pybatfish (github.com/batfish/pybatfish) on the outside -- that is,
get the list of unusedStructures and control how outliers is run by scoping
it appropriately. If that proves useful, we can add appropriate settings to
the outliers question to replicate that out of the box.

**Comment by ratulm** [comment]
hey, @vasu018 - are you still planning on looking into this? no worries if not, in which case please unassign yourself and we'll see if someone else can pick it up.
