### ISSUE TITLE
Cisco delimiter parsing

### ISSUE THREAD

**Issue by mkremerbbn** [batfish/batfish#2127]
The syntax for a Cisco IOS banner is "banner login _delimiter_ _message_ _delimiter_", where _message_ does not contain _delimiter_. For example, delimiter could be '^' or the control character '^C'. Unfortunately, the router will also accept characters directly after the delimiter and ignore them.

In the following snippet, the string "^Cc" is a control character '^C' followed by a literal 'C'.

> banner login ^Cc

This is valid, and the router interprets the delimiter to be the first character, i.e. '^C'. I have seen this in practice. Not a severe bug, but the result is that the banner gets interpreted literally by the Batfish parser.

> configfile:    MISCELLANEOUS: Unrecognized Line: 1: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ (Batfish parser context: [cisco_configuration]) SUBSEQUENT LINES MAY NOT BE PROCESSED CORRECTLY
> configfile:    MISCELLANEOUS: Unrecognized Line: 2: Banner text   (Batfish parser context: [cisco_configuration]) SUBSEQUENT LINES MAY NOT BE PROCESSED CORRECTLY
> configfile:    MISCELLANEOUS: Unrecognized Line: 3: More banner text (Batfish parser context: [cisco_configuration]) SUBSEQUENT LINES MAY NOT BE PROCESSED CORRECTLY
> configfile:    MISCELLANEOUS: Unrecognized Line: 4: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ (Batfish parser context: [cisco_configuration]) SUBSEQUENT LINES MAY NOT BE PROCESSED CORRECTLY
> configfile:    MISCELLANEOUS: Unrecognized Line: 5: (Batfish parser context: [cisco_configuration]) SUBSEQUENT LINES MAY NOT BE PROCESSED CORRECTLY

**Comment by dhalperi** [comment]
@arifogel did you fix this in last week's pr?

**Comment by arifogel** [comment]
Should be fixed by #4851. Not sure what to test here, since the line `banner login ^Cc` does not represent a complete banner (no final delimiter).
@mkremerbbn please let me know if you continue to have any issues.
