### ISSUE TITLE
Add more ICMP types for Cisco parsing

### ISSUE THREAD

**Issue by mkremerbbn** [batfish/batfish#2131]
`toIcmpType` in CiscoControlPlaneExtractor throws parsing errors when it encounters several ICMP types. There are many valid ICMP types, and Cisco apparently supports multiple aliases for the same ICMP type in some cases. I would like support for at least the ones used by ASA service-object, i.e. 'service-object icmp ICMP_TYPE'

From GNS3:
service-object icmp ?
>   alternate-address     
>   conversion-error      
>   echo                  
>   echo-reply            
>   information-reply     
>   information-request   
>   mask-reply            
>   mask-request          
>   mobile-redirect       
>   parameter-problem     
>   redirect              
>   router-advertisement  
>   router-solicitation   
>   source-quench         
>   time-exceeded         
>   timestamp-reply       
>   timestamp-request     
>   traceroute            
>   unreachable

The types are enumerated in Cisco_common.g4:icmp_object_type. All of the above types are parsed as valid configuration, but are not present in datamodel.IcmpType.

For 'object-group icmp-type ?', the router does not explicitly list the ICMP types. However, there is a (partial?) list [here](https://www.cisco.com/c/en/us/td/docs/security/asa/asa82/command/reference/cmd_ref/i1.html). The only differences are that 'address-mask-request' is an alias for 'mask-request' and 'address-mask-reply' is an alias for 'mask-reply'.

**Comment by dhalperi** [comment]
Makes sense! Do you need anything to be able to implement this?

**Comment by dhalperi** [comment]
Thanks!
