### ISSUE TITLE
bug in client arg parsing

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#219]
Since the client allows passing args some of which may be regular expressions, using the character | to split args does not work.

In [Client.java](projects/batfish-client/src/main/java/org/batfish/client/Client.java)
```
String[] params = paramsLine.split("\\\|");
```
should instead be replaced with something like 
```
String[] params = paramsLine.split("&&");
```

**Comment by ratulm** [comment]
Addressed by 541783bdc806997fad9f016df4a0fc937454b3fc

I modified parameter specification to be a comma-separated list of key=value pairs, and values should be JSON or a JSON literal.

E.g.:
batfish> get nodes summary=False, nodeRegex='as2border1'
batfish> get nodespath paths=[{"path":"$.nodes[*].interfaces[*][?(@.mtu != 1500)].mtu", "suffix":True}]
