### ISSUE TITLE
Batfish unable to recognize Aggregated Ethernet Links in Juniper Configs

### ISSUE THREAD

**Issue by SivaKesava1** [batfish/batfish#2193]
Juniper Config: 
```
version 15.1F5.15;
system {
    host-name routerAb;
}
interfaces {
    xe-0/2/0 {
        gigether-options {
            802.3ad ae0;
        }
    }
   xe-0/2/1 {  
        gigether-options {
            802.3ad ae0;
      }
   }
   ae0 { 
        mtu 9192;
        aggregated-ether-options {
            link-speed 10g;
            lacp {
                active;
                periodic fast;
            }
        }
        unit 0 {
            family inet {
                mtu 9178;
                no-redirects;
                 address 10.10.10.10/31;
            }
        }
    }
}
```

When given the above config as input and asked the question "get nodes", the "ae0" interface only shows up and the other two interfaces are not displayed.
I looked at the configurations variable also and it seems like the grammar does not recognize these block of lines.

**Comment by dhalperi** [comment]
The grammar is recognizing these blocks but indeed there's some gaps in representing the layer-2 mappings and aggregation. We've planned work on this in the next month or so, but happy to discuss with you (join Batfish slack!) if you want to get started.

**Comment by SivaKesava1** [comment]
Sure. I joined the slack.

**Comment by dhalperi** [comment]
FYI, we've pushed some changes that will make `ae0.0` in configs like this properly show up in the Batfish vendor-independent model.
