### ISSUE TITLE
Support Cisco nested object groups

### ISSUE THREAD

**Issue by plannigan** [batfish/batfish#2206]
Enhance the existing object group support to include nested groups. Version [8.x](https://www.cisco.com/c/en/us/td/docs/security/asa/asa84/configuration/guide/asa_84_cli_config/acl_objects.html#wp1525455) and [9.x](https://www.cisco.com/c/en/us/td/docs/security/asa/asa97/configuration/firewall/asa-97-firewall-config/access-objects.html) declare them differently, but the concept is the same.

I've start working on this and have a good chunk of it done, but it still needs some more work. I'll create a pull request when it is ready to be reviewed.

**Comment by dhalperi** [comment]
@plannigan awesome -- any ETA on the PR / anything we can do to help?

**Comment by saparikh** [comment]
Looks like this has been merged. Closing the issue. If this is incorrect, please re-open.
