### ISSUE TITLE
feature: support for iptables on routers

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#221]
We need to add batfish support for iptables not only for hosts, but for routers as well. What is the best way to support iptables for routers? There are many network configuration with linux routers (or quagga) where iptables is used on those routers instead of cisco ACLs for example. This feature will allow us to scale our testing.

For example, in a test configuration I have the following iptables rules on the ingress interface of an ospf router
```
# allow OSPF input
iptables -A INPUT -s 10.0.2.1 -p 89 -j ACCEPT
iptables -A INPUT -j DROP

# allow traffic forwarding from 10.0.4 subset
iptables -A FORWARD -s 10.0.4.0/24 -i eth0 -j ACCEPT
iptables -A FORWARD -i eth0 -j DROP
```
The router's is only doing ospf and config is very simple
```
interface eth0
  ip address 10.0.2.10/24
  
!
interface eth1
  ip address 10.0.3.1/24
  
!
router ospf
  router-id 10.0.2.10
  network 10.0.2.0/24 area 0
  network 10.0.3.0/24 area 0
!
router ospf6
  router-id 10.0.2.10
  interface eth0 area 0.0.0.0
  interface eth1 area 0.0.0.0
!
```

**Comment by ratulm** [comment]
Most of what you need is there, but some plumbing will be needed to assemble the router's behavior from two (or more) files. 

An outline of how you might accomplish this:
 1/ at the top-level of the testrig, define a new folder, e.g., 'acls' that has one or more JSON files that provide the mapping from iptables file to router/interfaces to which the iptables file applies. 

as a somewhat similar example, see the 'hosts' folder and files in the example test rig. the files there  that provide information on which iptables files sit on which host and how the host connects to the network.

 2/ in a manner similar to how the 'hosts' folder are processed (first parse the json files in it and then parse the iptables files listed in the json files) process the contents of your 'acls' folder. 

 3/ after your router configurations have been converted to vendor independent format, plug the acls to the router by inserting the (vendor independent) acls derived from iptables.

The rest of the analysis pipeline would stay unchanged. 

I hope this helps; if not, let me know which parts are unclear and I can add more detail.

**Comment by jkhourybbn** [comment]
will give it a try, tx

**Comment by virtuald** [comment]
It seems like a more intuitive approach might be to just add the router JSON to the 'hosts' directory (after all, a router is just a special type of host). The parser would notice that there is a config in both places, and then merge the information together as mentioned above.

**Comment by ratulm** [comment]
@virtuald - i like your way better than mine!

**Comment by jkhourybbn** [comment]
@ratulm it seems to me this is more involved, most likely I am missing something. lets decompose this

Assume we correctly parsed the iptables rules for the router which include three IPAccessLists for INPUT, FORWARD, and OUTPUT

The next step is how to bind the ACLs to the node. It looks like we have to add the ACL to the interface's incomingFilter (for INPUT) and outgoingFilter (for OUTPUT) so that they get picked up by the matchACLRules NoD computation.. and there is no clear place to attach the FORWARD chain. 

Are the semantics of iptables filters different than those of the incoming/outgoing port ACLs that you have implemented? i.e., a packet on a router incoming on an interface (in) but not destined for the router itself (not processed by INPUT chain), and has to be processed by the forwarding (FORWARD chain) before applying the forwarding logic. It was not clear to me from looking at how you produce the NoD dataplane program that you are actually doing this. thoughts?

**Comment by jkhourybbn** [comment]
Some more thoughts 

A clean solution would support the semantics of iptables and would have quagga as a vendor instead of  hacking iptables on top of cisco like we are doing now. 

A more expedient solution might be the following (only handles simple INPUT/FORWARD/OUTPUT iptables chains without redirection):

-  the INPUT chain rules will be attached to the interface's incomingFilter and would be updated to add the interface's ip address as the dest ip in the rule? It seems Interface has an InboundFilter but that doesn't seem to be used in the program?

 - the OUPUT chain rules similarly will be attached to the interface's outgoingFilter and would be updated to add the interface's ip address as the source ip in the rule?

 - the FORWARD chain rules will be attached to all interfaces' incomingFilter 

adding @virtuald @arifogel @ratulm

**Comment by ratulm** [comment]
@jkhourybbn's recommended approach can work. 

another one, if you are the ones designing iptables (versus someone handing them to you), would be to use PREROUTING and POSTROUTING chains. those chains are equivalent to input and output interface ACLs on routers. is that possible on your end?

if not, there are two options: i) the right one (capture iptables semantics by extending data plane analysis to account for INPUT, OUTPUT, and FORWARD chains); and ii) the expedient one ( @jkhourybbn's suggestion of preprocessing INPUT, OUTPUT, and FORWARD chains so that they kick in only under appropriate circumstances).

the right one is likely difficult to execute in a week, but the expedient one should be doable.

PS: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-IPTables.html has a nicer than wikipedia picture to explain things.

**Comment by virtuald** [comment]
I've taken a host configuration, moved the iptables rules from the PREROUTING/POSTROUTING chains into the `_inboundFilter` and `_outgoingFilter` on the router configuration for the appropriate interface(s), and it seems to be ignored. Looking directly at the vendor-independent configuration, the rules are indeed recorded.

Any thoughts why it's ignoring the rules?

**Comment by virtuald** [comment]
... wait, there's an incoming and an inbound filter? It appears only one of them is used, I'll switch it around.

**Comment by virtuald** [comment]
Hm. So a DROP reachability query seems to match my rules (and reports DENIED_IN), but the ACCEPT reachability seems to ignore the rules.

**Comment by virtuald** [comment]
I've played a bunch more with it, but haven't figured out the magic incantation yet.

I looked at the example test rig, and there are a few different ways that it specifies ACLs. One router (as1border1) specifies a variety of ip access list objects that are attached to the route policies. Another (as2core1) uses the incomingFilter field on the interface to filter things -- and this is the mechanism that I'm using.

**Comment by jkhourybbn** [comment]
we implemented the pre/post routing version of this which I think is good enough. We will push it (send a merge request) next week.

**Comment by arifogel** [comment]
I am reopening since #338 was not yet merged.

**Comment by arifogel** [comment]
@dspicuzzbbn The inboundFilter is meant for traffic destined to the host itself (to one of its ip addresses), and is checked after incoming interface filter. This was added to support Juniper zones/firewall semantics.

**Comment by arifogel** [comment]
To be clear, you should not use inboundFilter except for this purpose stated above. It won't be applied to traffic that is forwarded.

**Comment by jkhourybbn** [comment]
Ari, Dustin is using incoming and outgoing to simulate the desired behavior. We don't use inbound. Note that to be clear, the PR that Dustin sent you for iptables support allows us to take a quagga config (in which we can't specify ACLs), augment it with iptables configuration on the routers as a means to simulate Cisco with ACLs. With this change we are able to create CORE configurations and analyze them in batfish and test runtime behavior in CORE simulator as well. We will push the test configurations and CORE pieces soon.

**Comment by arifogel** [comment]
@jkhourybbn Thanks for that clarification. I hope we can work out the issues in PR #338 soon so you are not blocked.
