### ISSUE TITLE
Add support for ICMP packet-too-big

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#2295]
cc: @arifogel

**Comment by progwriter** [comment]
To expand on context here: 
This is a parsing issue, in particular on cisco (I believe).
Not to be confused with ICMPv6 type `Packet too big` which is a different thing. 
In this case, this is simply a shorthand for specifying ICMP type 3, Code 4 (See https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Destination_unreachable for reference).

**Comment by dhalperi** [comment]
https://github.com/batfish/batfish/pull/2372
