### ISSUE TITLE
Add checks in host config processing to prevent parser crash

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#2473]
Some OS's add random files like `Icon?` to folders. It typically is a read-only 0 byte file. If this is present in the `hosts` folder for the uploaded snapshot, the parser crashes and cannot recover.

**Comment by dhalperi** [comment]
@sfraint  - does this fit into the work you've been doing?

**Comment by sfraint** [comment]
Fixed in https://github.com/batfish/batfish/pull/2689
