### ISSUE TITLE
BF does not honor VRRP priority

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#2474]
The `vrrp <group> priority <value>` command is correctly parsed by BF. However it is not currently being honored when determining the VRRP master on a segment. BF is defaulting to using the IP address for picking VRRP master instead.

**Comment by dhalperi** [comment]
The underlying bug here was not that priority was not honored, but rather that the priority line was not parsed because of other unrelated unrecognized lines in the interface. Declaring this issue fixed as Batfish does honor VRRP priority. Parsing PRs to fix incoming.
