### ISSUE TITLE
default Iptables chain policy should be ACCEPT

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#252]
I believe the default policy (if not specified) is ACCEPT, so it should be set to that, or `getIpAccessListLineAction` will throw an exception. 

https://github.com/batfish/batfish/blob/dc12e2fee4aaab6601e2c822cf11c10be72e2e8d/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesChain.java#L24

Additionally, line 54 will throw a NullPointerException if the _policy is null. Better to remove the toString there.

However, if your intent is to tell a user "you really should set a default policy".... then that error message should be better, as the error message (with the toString removed) is "Unsupported ChainPolicy for mapping to LineAction: null", which isn't very useful. It should probably give context (a line number? filename? hostname? something).

Also, #233 applies here, as the error message only shows up in debug mode.

**Comment by dhalperi** [comment]
Hi Dustin,

I'm trying to find out what the input was that caused this bug. Can you share that?

**Comment by virtuald** [comment]
Here's the iptables save file that causes an exception to be thrown at testrig parse time:

```
*filter
:INPUT DROP [0:0]
-A OUTPUT -p udp --dport 53 -j ACCEPT
COMMIT
```

Here's the result of applying it on a linux system with no rules present

```
root@n2# iptables -F
root@n2# iptables-restore < foo 
root@n2# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
```

**Comment by dhalperi** [comment]
Thanks! Out of curiosity, how was that initial content generated?

e.g., I ran your command and then `iptables-save`, and it included the lines you didn't:

```
# Generated by iptables-save v1.4.21 on Wed Aug  9 23:50:29 2017
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
COMMIT
# Completed on Wed Aug  9 23:50:29 2017
```

**Comment by virtuald** [comment]
I wrote it by hand when I was messing with things.
