### ISSUE TITLE
Implement loop detection in new traceroute engine

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#2543]
The new traceroute engine does not detect routing loops, which means traceroute itself can go into an infinite loop. Loop detection is implemented in the old engine, so it should be fairly easy to do the same thing.

**Comment by anothermattbrown** [comment]
The old engine determines loops by checking whether an edge it's about to traverse has been traversed already. This is a loop, but not necessarily an infinite loop, since the header may have changed. 

Do we want `LOOP` to mean infinite loop?

**Comment by haverma** [comment]
In actual router's traceroute, it seems they mean infinite loop by routing loop

**Comment by dhalperi** [comment]
P0 to get it not infinite looping, lower priority to change semantics over
what it used to be. Though yes, I agree that actual loop would be better
here!
