### ISSUE TITLE
Need more robust .ref production, comparison

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#256]
When we have a field as e.g.
```java
SortedMap<String, SortedSet<String>> _someField
```
as used for snmp server traps in the data model, if we store a mapping of some key to an empty set of strings, the whole mapping disappears during serialization. The current JSON comparison we perform in our end-to-end testing cannot tell the difference between the mapping for a key being absent, and the mapping for that key being to an empty set.

My guess is using `JsonInclude.NON_EMPTY` causes the empty set to be simplified into a null (possible bug in this context, as it is a map value and not a field). Then the mapping from key to null is potentially indistinguishable from an absent key depending on comparison method used.

**Comment by dhalperi** [comment]
Posted a candidate fix: #280 

Based on a conversation with the Jackson authors: https://groups.google.com/forum/#!topic/jackson-user/WfZzlt5C2Ww
