### ISSUE TITLE
[pathanalysis] integrate LOOP as failure status into appropriate questions

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#2594]
Reachability currently ignores LOOP if user asks for FAILURE, and fails if LOOP is given as the sole requested disposition. Instead, we should consider LOOPs as failures.

**Comment by dhalperi** [comment]
@haverma isn't this done? Why is this still open?

**Comment by haverma** [comment]
yes, should be done by PRs: [2617](https://github.com/batfish/batfish/pull/2617), [2614](https://github.com/batfish/batfish/pull/2614), [2612](https://github.com/batfish/batfish/pull/2612).
