### ISSUE TITLE
Juniper vrf-import/export policy support

### ISSUE THREAD

**Issue by vanyasvl** [batfish/batfish#2658]
Batfish now doesn't support policy references, configured as vrf-import or vrf-export in routing instance.

Policy fabric is used as vrf-import policy in routing-instance fabric, but batfish decides that policy fabric is unusedStructure.
Sample config - https://pastebin.com/LCgPcHeq

**Comment by dhalperi** [comment]
Thanks @vanyasvl  - taking a look!
