### ISSUE TITLE
cisco username contains 'sha' parsing error 

### ISSUE THREAD

**Issue by vanyasvl** [batfish/batfish#2705]
Hello.
 
batfish has an issue with parsing 'username sha' on cisco.

**Config part example:**
```
username sha privilege 15 secret 5 $1$YpWC$0bvA3kFjfpMndkILUo6.P.
```
**Batfish output:**
```
  Filename                                               Text  Line                Parser_Context                      Comment
0   cisco-r1  username sha privilege 15 secret 5 $1$YpWC$0bv...   586  [stanza cisco_configuration]  This syntax is unrecognized
```

**Comment by sfraint** [comment]
FYI: Netconan shouldn't care, for this syntax it is searching for a password/hash that is any non-whitespace and in general it finds `$1$...` where `...` is not whitespace, semicolon, or quotes.

**Comment by vanyasvl** [comment]
The problem not in password hash but in the username, if you change sha to other usernames, for example, xxx, no parsing errors will occur.

**Comment by dhalperi** [comment]
Aha, thanks @vanyasvl . Taking a look.

Allowing reserved words as user names for structures... bad move Cisco!
