### ISSUE TITLE
Bandwidth / speed separation

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#2732]
Batfish currently does not differentiate between interface `speed` and `bandwidth` on Cisco devices. They are usually the same but can be different: https://etherealmind.com/basics-difference-bandwidth-speed/

Cc: @arifogel

**Comment by dhalperi** [comment]
What's the desired outcome?

- fields for both in the VI model?
- fixing a bug with bandwidth computation under some scenario?

etc?

**Comment by ratulm** [comment]
We definitely need two fields in the VI model. 

Given that there is only one field, whether there is a bug is unclear to me. Batfish outputs different bandwidths for the two cases below which differ on whether speed is explicitly specified. 
```
interface GigabitEthernet0/1
 bandwidth 128
 ip address 10.10.10.162 255.255.255.252
 media-type sfp
``` 
```
interface GigabitEthernet0/1
 bandwidth 128
 ip address 10.10.10.162 255.255.255.252
 media-type sfp
 duplex full
 speed 100
```
