### ISSUE TITLE
An object-based REST API for Batfish

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#278]
Right now, the server and client use raw JSONObject or JSONArray as the inputs/outputs of API calls. This in general makes the APIs hard to understand, hard to develop, hard to test, and leads to clients and servers getting out of sync. (E.g., https://github.com/batfish/batfish/issues/212).

If we switch to an entity-based REST API (e.g., using Jackson to automatically turn POJOs into JSON) we can have a clearer definition of what our APIs accept and return. I think this will be a strong improvement in the long run.

We can also:

- Move everything from POST to a proper RESTful design
- Move confidential information from query parameters that show up in URIs to HTTP headers
- Take advantage of browser caching at the HTTP level
- ... etc.
- and of course improve testing.

**Comment by dhalperi** [comment]
We've made a bunch of progress here.

**Comment by PenguinzPlays** [comment]
Any documentation for this?
