### ISSUE TITLE
Implement prefix-limit, accepted-prefix-limit

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#2793]
Documentation here:
https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/prefix-limit-edit-protocols-bgp.html
https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/accepted-prefix-limit-edit-protocols-bgp.html

The Cisco version of that feature is maximum-prefix https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/25160-bgp-maximum-prefix.html

**Comment by dhalperi** [comment]
For now, we've decided not to do this. Too hard to understand which prefixes will get deployed.
