### ISSUE TITLE
There is warning/error messages when it load the Paloalt's config.

### ISSUE THREAD

**Issue by takmiz** [batfish/batfish#2938]
When I'm loading paloalto config to batfish , it happend error messages.
If I exclude `set network ike..` command in config, it not happend error messages but  it happend warning messages.. Coud you tell me whether I could load paloalto config.

- error message is bellow.
![error](https://user-images.githubusercontent.com/19756939/51026847-d1484280-15d2-11e9-89bd-b439ced44e44.PNG)

- warning message is bellow.
![warning](https://user-images.githubusercontent.com/19756939/51026679-6eef4200-15d2-11e9-863a-790913996af4.PNG)

- paloalto config is bellow link.
[palo.txt](https://github.com/batfish/batfish/files/2749065/palo.txt)

**Comment by ratulm** [comment]
@takmiz - thanks for reporting the issue and sharing the config. 

the warning message shows up even if a single line is unrecognized by the parser, which usually happens for new configs, and it is usually OK to proceed despite the warning. 

we'll look into the error/warnings and see what is needed. 

FYI, @sfraint.
