### ISSUE TITLE
need to refactor *_VAR constants for easier sorting

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#303]
Currently, all Jackson property names are constants with names like `DESCRIPTION_VAR`, etc.
The placement of `_VAR` at the end of the constant name hinders sorting. Furthermore, `VAR` itself is not appropriately descriptive.
I suggest every such constant be refactored to `PROP_(name)` from `(name)_VAR`.
However, I am open to other naming suggestions.

**Comment by arifogel** [comment]
I should note that this refactoring should only occur for Jackson properties. Any constants ending in _VAR used in other places (e.g. org.batfish.z3.* packages) should be left alone.

**Comment by kidsbear** [comment]
Hi, @arifogel  I'm just curious why you say 'The placement of _VAR at the end of the constant name hinders sorting'. If we sort them in alphabetical order, why the refactoring will make a difference? Thanks~

**Comment by arifogel** [comment]
I should have been more specific. I meant that I wanted PROP_ constants separate from other constants after alphabetical sorting. By moving the prefix to the beginning, this is accomplished.
