### ISSUE TITLE
reachability question with type={multipath,reduced} ignores all four nodeRegex parameters

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#317]

**Comment by dhalperi** [comment]
Ari, can you take a look and flesh out the issue description so that we could pass it off to someone else?

**Comment by arifogel** [comment]
Reachability question can be scoped with:
- `finalNodeRegex`: Only return packets that end up being dropped at or accepted by nodes matching this regex.
- `notFinalNodeRegex`: Only return packets that __do not__ end up being dropped at or accepted by nodes matching this regex.
- `ingressNodeRegex`: Only return packets that start at a node matching this regex.
- `notIngressNodeRegex`: Only return packets that __do not__ start at a node matching this regex.

Apparently these parameters are ignored when type is `multipath` or `reduced`.

**Comment by dhalperi** [comment]
This is largely fixed by follow-on work to rewrite the whole structure of reachability-like questions.
