### ISSUE TITLE
Juniper, disable parameter ignore under protocol bgp

### ISSUE THREAD

**Issue by dgarros** [batfish/batfish#3443]
I noticed that the `disable` parameter is ignored when configured under `protocols bgp`
I tried to disable bgp completely on my configuration but batfish still consider all BGP sessions as active

```
protocols {
    bgp {
        disable;
```

**Comment by dhalperi** [comment]
@progwriter , @corinaminer to triage. Does the engine let you disable protocols at all? If so, where? If not, we should.

**Comment by corinaminer** [comment]
`set protocols [protocol] disable` is not currently parsed for BGP, OSPF, or IS-IS.

**Comment by dhalperi** [comment]
Suppose it were, could we support it?

**Comment by corinaminer** [comment]
Yes; the question is how we want the disabled protocol to look in the vendor-independent datamodel. We could:
1. Prevent the disabled protocol from being converted into the VI datamodel. This would be straightforward and should yield correct routes/reachability, but Batfish wouldn't be able to give any information about the disabled protocol's configuration.
2. Still propagate the protocol's settings into the VI datamodel, and keep track of its disabled status throughout data plane calculation (and possibly a few other places). This would be more complex and prone to errors (if the status isn't checked in places where it should be), but it would still be possible to query the disabled protocol's configuration.

Option 2 is probably the right option in the long term (unless there's a better option 3 I'm missing).

**Comment by dgarros** [comment]
I think 1/ would be acceptable and closer to the reality. 
When a section of the configuration is disabled, the device ignore it so it would make sense to me that batfish would ignore it too.
The most important for me is to be sure that any BGP/ISIS session that would be down on a real devices will be correctly emulated by Batfish.

**Comment by corinaminer** [comment]
Option 1 is implemented for BGP: when `disable` is configured, no corresponding BGP process is created in the VI datamodel. Similar work is in progress for `disable` in other protocols.
