### ISSUE TITLE
path policy question

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#345]
@ratulm To check that a class of traffic originating at ingressNode/iface to some destination always traverses an ordered set of waypoints, it seems that would be doable using the traceroute question. Specifically, use traceroute underneath to get all paths, and check that each contains the ordered waypoints. Makes sense?

**Comment by ratulm** [comment]
yeah, that makes sense. for better client-side usability, one could even implement a waypoint question that does the post-processing on the server side after computing the traceroute (and maybe shows paths that do not meet the waypointing criteria).

**Comment by jkhourybbn** [comment]
Yeah that's what i was thinking. I'll keep this open so we can implement against it

**Comment by jkhourybbn** [comment]
@ratulm some more thoughts:

I think the better way of doing this is to extend the reachability query instead with arguments `TransitNode`, and `notTransitNode` which by default are unused

In order to verify that all traffic from source subnet must go through a `TransitNode` in order to reach a destination subnet, we can posit the reachability query 
```
get reachability type="standard", ingressNodeRegex="from", srcIps=["1.1.1.0/24"], dstIps=["2.2.2.2"], actions=["accept"], notTransitNode="waypoint"
```
This adds an expression to the NoD query conjunction `not (R_transit_waypoint ...)`

This approach has many advantages over the traceroute because it allows all the reachability query expressiveness, and it searches the whole space for a counterexample (the absence of which means correctness). If we use trace route, we will have to create N^2 explicit queries from all source to all destination IPs and analyze them 

Makes sense?

**Comment by ratulm** [comment]
yes, that would work great, assuming that you don't need to reason about an "ordered set of waypoints" (per your original spec).  my sense is that ordering may be harder to encode in the reachability query, though an easy extension might allow for more than one waypoint.

**Comment by jkhourybbn** [comment]
Yes I added a set of waypoints I am calling 'transitNodes' and 'notTransitNodes'. Will push a PR tomorrow. Tx

**Comment by dhalperi** [comment]
Thanks!
