### ISSUE TITLE
make spoofing optional in reachability query

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#346]
Currently, when specifying reachability queries, despite specifying an ingressNode, the solver does not restrict the source IPs possibly returning a set of spoofed packets originating at the ingressNode. This behavior is interesting in certain cases, and uninteresting in many other cases (e.g., when spoofing is already handled at layer2). Right now, one has to specify ingressNode and then search for the interface IP of the ingressNode and set srcIPs accordingly to force the solver to not consider spoofing. 

@ratulm Does it make sense to add an option `noSpoofing` to the reachability query to force every NoD job to use the interface Ip of the ingressNode (similar to traceroute)?

**Comment by ratulm** [comment]
yeah, that make sense, and it seems like a useful flag.

**Comment by dhalperi** [comment]
This is largely supported by the new work for reachability questions with location and srcIp specifiers.

For an example, see SpecifiersQuestion. Also, when things are unclear, feel free to ask for help on Slack!
