### ISSUE TITLE
ISP modeling: Usability

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#3518]
- Warn when the input is wrong (e.g., the hostname does not exist or the interface does not exist on the node).

- Name matching should be case insensitive

- Warn when ISPs cannot be attached for some reason

(There may be other failure modes, but these are the ones I encountered.)

**Comment by haverma** [comment]
closed by https://github.com/batfish/batfish/pull/3522 and https://github.com/batfish/batfish/pull/3538
