### ISSUE TITLE
Cisco ASA IP address of the interface in HA mode

### ISSUE THREAD

**Issue by Vadims06** [batfish/batfish#3629]
Hi team, we noticed that batfish cannot parse ASA's interface configuration with HA mode.
ASA config:
```
interface GigabitEthernet0/0.500
 vlan 500
 nameif ha-test
 security-level 100
 ip address 55.55.55.1 255.255.255.0 standby 55.55.55.2
```
Cisco switch config:
```
interface GigabitEthernet1/0/1
 description lab-asa Gi0/0
 switchport trunk encapsulation dot1q
 switchport trunk allowed vlan 500
 switchport mode trunk
!
interface Vlan500
 ip address 55.55.55.3 255.255.255.0
 ip ospf 500 area 0
```
Batfish config parsing results:
parse_warning = bfq.parseWarning().answer().frame()
parse_warning
![image](https://user-images.githubusercontent.com/20796986/56271530-63e00c80-6101-11e9-8b8c-fb1c7f00a85f.png)

L3 connection checking:
bfq.edges( edgeType="layer3").answer().frame()

> no outputs

I tried to delete `standby 55.55.55.2` statement, but the same error appeared. Any comments?..

**Comment by arifogel** [comment]
Thanks for your report!
The `[cisco_configuration]` parser context indicates to me that there is a parsing error above the `ip address` line.
From what I can tell the `vlan 500` line is being improperly processed as a top-level vlan declaration.
We will release a fix shortly.

**Comment by arifogel** [comment]
@Vadims06 What version of ASA are you using? The VM I have (version 9.7(1)) does not support the `vlan` command inside of `interface` configuration.

**Comment by arifogel** [comment]
Sorry ignore my last question. I was not using a subinterface when I tested the first time.

**Comment by Vadims06** [comment]
Thanks, Ari. Should I expect new commit in allinone container?

**Comment by dhalperi** [comment]
Yes, this was released in the 2019-04-19 release last week. https://github.com/batfish/batfish/releases/tag/v.2019.04.19
