### ISSUE TITLE
Cisco ASA Port-Channel issue

### ISSUE THREAD

**Issue by Vadims06** [batfish/batfish#3676]
Hi team, we noticed that batfish cannot parse ASA's interface configuration if configuration wrapped in port-channel config.
**ASA config:**
interface Port-channel1.500
 vlan 500
 nameif ha-test
 security-level 100
 ip address 55.55.55.1 255.255.255.0 standby 55.55.55.2
!
interface GigabitEthernet0/0
 channel-group 1 mode active
 no nameif
 no security-level
 no ip address

**Cisco switch config:**
interface GigabitEthernet1/0/1
 description lab-asa001cn Gi0/0
 switchport trunk encapsulation dot1q
 switchport trunk allowed vlan 500
 switchport mode trunk
 channel-protocol lacp
 channel-group 1 mode active
!
interface Port-channel1
 switchport trunk encapsulation dot1q
 switchport trunk allowed vlan 500
 switchport mode trunk
!
interface Vlan500
 ip address 55.55.55.3 255.255.255.0
 ip ospf 500 area 0

Batfish any warnings in bfq.parseWarning().answer().frame()

L3 connection checking does't show anything:
bfq.edges( edgeType="layer3").answer().frame()

no outputs

Any comments?..

**Comment by ratulm** [comment]
@arifogel , @progwriter - were you in the neighborhood of this issue recently?

**Comment by progwriter** [comment]
Hi @Vadims06 this issue has been fixed by #3674 and the fix should already be available in the latest docker container (as of 2019-04-22)
