### ISSUE TITLE
Multiple OSPF processes. Tracert path broken

### ISSUE THREAD

**Issue by Vadims06** [batfish/batfish#3702]
Hi, team. We got wrong tracert output if we use two ospf processes. For example, we test in the following scheme:
cisco_sw1 -- OSPF PID 1 -- OSPF PID 1 **cisco_router** -- OSPF PID 2 --  OSPF PID 1 -- cisco_sw2  -|networks_B
We have summary-address of networks_B in ospf pid 1 on the cisco router and as a result, we hide all networks (where cisco_sw2 is placed) behind cisco_router (from cisco_sw1 point of you).
`bfq.edges(edgeType="layer3").answer().frame()` 
shows the connection between cisco_sw1 and cisco_router, cisco_router and cisco_sw2 correctly. But 
`bfq.traceroute(startLocation="cisco_sw1", headers=HeaderConstraints(srcIps="cisco_sw1[Vlan1]", dstIps='cisco_sw2[Vlan1]')).answer().frame()` 
follow us to default route of cisco_sw1 not summary address of networks_B.
You already mentioned in #925, that you keep process id in ospf, but probably mapping between two ospf processes is not deployed.
**Just to sum it up**: cisco_sw1 should rely on summary address and route the packet to cisco_router, then the cisco_router should rely on his own RIB specifically based on routing information from ospf pid 2, then follow SPT path to networks_B. 
@dhalperi, @progwriter  could you please check it

**Comment by progwriter** [comment]
Hi @Vadims06 
This is likely because we currently ignore one of the OSPF processes on `cisco_router`.
We're are nearly done with support for multiple OSPF processes, so this should get resolved fairly soon!

**Comment by Vadims06** [comment]
Hi @progwriter @corinaminer. Is there any update regarding this issue?..

**Comment by progwriter** [comment]
@Vadims06 We are currently working on this! 
If you have the ability to share your configs, we'd greatly appreciate it; It would help us ensure the fix works for your use case.

**Comment by corinaminer** [comment]
Added support for multiple OSPF processes in #3799, and we'll release a new docker image with the update sometime tomorrow (will add a comment on this issue when it's ready). Excited for you to try it out, @Vadims06 -- let us know if you run into any issues.

**Comment by corinaminer** [comment]
New docker image with support for multiple OSPF processes is now out.
