### ISSUE TITLE
Interface type is computed wrongly in POJO topology

### ISSUE THREAD

**Issue by haverma** [batfish/batfish#3904]
We wrongly mark interface type as `UNKNOWN` in POJO topology because  we are looking for an interface in the wrong Configuration node.
https://github.com/batfish/batfish/blob/06a5b316b516e566d719bd56a11b0f47030f3e90/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/pojo/Topology.java#L47-L63

**Comment by progwriter** [comment]
@haverma Fixed by #4388?
