### ISSUE TITLE
Error Adding Snapshot - Windows

### ISSUE THREAD

**Issue by spazman998** [batfish/batfish#3922]
I'm getting issues when trying to add a snapshot using bf_init_snapshot.
The issue appears to be how windows handles temp files you cannot call open when it is already open like you can in linux. Is there a workaround for this? I have tried setting delete=False on the temp file and closing it so the open will work but that just throws me an error with the packaging of the snapshot.

https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
tempfile.NamedTemporaryFile(mode='w+b', buffering=None, encoding=None, newline=None, suffix=None, prefix=None, dir=None, delete=True)
This function operates exactly as TemporaryFile() does, except that the file is guaranteed to have a visible name in the file system (on Unix, the directory entry is not unlinked). That name can be retrieved from the name attribute of the returned file-like object. **Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later)**. If delete is true (the default), the file is deleted as soon as it is closed. The returned object is always a file-like object whose file attribute is the underlying true file object. This file-like object can be used in a with statement, just like a normal file.

Causes the below error:

`
"C:\Program Files\Python37\python.exe" C:/Networking/Projects/Python/batfish/batfish.py
Successfully loaded 55 questions from remote
Traceback (most recent call last):
  File "C:/Networking/Projects/Python/batfish/batfish.py", line 5, in <module>
    bf_init_snapshot('C:\\Networking\\Projects\\Python\\batfish')
  File "C:\Program Files\Python37\lib\site-packages\pybatfish\client\commands.py", line 415, in bf_init_snapshot
    extra_args=extra_args)
  File "C:\Program Files\Python37\lib\site-packages\pybatfish\client\session.py", line 587, in _init_snapshot
    file_to_send)
  File "C:\Program Files\Python37\lib\site-packages\pybatfish\client\workhelper.py", line 353, in get_data_upload_snapshot
    'filename', open(file_to_send, 'rb'),
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\johndoe\\AppData\\Local\\Temp\\tmpfe8xcfv8'
`

**Comment by progwriter** [comment]
Hi @spazman998 
This issue should be fixed now. You will need to update your pybatfish to the newest version (e.g., with `pip install --upgrade git+https://github.com/batfish/pybatfish.git`) 

Let us know if you experience other issues.
