### ISSUE TITLE
Juniper IS-IS export policy support for redistribution

### ISSUE THREAD

**Issue by wz88** [batfish/batfish#4109]
Exporting a policy for redistribution purposes under IS-IS is not supported

config snippet:
```
isis {
    export <policy_statement>;
    reference-bandwidth 100g;
    level 2 disable;
...
}
```

**Comment by progwriter** [comment]
@wz88 
We implemented support for this in #5086, should be available in the next release!
If you are eager to try out the pre-release, you can use the `test-267` tag for the `batfish` or `allinone` docker container. 
For example, 
`docker run --name batfish -v batfish-data:/data -p 8888:8888 -p 9997:9997 -p 9996:9996 batfish/allinone:test-267`
