### ISSUE TITLE
Juniper policy-statement terms support multiple communities

### ISSUE THREAD

**Issue by wz88** [batfish/batfish#4110]
For terms definition under policy-statements, having a list of communities is not supported

config snippet:
```
policy-options {
    policy-statement intra {
        from community [ <community_a> <community_b> ];
        then reject;
    }
}
```

**Comment by dhalperi** [comment]
Hi @wz88! Thanks for the report.

I'm having a hard time confirming your particular issue. Can you provide a slightly more context?

From what I can tell, `prefix-list` does not have `from community` statements. What device type are you on? Did you mean `policy-statement`?

I created a very simple config using a `policy-statement`. When I run `show`, the output looks like this:

```
policy-options {
    policy-statement foo {
        from community [ 1 2 3 ];
        then reject;
    }
}
```

and the `show | display set` version looks like this:

```
set policy-options policy-statement foo from community 1
set policy-options policy-statement foo from community 2
set policy-options policy-statement foo from community 3
set policy-options policy-statement foo then reject;
```

Batfish handles both of these.

**Comment by wz88** [comment]
Hi @dhalperi, thank you for the prompt reply.  Yes, I meant `policy-statement` and not `prefix-list`, I updated the issue.

It was not working until recently.  Did it get added lately?

**Comment by dhalperi** [comment]
I do not think anything major changed here recently -- I can double-check and get back to you.

Just to double-check: your updated snippet still has some syntax missing: Is `from [ <community_a> <community_b> ];` actually legal on your device? On mine, it needs to be `from community [...];` like in my example?

**Comment by wz88** [comment]
I fixed that as well

**Comment by dhalperi** [comment]
I don't see that anything has changed in our handling of communities in the parsers. In March we improved parsing for standard communities.

If you have a line that is not handled correctly by the latest Batfish docker release, please reopen with more details?

Thanks!
