### ISSUE TITLE
bfq.undefinedReferences false positive for community list

### ISSUE THREAD

**Issue by clay584** [batfish/batfish#4121]
This is showing up as an undefined reference, but it is defined in this particular configuration. I am unable to provide bf_upload_diagnostics or a netconan scrubbed configuration. I just can't. Hopefully this is enough information to fix.

Vendor: Cisco
OS: NXOS
Version: 7.0(3)I5(2))

Struct_Type | Ref_Name | Context
-- | -- | --
community-list | bgp-to-ospf | route-map match community-list

Relevant lines from the running config:

```
ip community-list standard bgp-to-ospf seq 10 permit 65001:65211
route-map bgp-to-ospf deny 10
  match community bgp-to-ospf
```

**Comment by progwriter** [comment]
Hi @clay584, looking at the [nxos docs](https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/nxos/commands/bgp/ip-community-list.html) it seems like having `seq 10` is not valid syntax in the community list definition.

If I switch your community list definition line to
`ip community-list standard bgp-to-ospf permit 65001:65211` everything parses fine.

If there is some other variant or I am looking at the wrong docs, let me know and I can look into it in more detail.

**Comment by dhalperi** [comment]
Hey @clay584  - I got a change to try this on my nxos emulator - 7.3(0)D1(1) - and it rejects this command as invalid like @progwriter said.

Can you confirm this configuration came as-is off of a running device? Can you add more detail about the specific device type?

Thanks!

**Comment by clay584** [comment]
It definitely came off of a running device from one of my customers. It is a Nexus 9k switch. Here is the documentation that shows that this command is valid.

[Command Reference for version 7.0(3)I5(1)](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/command_references/configuration_commands/b_N9K_Config_Commands_703i5x/b_N9K_Config_Commands_703i5x_chapter_01001.html#wp2867838948)

I also logged into one of Cisco DevNet's always-on sandboxes running NX-OS 9.2(1) and it is valid as well.  If you want to log in and take a look, I just put the configuration on their device to test. It's in the running-config right now.

`sbx-nxos-mgmt.cisco.com:8181`
`admin`
`Admin_1234!`

**Comment by dhalperi** [comment]
Thanks @clay584 !

I typed these into a n9k emulator:

```
ip community-list standard foo permit  1
ip community-list standard foo seq 20 permit  2
ip community-list standard foo permit  3
```

and got this out:

```
ip community-list standard foo seq 1 permit 0:1 
ip community-list standard foo seq 20 permit 0:2 
ip community-list standard foo seq 21 permit 0:3 
```

I know what to do :)

**Comment by clay584** [comment]
Oops, hit the wrong button. Didn't mean to close the issue.

**Comment by dhalperi** [comment]
Minor update: @arifogel is about to flip the switch (~this week) on a newly-rewritten NX-OS parser, which will resolve this bug.

**Comment by dhalperi** [comment]
Hey @clay584 - we flipped the bit, and the next release will be using the new parser.

But since the new parser is a complete from-scratch rewrite, you may see a few unexpected issues. Please continue to file them!
