### ISSUE TITLE
Interface Int-Name on Cisco ASA is missing bandwidth, cannot compute OSPF cost

### ISSUE THREAD

**Issue by Vadims06** [batfish/batfish#4124]
Hi Team,
I pulled updated allinone container and try to parse Cisco ASA config, but unfortunately, I got an unexpected error. One month ago I didn't get any error with the same config!
I have standard interface config
```
interface Port-channel1.1
 vlan 1
 nameif LAB-INT
 security-level 10
ip address 192.168.1.1 255.255.255.0 standby 192.168.1.2
```
*** SERIALIZING 5 VENDOR-INDEPENDENT CONFIGURATION STRUCTURES FOR SNAPSHOT 85726F9D-1291-478B-8030-5AF260B3AAF0***
Exception in container:***8c0b, testrig:***3aaf0; exception:java.lang.IllegalStateException: Interface *LAB-INT* on asa1 is missing bandwidth, cannot compute OSPF cost

**Comment by dhalperi** [comment]
@Vadims06 -- thanks for the report! I think we added some new checks recently during conversion, and maybe something is messed up with `nameif` in ASA.

Can you provide a very minimal reproduction? I'm certain we can fix this (and add regression tests) very quickly :)

**Comment by dhalperi** [comment]
I was able to reproduce with:

```
!
ASA Version 9.6(3)8
interface Port-channel1.1
 vlan 1
 nameif LAB-INT
 security-level 10
 ip address 192.168.1.1 255.255.255.0 standby 192.168.1.2
router ospf 2
 network 192.168.0.0 255.255.0.0 area 0
```

**Comment by dhalperi** [comment]
Hey @Vadims06  - even thoguh I have a plausible fix, I'd like to see more of your configuration to make sure my fix is actually useful in practice... Can post here or reach out on #batfish slack.

**Comment by Vadims06** [comment]
Hi, @dhalperi, actually additionally I have only aggregate address 192.168.0.0 in router ospf 1. That's all.
