### ISSUE TITLE
ACL Tests: Zero Trust Testing

### ISSUE THREAD

**Issue by supertylerc** [batfish/batfish#4147]
Hello!

Is it possible to use Batfish to test a "zero trust" (buzzword bingo) ACL?

Here's a brief example:

I have a simple NX-OS ACL that looks like the following:

```
ip access-list zero-trust
permit tcp 10.0.1.0/24 10.0.2.0/24 eq 443
deny ip any any
```

I want to test that `10.0.1.1` can talk to `10.0.2.1` on port `443`.  This part is easy and well-documented.

However, I also want to test that no other ports are allowed.  I'm unsure of how to go about this without writing individual random tests and basically doing a "spot check."

The more complex use case is to have a defined list of ports that are OK to allow, and if you write an ACL that violates that policy, the test fails so that you have to go have a bigger conversation to get the port approved.  For example, a security team says something like:

```
By default, everything outbound is denied.  You can add exceptions that are outbound to port 443/tcp, but anything else must go through additional review and have special exceptions written.
```

So, using the example above, I would want tests to fail if I added port `36537` (just a random port) to the ACL, but I don't want to have to write a test for that specific port.

Thanks!

**Comment by anothermattbrown** [comment]
Hi @supertylerc! This is a great question. The batfish question you want in this case is [searchFilters](https://pybatfish.readthedocs.io/en/latest/questions.html#pybatfish.question.bfq.searchFilters). It allows you to search for packets that are permitted or denied by an ACL, and you can specify a set of headers to search within. This lets you verify that the ACL permits every packet it should and nothing else.

I've attached a short jupyter notebook showing how to do this for your ACL here:
 [zero-trust.zip](https://github.com/batfish/batfish/files/3327763/zero-trust.zip). See the [pybatfish](https://github.com/batfish/pybatfish) docs for instructions on how to run it. Here are the key snippets:

```python
# Initialize a new snapshot with a single device containing your ACL
ss = bf_session.init_snapshot_from_text(
    platform="cisco-nx",
    text="""
ip access-list zero-trust
permit tcp 10.0.1.0/24 10.0.2.0/24 eq 443
deny ip any any
""")
```

```python
# Check if anything is permitted by the ACL. (returns 1 example header)
bfq.searchFilters().answer()
```
<img width="900" alt="Screen Shot 2019-06-25 at 6 06 08 PM" src="https://user-images.githubusercontent.com/15133240/60143645-f6410400-9773-11e9-8bb9-c5cf97de4dcb.png">


```python
# Verify that it permits everything it should. To do this,
# we search for errors: packets that should be permitted 
# but are actually denied. (returns 0 headers)
bfq.searchFilters(
    headers=HeaderConstraints(
        srcIps="10.0.1.0/24", 
        dstIps="10.0.2.0/24", 
        dstPorts="443", 
        ipProtocols="tcp"), 
    action="deny").answer()
```

```python
# Make sure no other flows are permitted. To do this,
# use invertSearch to search outside the specified 
# headerspace. (returns 0 headers)
bfq.searchFilters(
    headers=HeaderConstraints(
        srcIps="10.0.1.0/24", 
        dstIps="10.0.2.0/24", 
        dstPorts="443", 
        ipProtocols="tcp"),
    action="permit",
    invertSearch=True).answer()
```

For more about this, see our jupyter notebooks on [Analyzing ACLs and Firewall Rules](https://github.com/batfish/pybatfish/blob/master/jupyter_notebooks/Analyzing%20ACLs%20and%20Firewall%20Rules.ipynb) and [Provably Safe ACL and Firewall Changes](https://github.com/batfish/pybatfish/blob/master/jupyter_notebooks/Provably%20Safe%20ACL%20and%20Firewall%20Changes.ipynb). 

Thanks, and let us know if you have any more questions.

**Comment by supertylerc** [comment]
Thank you!  I think `invertSearch` is the piece I was missing.
