### ISSUE TITLE
Match Metric causes dataplaning failure

### ISSUE THREAD

**Issue by Volcanon-** [batfish/batfish#4167]
See below for the stack trace - it seems like if you have match metric in your config somewhere it will parse and trip an exception in the code.  Totally reproduce-able with match metric in Juniper configs.

containers/5ddc2d68-a49f-4666-8112-d0f75a29b1a8/snapshots/c3ae673e-b469-470e-ac45-320adb243c74/output/fefcff83-71f8-4f0f-96b5-4c21a04f43b3.log:	at org.batfish.datamodel.routing_policy.expr.MatchMetric.evaluate(MatchMetric.java:39)
containers/5ddc2d68-a49f-4666-8112-d0f75a29b1a8/snapshots/c3ae673e-b469-470e-ac45-320adb243c74/output/fefcff83-71f8-4f0f-96b5-4c21a04f43b3.log:{"answerElements":[{"class":"org.batfish.common.BatfishException$BatfishStackTrace","answer":["org.batfish.common.BatfishException: No implementation for MatchMetric.evaluate()","   at org.batfish.datamodel.routing_policy.expr.MatchMetric.evaluate(MatchMetric.java:39)","   at org.batfish.datamodel.routing_policy.expr.Conjunction.evaluate(Conjunction.java:52)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:88)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:117)","   at org.batfish.datamodel.routing_policy.expr.CallExpr.evaluate(CallExpr.java:61)","   at org.batfish.datamodel.routing_policy.expr.FirstMatchChain.evaluate(FirstMatchChain.java:66)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:88)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:117)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:220)","   at org.batfish.dataplane.ibdp.VirtualRouter.exportNonBgpRouteToBgp(VirtualRouter.java:1856)","   at org.batfish.dataplane.ibdp.VirtualRouter.lambda$queueOutgoingRoutesPerEdge$30(VirtualRouter.java:1350)","   at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)","   at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)","   at java.util.Collections$2.tryAdvance(Collections.java:4717)","   at java.util.Collections$2.forEachRemaining(Collections.java:4725)","   at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)","   at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)","   at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)","   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)","   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)","   at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)","   at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)","   at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)","   at org.batfish.dataplane.ibdp.BgpRoutingProcess.enqueueBgpMessages(BgpRoutingProcess.java:707)","   at org.batfish.dataplane.ibdp.VirtualRouter.enqueueBgpMessages(VirtualRouter.java:2166)","   at org.batfish.dataplane.ibdp.VirtualRouter.queueOutgoingRoutesPerEdge(VirtualRouter.java:1435)","   at org.batfish.dataplane.ibdp.VirtualRouter.newBgpSessionEstablishedHook(VirtualRouter.java:1678)","   at org.batfish.dataplane.ibdp.VirtualRouter.queueInitialBgpMessages(VirtualRouter.java:1644)","   at org.batfish.dataplane.ibdp.IncrementalBdpEngine.lambda$computeNonMonotonicPortionOfDataPlane$33(IncrementalBdpEngine.java:631)","   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)","   at java.util.Collections$2.tryAdvance(Collections.java:4717)","   at java.util.Collections$2.forEachRemaining(Collections.java:4725)","   at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)","   at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)","   at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)","   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)","   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)","   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)","   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)","   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)","   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)","   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)",""]}],"status":"FAILURE","summary":{"numFailed":0,"numPassed":0,"numResults":0}}

**Comment by saparikh** [comment]
@Volcanon- please append a sanitized version of the configuration file that triggered this error. If you need to anonymize it, check out https://github.com/intentionet/netconan

**Comment by dhalperi** [comment]
@progwriter can probably triage this without a repro, since it's kinda obvious from a code POV

**Comment by Volcanon-** [comment]
Sadly I won't be able to provide a full config anytime soon, but if I have time I will try to cut a small sample config that shows the problem. 

You might be able to see it in action by just uncommenting this: https://github.com/batfish/batfish/blob/e25bf2ddf625d477e174a179eb4562177f3a9d05/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term#L50
