### ISSUE TITLE
Document Cumulus NCLU in packaging snapshots for analysis

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#4176]
I'd expect it to be about here: https://github.com/batfish/batfish/wiki/Packaging-snapshots-for-analysis#format-for-f5-big-ip-configuration-files

Otherwise folks may try submitting FRR data instead.

**Comment by dhalperi** [comment]
Should probably also have links off the readme?

**Comment by ratulm** [comment]
removing myself as @arifogel and @saparikh know the exact commands. 

Yes, we should link off of the README. 

(Palo Alto also needs specific instructions?)

**Comment by saparikh** [comment]
Cumulus instructions updated in the Wiki. If PA needs specific instructions, a separate issue should be created.
