### ISSUE TITLE
Juniper Community Lists Matching Logic

### ISSUE THREAD

**Issue by Volcanon-** [batfish/batfish#4190]
I had a case where I had a community list like this:

community COMM1 members [ 1:2 3:4 ];

And I had a policy which matched on this and then applied additional communities.  The problem I was having is that routes with just 3:4 were being matched on this.  When I removed 3:4 from the list it wasn't an issue, but it seems like Batfish is performing a logical OR on these, when it should be ANDing them.

A simple test bench should be able to confirm this behavior.  Let me know if you need more info.

Juniper Doc ref:
https://www.juniper.net/documentation/en_US/junos/topics/concept/policy-bgp-communities-extended-communities-evaluation-in-routing-policy-match-conditions.html

**Comment by dhalperi** [comment]
I believe @arifogel has fixed this now, but we'll confirm and get back to you @Volcanon-

**Comment by arifogel** [comment]
This has already been fixed, though a test was missing.
I added an appropriate test in #4885.
