### ISSUE TITLE
Parsing of BGP Neighbor in IOS-XR Fails Without Remote AS on the Same Line

### ISSUE THREAD

**Issue by supertylerc** [batfish/batfish#4194]
# Environment

Docker container, `batfish/allinone:

```bash
$ docker images batfish/allinone:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
batfish/allinone    latest              e64498ac4338        8 hours ago         959MB
```

# Problem

With IOS XR, you do not have to specify the `remote-as` on the same line as the neighbor.  However, the parser seems to think that a `neighbor <ip>` line on its own is a problem.  Example of functional IOS XR configuration that raises parsing warnings in Batfish:

```
router bgp 65501
 neighbor-group EXAMPLE
  remote-as 65502
  address-family ipv4 unicast
   soft-reconfiguration inbound
  !
 !
  neighbor 1.2.3.4
    use neighbor-group EXAMPLE
    description "example router"
  !
!
```

This example uses `neighbor-group`, which also seems to be unsupported, but it can be reproduced even with the following configuration, which is valid IOS-XR configuration:

```
router bgp 65501
  neighbor 1.2.3.4
    remote-as 65502
    description "example router"
  !
!
```

I've tested this using:

```python
bf_session.init_snapshot_from_text(
    platform="cisco-xr",
    text="""
<snip>
"""
```

Followed by looking at the parse warnings.

**Comment by supertylerc** [comment]
If I update the configuration to the following, it is successfully parsed:

```
router bgp 65501
  neighbor 1.2.3.4 remote-as 65502
    description "example router"
  !
!
```

However, this is not the output of IOS XR config when issuing the `sh run` command.

**Comment by dhalperi** [comment]
Thanks @supertylerc. Both `neighbor-group` and neighbors are generally supported, but I'm certain that there are (Batfish) grammar issues here. There may be a quick fix, which I'll take a look at.

Concurrently, we are actively pulling apart the Cisco parsers to make the nuances between Cisco-NX and Cisco-XR and Cisco-IOS and Cisco-XE easier to deal with. In 2013 it was a good idea to build one combined grammar, in 2019 it is not :).

**Comment by supertylerc** [comment]
Thanks, @dhalperi.  Just wanted to update and say that I tried to go back a while and used the `batfish/allinone:latest-39` tag.  It has the exact same problem.

Interestingly, if I change the `platform` to `cisco-nx`, it parses just fine and shows everything as expected.  But that will likely only work for the very small snippet and edge case as the other parts of XR config are very different.  :/

**Comment by supertylerc** [comment]
After much more poking around because I refused to believe this was really broken, this looks like it's actually a combination of user error, documentation, and a platform detection bug in Batfish.

The parser automatically detects the OS based on a comment string.  [The pybatfish docs](https://pybatfish.readthedocs.io/en/latest/api.html#pybatfish.client.session.Session.init_snapshot_from_text) say that if you're going to specify the platform, you should do so with the `platform` parameter and follow the established [RANCID device_type](https://www.shrubbery.net/rancid/man/router.db.5.html#SYNTAX).  For IOS XR, this is `cisco-xr`.  The end result is that `pybatfish` [prepends a string to the configuration](https://github.com/batfish/pybatfish/blob/master/pybatfish/client/session.py#L1092) you make when using `pybatfish.client.session.Session.init_snapshot_from_text` that has this format:

```
!RANCID-CONTENT-TYPE: {platform}
```

This doesn't seem to work with `cisco-xr`, though:

```python
_ = bf_session.init_snapshot_from_text(text="""
!RANCID-CONTENT-TYPE: cisco-xr
router bgp 65501
 neighbor 1.2.3.4
  remote-as 65501
  description "Example"
 !
!""")

load_questions()

bfq.parseWarning().answer().frame().to_csv(seb='\t')
```

This prints:

```
	Filename	Text	Line	Parser_Context	Comment
0	configs/config	neighbor 1.2.3.4	4	[router_bgp_stanza stanza cisco_configuration]	This syntax is unrecognized
1	configs/config	remote-as 65501	5	[router_bgp_stanza stanza cisco_configuration]	This syntax is unrecognized
```

I went digging through the tests and found [this one](https://github.com/batfish/batfish/blob/master/tests/parsing-tests/networks/unit-tests/configs/ios_xr_bgp_neighbor_group#L1), which specifies the platform with:

```
! This is an IOS XR formatted file.
```

I tested this and it works as expected.  I also found that if I used the following string (from the docstring of `pybatfish.client.session.Session.init_snapshot_from_text`), it would successfully parse:

```
!! IOS XR Configuration 5.2.4
```

So it seems that the `RANCID-CONTENT-TYPE` mechanism of determining platform doesn't work with IOS XR.  [VendorConfigurationFormatDetector.java](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java) looks like it's missing the relevant lines to allow that to work, but I know less Java than I do Python, so maybe there's something else at play.  Reading that file, it looks like the only detection for IOS XR is that the string `IOS XR` exists _somewhere_ in the file.

**Comment by dhalperi** [comment]
Thanks, and sorry for the latency in investigating. Holidays + busy...

I'll take a look now.

**Comment by supertylerc** [comment]
No worries!  Hope the holidays were fun.  :)

Thanks for looking!  Probably an easy fix.  :D  I know how to deal with it locally, at least, so this isn't a show stopper.
