### ISSUE TITLE
BGP address-family ipv4 not recognized in Arista EOS

### ISSUE THREAD

**Issue by Alexanderis** [batfish/batfish#4202]
[unrecognized.tar.gz](https://github.com/batfish/batfish/files/3361828/unrecognized.tar.gz)

Hi team,

Batfish is having issues identifying address-family in Arista configs.
I think it may be due to it expecting unicast and multicast keywords like NX-OS, however in Arista these are not present.

Added sample config and debug files generated by Batfish. 
Let me know if this can be fixed.

Cheers,
Alex

**Comment by saparikh** [comment]
@Alexanderis I believe the issue here is that Batfish is not recognizing the config file format as Arista. The parser detection logic looks for one of these lines:
```
! device: foo (DCS-7050SX2-72Q, EOS-4.19.1F)
!
! boot system flash:/EOS-4.19.1F.swi
```

You can also append the `RANCID-CONTENT-TYPE` at the top of the file for configurations that are generated by a template.
