### ISSUE TITLE
IOS XR RPL Sub-Policies Are "Unused References"

### ISSUE THREAD

**Issue by supertylerc** [batfish/batfish#4227]
Latest `batfish/allinone` container.

```python
bf_session.init_snapshot_from_text("""
!IOS XR
route-policy SUB_POLICY
  drop
end-policy
!
route-policy MAIN_POLICY
  apply SUB_POLICY
end-policy
!
router bgp 65501
 neighbor 1.2.3.4
  remote-as 65502
  address-family ipv4 unicast
   route-policy MAIN_POLICY out
  !
!""")
print(bfq.unusedStructures().answer().frame().to_csv(sep='\t'))
```

yields:

```
	Structure_Type	Structure_Name	Source_Lines
0	route-policy	SUB_POLICY	configs/config:[3, 4, 5]
```

The configuration is valid, but Batfish thinks that `SUB_POLICY` is unused.  I have not checked to see if this is an actual issue (i.e., I don't know if Batfish fails to evaluate sub-policies) or if it's just a "cosmetic" problem (i.e., Batfish just says it's unused but in functional testing correctly evaluates the full policy).

**Comment by supertylerc** [comment]
I'm assuming that this is supported functionality; there are test cases that use sub policies.

**Comment by dhalperi** [comment]
You have correctly diagnosed the issue -- subpolicies are indeed supported, but we were missing logging this as a reference. Fix in flight. Thanks @supertylerc !
