### ISSUE TITLE
Juniper OSPF Area Configuration not parsed Correctly by Batfish

### ISSUE THREAD

**Issue by kokasha** [batfish/batfish#4316]
When generating a configuration for Juniper Devices with the below OSPF Area Configuration, Batfish doesn't recognize the OSPF Area section and discard it.

protocols {
    ospf {
        area 0 {
            interface ge-0/0/0.0 {
                interface-type p2p;
                metric 100;
            }
            interface ge-0/0/1.0 {
                interface-type p2p;
                metric 100;
            }
            interface lo0.0 {
                passive;
            }
        }
    }
}

When the OSPF Area Configuration is changed as below BatFish Parse the configuration correctly.

protocols {
    ospf {
        area 0.0.0.0 {
            interface ge-0/0/0.0 {
                interface-type p2p;
                metric 100;
            }
            interface ge-0/0/1.0 {
                interface-type p2p;
                metric 100;
            }
            interface lo0.0 {
                passive;
            }
        }
    }
}

**Comment by kokasha** [comment]
@ratulm This is the OSPF problem that we discussed about on Slack

**Comment by ratulm** [comment]
Fixed by #4289 :)

**Comment by progwriter** [comment]
As @ratulm points out, it is fixed by #4289 and the newest release (v2019.07.31) should contain the fix as well.
