### ISSUE TITLE
EIGRP distribute-list does not work in some cases

### ISSUE THREAD

**Issue by Tachashi** [batfish/batfish#4392]
I tried EIGRP route filter analysis using batfish/allinone:latest-130 docker image. 
(In this image, EIGRP distribute-list analysis has been supported. #4368)

My test environment is like below:

![image](https://user-images.githubusercontent.com/41357228/62377485-d1635c00-b57d-11e9-9e3a-e3061f7b48d9.png)

The route `10.10.1.0/30` is permitted in hqdist1 and denied in hqborder1. This route should not be appeared in the routing table of hqborder1. But the result of `bfq.routes()` in brborder1 shows this.

![bfq routes()_brborder1](https://user-images.githubusercontent.com/41357228/62376919-b217ff00-b57c-11e9-9c26-f5649f92023a.png)
![bfq routes()_hqborder1](https://user-images.githubusercontent.com/41357228/62376922-b6441c80-b57c-11e9-89e3-30fa373552f6.png)
![bfq routes()_hqdist1](https://user-images.githubusercontent.com/41357228/62376935-b93f0d00-b57c-11e9-92a5-738134a5290b.png)

 The routes `192.168.2.0/24` and `192.168.3.0/24`, which are also denied in hqborder1, are not displayed in `bfq.routes()` of brborder1, so distribute-list itself may be functioning.

When `10.10.1.0/30` is denied in both hqdist1 and hqborder1, `bfq.routes()` of these routers didn't show this route (as expected).

[brborder1_shrun (1).log](https://github.com/batfish/batfish/files/3461659/brborder1_shrun.1.log)
[hqborder1_shrun (1).log](https://github.com/batfish/batfish/files/3461660/hqborder1_shrun.1.log)
[hqdist1_shrun (1).log](https://github.com/batfish/batfish/files/3461661/hqdist1_shrun.1.log)

**Comment by progwriter** [comment]
Thanks for the report @Tachashi, we'll take a look.
Can you please share your configs of the 4 devices as well, so that we can reproduce this behavior?

**Comment by Tachashi** [comment]
Actually, I didn't use hqaccess1(L2SW) for router analysis. So three "xxx_shrun (1).log" files are all.
