### ISSUE TITLE
Request for supporting Checkpoint FW

### ISSUE THREAD

**Issue by derwin4o** [batfish/batfish#4403]
Dear All,
do you have any plans for Checkpoint FW's support?

BR!

**Comment by ratulm** [comment]
@derwin4o - Yes, we do. But not ready to commit to a release date yet.

You can help by providing example configs though, which helps us get the work done faster.

**Comment by wareagl** [comment]
Any updates on Checkpoint support?

**Comment by saparikh** [comment]
we are starting to plan the work required to support for Checkpoint firewalls. If you are able to share configs, that would greatly aid in our ability to get a working version out that supports the key features mostly commonly used. 

Netconan can anonymize the configs (https://github.com/intentionet/netconan).

**Comment by steffenschumacher** [comment]
Hey - you still need configs?
I guess it’s the json formatted ones, or are you all set?
It seems like there is some checkpoint support, but possibly not fully or?

**Comment by ratulm** [comment]
Initial support was added and was part of Nov 2021 release. 

Details on how to supply the data are here: https://pybatfish.readthedocs.io/en/latest/formats.html#check-point
