### ISSUE TITLE
Supporting multiple processes on VRFs

### ISSUE THREAD

**Issue by haverma** [batfish/batfish#447]
Currently only one process is supported for processes like OSPF, BGP, RIP etc in VRFs. This causes some indeterministic behavior while converging/propagating routes from these processes into main RIB in cases where there are multiple processes are declared in the configs

**Comment by arifogel** [comment]
Please provide PR with failing junit tests that would be fixed with proper handling.

**Comment by haverma** [comment]
OK, will try to simulate the "Switch customer" configs oscillation through junit tests

**Comment by dhalperi** [comment]
Multiple OSPF processes are now supported.
