### ISSUE TITLE
more robust support and testing for iptables on routers

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#464]
Post-#462 we need to add more robust handling and testing of varied iptables scenarios.
For instance, we should be able to combine global and interface-specific filtration.

**Comment by arifogel** [comment]
@dspicuzzbbn Can you provide us with some more varied iptables files than the on from #462?

**Comment by dspicuzzbbn** [comment]
As we find things that don't work, I'm sure we'll be adding more tests. A lot of what we're doing were along the lines of the files included in the unit tests.

**Comment by jkhourybbn** [comment]
@arifogel @dspicuzzbbn it looks like the current conversion of iptables ignores global rules and only applies per interface rules -- I haven't looked at the code but I can clearly see that global rules are not part of the interface access lists. Can you  confirm and is there a reason why you are dropping those? 

For example, take the mangle rules below
```
*mangle
:PREROUTING DROP [0:0]
# allow OSPF input/output
-A PREROUTING  -s 10.0.0.1 -p 89 -j ACCEPT
# allow all output
-A POSTROUTING -j ACCEPT
# allow traffic forwarding from 10.0.4 subset
-A PREROUTING -s 10.0.3.0/24 -i eth0 -j ACCEPT
-A PREROUTING -s 10.0.4.0/24 -i eth1 -j ACCEPT
COMMIT
```
I only see the last two pre-routing rules being converted when ingested the testrig and the others dropped. The correct behavior instead should be to convert the global rules and apply them to all interfaces. For example,
```
-A PREROUTING  -s 10.0.0.1 -p 89 -j ACCEPT
```
should be applied to both interfaces eth0 and eth1 when no such interface is specified. Similarly for the 
```
-A POSTROUTING -j ACCEPT
```
and the default drop all
```
:PREROUTING DROP [0:0]
```

**Comment by jkhourybbn** [comment]
@arifogel I uploaded a testrig with iptables in #485 if you want to test with it

**Comment by virtuald** [comment]
I'm taking a look now.

**Comment by dspicuzzbbn** [comment]
#488 addresses the overlay problems.
