### ISSUE TITLE
Some NX-OS EIGRP commands are not recognized

### ISSUE THREAD

**Issue by Tachashi** [batfish/batfish#4684]
I tested NX-OS EIGRP route analysis on batfish/allinone:latest-159 by using two NX-OSv9000 switches.

The snippet of configs are below:

- nexus1

```
hostname nexus1

feature eigrp
feature interface-vlan

vlan 2222

interface Loopback0
 ip address 10.1.1.1 255.255.255.255

interface ethernet 1/1
 no switchport
 ip address 192.168.100.1/24
 ip router eigrp Test1
 no shutdown

interface ethernet 1/2
 switchport access vlan 2222
 no shutdown

interface Vlan2222
 ip address 192.168.200.1/24
 ip router eigrp Test1
 ip passive-interface eigrp Test1
 no shutdown

ip route 0.0.0.0/0 192.168.200.2

route-map Route1 permit 10
 match interface Vlan2222

router eigrp Test1
 autonomous-system 33
 redistribute static route-map Route1
 default-metric 1000000 10 255 1 1500
```

- nexus2

```
hostname nexus2

feature eigrp
feature interface-vlan

vlan 3333

interface Loopback0
 ip address 10.2.2.2 255.255.255.255
 ip router eigrp Test1

interface Vlan3333
 ip address 192.168.100.2/24
 ip router eigrp Test1
 ip distribute-list eigrp Test1 prefix-list Prefix1 out
 no shutdown

interface ethernet 1/1
 switchport access vlan 3333
 no shutdown

router eigrp Test1
 autonomous-system 33

ip prefix-list Prefix1 seq 10 permit 10.2.2.2/32
```

In Cisco VIRL simulation environment, the outputs of EIGRP neighbor and routing table are below:

```
nexus1# sh ip eigrp neighbor
IP-EIGRP neighbors for process 33 VRF default
H   Address                 Interface       Hold  Uptime  SRTT   RTO  Q  Seq
                                            (sec)         (ms)       Cnt Num
0   192.168.100.2           Eth1/1          14   00:23:54  14   84    0   3
```

```
nexus1# sh ip route
IP Route Table for VRF "default"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%<string>' in via output denotes VRF <string>

0.0.0.0/0, ubest/mbest: 1/0
    *via 192.168.200.2, [1/0], 00:24:03, static
10.1.1.1/32, ubest/mbest: 2/0, attached
    *via 10.1.1.1, Lo0, [0/0], 00:24:27, local
    *via 10.1.1.1, Lo0, [0/0], 00:24:27, direct
10.2.2.2/32, ubest/mbest: 1/0
    *via 192.168.100.2, Eth1/1, [90/130816], 00:23:56, eigrp-Test1, internal
192.168.100.0/24, ubest/mbest: 1/0, attached
    *via 192.168.100.1, Eth1/1, [0/0], 00:24:33, direct
192.168.100.1/32, ubest/mbest: 1/0, attached
    *via 192.168.100.1, Eth1/1, [0/0], 00:24:33, local
192.168.200.0/24, ubest/mbest: 1/0, attached
    *via 192.168.200.1, Vlan2222, [0/0], 00:24:03, direct
192.168.200.1/32, ubest/mbest: 1/0, attached
    *via 192.168.200.1, Vlan2222, [0/0], 00:24:03, local
```

Full logs:
[nexus1_log.txt](https://github.com/batfish/batfish/files/3563266/nexus1_log.txt)
[nexus2_log.txt](https://github.com/batfish/batfish/files/3563267/nexus2_log.txt)

But in Batfish analysis, some EIGRP command syntax was not recognized:
![image](https://user-images.githubusercontent.com/41357228/64073765-3923d880-ccdd-11e9-9302-10359aae9da9.png)

 Also, the two switches did not form EIGRP neighbor relationships.
![image](https://user-images.githubusercontent.com/41357228/64073809-d3841c00-ccdd-11e9-95d5-4eac70064dc5.png)
![image](https://user-images.githubusercontent.com/41357228/64073859-b56aeb80-ccde-11e9-9f57-d5a98a73d4c8.png)

**Comment by dhalperi** [comment]
Hi @Tachashi - we're close to turning on a completely rewritten Cisco NX-OS parser, which will have much better support for these commands. Please hold tight :).

**Comment by dhalperi** [comment]
@corinaminer - are these all fixed now?

**Comment by corinaminer** [comment]
@Tachashi - as of today, most of these commands are supported. In your sample configs, the EIGRP edge is up and routes are exchanged in current master (we have not yet updated docker images).

However, note that we do not yet support `redistribute static` or `default-metric` for EIGRP. If those are important for you, feel free to comment here or open follow-up issues linked back to this issue.

**Comment by Tachashi** [comment]
@corinaminer Thanks! I'll try using the next release! Our network environment often uses EIGRP and static routing. So it would be very grateful if you could support those functions as well.

**Comment by corinaminer** [comment]
@Tachashi just to let you know, `default-metric` and static redistribution into EIGRP will in fact both be supported in the next release :)

**Comment by Tachashi** [comment]
@corinaminer Awesome! Thanks! :)
