### ISSUE TITLE
Possible issue with parsing default ASAv firewall rules.

### ISSUE THREAD

**Issue by asydney** [batfish/batfish#471]
Hi Batfish folks,
                         The Cisco ASAv (v9.7.1) firewalls are configured by default with rules which block traffic between security zones, unless access-lists explicitly define rules to allow traffic between these zones.  I have one such configuration which only allows ICMP traffic between two zones (named "inside" and "outside"). When I run the configuration through batfish, only the access lists are parsed: i.e. the default rules which block all other traffic by default are not extracted/parsed. Below is a snippet of the configuration (please see the [codepad link](http://codepad.org/lMqNtraC) for the entire result of `get nodes nodeRegex="asa1.*", summary=False`):

```
"ipAccessLists" : {
        "OUTSIDE-INSIDE" : {
          "name" : "OUTSIDE-INSIDE",
          "lines" : [
            {
              "action" : "ACCEPT",
              "dstIps" : [
                "0.0.0.0/0"
              ],
              "ipProtocols" : [
                "ICMP"
              ],
              "name" : "permit icmp any any",
              "negate" : false,
              "srcIps" : [
                "0.0.0.0/0"
              ]
            }
          ]
        }
      },
```

Here is a configuration file which results in this behavior: 
[asa_config.txt](https://github.com/batfish/batfish/files/1331213/asa_config.txt)

Can you please provide feedback?

PS. Adding @jkhourybbn and @dspicuzzbbn to this one.

Cheers!
Ali

**Comment by arifogel** [comment]
We do not currently support most ASA-only filter semantics (`nameif`, security-level`, etc.).
 
I'll take a look at this.

**Comment by asydney** [comment]
What about this one also? Have you had a moment to look into it?

**Comment by arifogel** [comment]
So I have an ASA setup I've been testing. Due to the different forwarding paradigm ASA uses compared to other device types, there is quite a bit of work involved in modeling this decently. Unfortunately I'm going to have to put this work on hold for now, but I will take a look again in a week or two when I have some more time.

**Comment by jkhourybbn** [comment]
@arifogel @ratulm I assume you decided not to support ASA semantics?

**Comment by arifogel** [comment]
@jkhourybbn While we do eventually plan to support ASAv forwarding semantics, It's not on my queue at the moment.

**Comment by dhalperi** [comment]
@sfraint has been doing a lot of work on firewall semantics. Spencer, any update here in the interim?

**Comment by jkhourybbn** [comment]
@dhalperi this can be closed. There was a problem with how you were inversely parsing the subnet masks for the ASA which was fixed a while back. 

@sfraint we are working the net screen and have questions about juniper SRX support which will send separately
