### ISSUE TITLE
OS/X users with zsh won't be able to do variable expansion on batfish_functions.sh

### ISSUE THREAD

**Issue by gaberger** [batfish/batfish#476]
Expansion on BASH_SOURCE doesn't work when executed from zsh. The fix is to use a bash file such as:

build.sh

```#!/bin/bash
. tools/batfish_functions.sh
$1
```
`sh -x ./build.sh batfish_build_all`

**Comment by ratulm** [comment]
none of us are zsh users. want to send a PR based on what works for you?

One thing I noticed while trying your idea was that tab completion of commands line "batfish_build_all" and "allinone" no longer work. (Perhaps there is a way to get that going too ...)

**Comment by dhalperi** [comment]
As a `zsh` user I am in principle a big fan of fixing our aliases to work across shells.

However, in practice i find myself just running `bash` when I want to run `allinone`.

This would be a nice enhancement, but I think it's low priority right now.

**Comment by dhalperi** [comment]
These shell aliases are deprecated, closing this issue.
