### ISSUE TITLE
Banner preprocessor issue

### ISSUE THREAD

**Issue by eidorb** [batfish/batfish#4845]
BatFish failed to parse a Cisco ASA config file. An exception with "Invalid banner" was raised. I isolated the issue to the following `banner` command:

```
banner exec |
```

I created some other test configs and found the following `banner` commands also cause parsing to fail:

```
banner login =
banner login (
banner login 1
```

But, the following was successful:

```
banner login d
```

I *think* the issue is may be related to the dynamic creation of the delimiter regex pattern, based on the captured delimiter. 

https://github.com/batfish/batfish/blob/291f8740b44401bbefe9b51af0a4752415185bd9/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L80

I was not aware that nested character sets (`[[]]`) were valid regular expressions. However, I do see that they are valid in Java regular expressions in some *very specific* circumstances. Specifically, they are used to create unions and intersections of *letter* ranges. Thus, this is why it is successful with the letter delimiter above (`banner login d`), but not with the non-letter characters.

**Comment by dhalperi** [comment]
@arifogel can you take a look at this?

**Comment by arifogel** [comment]
@eidorb Thanks for the report! I've identified the issue, and will push out a fix soon.

**Comment by eidorb** [comment]
That's one hell of a fix 😄
