### ISSUE TITLE
router igmp parsing error

### ISSUE THREAD

**Issue by agember** [batfish/batfish#4864]
The following Cisco configuration snippet causes an irrecoverable parser failure:
```
!
router igmp
 vrf default
  interface all router disable
 !
!
end
```

**Comment by dhalperi** [comment]
Hey @agember - we have some existing parsing tests with `router igmp` in it. Can you say more about what is unrecoverably bad? Stack trace? Lost parsing afterwards? Something else?

**Comment by dhalperi** [comment]
And for config snippets, we need information about vendor as well -- what OS is this?

**Comment by agember** [comment]
@dhalperi The snippet is Cisco IOS. The parser fails when it encounters the `interface` line. The context at the time is `[s_interface, cisco_configuration]`. 

Looking at the parsing for `router igmp` (https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4#L2185), it seems that there is no parsing support for the `vrf` line. I don't know how the parsing recovery works, but I would hypothesize that the following occurs: the parser tries to recover when it encounters the `vrf` line; recovery returns to the top-level context `cisco_configuration`; the subsequent `interface` line causes the parser to match `s_interface`; the parser does not know what to do with `router disable`, so it fails.

**Comment by dhalperi** [comment]
I still don't understand the actual behavior. If recovery is working, we should ignore that entire `router igmp` block, pop up to next level, and exit with unrecognized lines. That would be expected behavior, is that what's happening?

**Comment by agember** [comment]
I was getting status of `FAILED` instead of `PARTIALLY_UNRECOGNIZED`, but now I cannot reproduce it. I created a pull request to add the snippet to the test suite, to avoid regressions, but I don't think there is any further fixing required.
