### ISSUE TITLE
Unimplemented BDP feature (NamesAsPathSet?)

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#49]
Status: FAILURE
Question: null
{
  "class" : "org.batfish.common.BatfishException$BatfishStackTrace",
  "contents" : [
    "org.batfish.common.BatfishException: Batfish job failed",
    "   at org.batfish.main.Driver$1.run(Driver.java:302)",
    "Caused by: org.batfish.common.BatfishException: unimplemented",
    "   at org.batfish.datamodel.routing_policy.expr.NamedAsPathSet.matches(NamedAsPathSet.java:31)",
    "   at org.batfish.datamodel.routing_policy.expr.MatchAsPath.evaluate(MatchAsPath.java:27)",
    "   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:35)",
    "   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:38)",
    "   at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:78)",
    "   at org.batfish.bdp.Node.propagateBgpRoutes(Node.java:801)",
    "   at org.batfish.bdp.BdpDataPlanePlugin.lambda$computeFixedPoint$15(BdpDataPlanePlugin.java:369)",
    "   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)",
    "   at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2893)",
    "   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)",
    "   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)",
    "   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)",
    "   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)",
    "   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)",
    "   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)",
    "   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)"
  ]
}

**Comment by arifogel** [comment]
Please create topic branch with failing unit test. Then create pull request for topic branch. I will fix, merge, then delete the topic branch.

**Comment by ratulm** [comment]
check email

**Comment by arifogel** [comment]
Implemented in df8d2529b5a4a9f04bb9e69bccd9bde169ca4c67
