### ISSUE TITLE
Indicate which lines in a config are causing parsing to fail

### ISSUE THREAD

**Issue by jlmcgraw** [batfish/batfish#502]
Attempting to parse some real-world config files caused batfish to fail.  I had to remove lines one by one to determine which commands were unsupported by the grammar.

Is there a better way to have batfish express what is causing it to fail?

Is it possible to have batfish continue on, ignoring unsupported keywords?

**Comment by ratulm** [comment]
The following command should tell you whats happenings with the parsing failures:
   batfish> get initinfo verboseError=True

We try to ignore unsupported stuff as much as we can. It gets tricky sometimes, e.g., when the top-level thing is something that we know of, but is followed by something that we don't. The parser (Antlr4) never seems to recover gracefully from those situations, and we haven't been able to hack that. If you are an Antlr4 wizard, we'd love help.
