### ISSUE TITLE
Feature request: create linked versions of config

### ISSUE THREAD

**Issue by jlmcgraw** [batfish/batfish#503]
I have written a very brute-force and simpleminded tool to link together items within a configuration as well as between configurations (https://github.com/jlmcgraw/network_configuration_navigator) and create HTML versions that allow you to more easily follow the logic and definitions ( as well as discover things that are defined but not used)

(see here for example outputs: http://htmlpreview.github.io/?https://github.com/jlmcgraw/network_configuration_navigator/blob/master/examples/html_test_case_1.cfg.html)

Since batfish is doing a much more intelligent parsing of configurations than my tool, it seems like this sort of linking could easily shake out of the analysis it is already doing.

Would you consider adding this sort of functionality, basically like a simple IDE and simple linter for network device configurations, to batfish?

**Comment by ratulm** [comment]
@jlmcgraw - Your tool is cool! Loved it when I saw it originally. 

A few Intentionet engineers are working on displaying the analysis of Batfish visually, which will include some of what you are imagining. I am sure they'd love to run it by you when they have something demonstrable.

**Comment by ratulm** [comment]
Closing for now. Please re-open if you'd like to discuss further.
