### ISSUE TITLE
testRoutePolicies question probably has a bug.

### ISSUE THREAD

**Issue by ohlisa55** [batfish/batfish#5048]
Hello,

I'm trying to use testRoutePolicies question but it probably has a bug.

Here is my code on the jupyter notebook.
```
#read questions
%run startup.py
load_questions()

#read snapshots
NETWORK_NAME = "example_network"
SNAPSHOT_NAME = "example_snapshot"
SNAPSHOT_PATH = "networks/example"
bf_set_network(NETWORK_NAME)
bf_init_snapshot(SNAPSHOT_PATH, name=SNAPSHOT_NAME, overwrite=True)

#doing question
routes_all = bfq.testRoutePolicies(nodes="as3border1", policies="as1_to_as3", inputRoutes(network="0.0.0.0/0"), direction="in")
```

Here is a error message.
```
SyntaxError: positional argument follows keyword argument
```
I'm following the pybatfish document to give inputRoutes's argument parameter so these orders are  supposed to be correct but it's getting this error message.
The pybatfish document says here.

```
class pybatfish.question.bfq.testRoutePolicies(*.nodes, policies, inputRoutes, direction, question_name)
```

How can I fix it?

Thanks.

**Comment by dhalperi** [comment]
Thanks @progwriter. @ohlisa55 , please comment if you have further questions!
