### ISSUE TITLE
Arista: "fallback" keyword for replace-as

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#506]
Need to add parser support for the following BGP config stanza for Arista EOS:

neighbor <x> local-as <y> no-prepend replace-as
neighbor <x> local-as <y> no-prepend replace-as fallback

**Comment by dhalperi** [comment]
[template message] Now that we have parser recovery, I'm closing a bunch of older "this doesn't parse" bugs. I'm assuming that filers will ping those that are important to them.
