### ISSUE TITLE
Arista: bgp additional paths parser support

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#508]
Arista EOS configuration for BGP Add-paths is different then Cisco. 

It can be enabled globally for ALL peers via the following commands:

bgp additional-paths install <== install multiple BGP paths in BGP RIB and routing table
bgp additional-paths receive <== accept multiple BGP paths from neighbors. This is on by default
bgp additional-paths send any <== send ALL multiple paths to ALL neighbors

Additionally, the add-paths receive and send commands can be enabled per BGP peer.

**Comment by dhalperi** [comment]
[template message] Now that we have parser recovery, I'm closing a bunch of older "this doesn't parse" bugs. I'm assuming that filers will ping those that are important to them.
