### ISSUE TITLE
report a smt-reachability bug with only static route

### ISSUE THREAD

**Issue by YuhuWang2002** [batfish/batfish#512]
I create sample config as below:
[node2.txt](https://github.com/batfish/batfish/files/1361514/node2.txt)
[node1.txt](https://github.com/batfish/batfish/files/1361512/node1.txt)
[node3.txt](https://github.com/batfish/batfish/files/1361516/node3.txt)
[host3.txt](https://github.com/batfish/batfish/files/1361517/host3.txt)
[host1.txt](https://github.com/batfish/batfish/files/1361518/host1.txt)
Topology:
![topology](https://user-images.githubusercontent.com/21324650/31263008-d3f1403e-aa91-11e7-9136-3e21280f88b5.png)

I met some bugs:
1 : private static Ip ipVal(Model m, Expr e) {
   return new Ip(intVal(m,e));
   }
overfolw,
I change to: return new Ip(Long.parseLong(evaluate(m, e)));
2: static route lost by create Graph, I think it is a bug:
in graph.java line 225
`             if (isNextHop) {

                someIface = true;

                List<StaticRoute> srs = map.getOrDefault(hereName, new ArrayList<>());

                srs.add(sr);

                map.put(there.getName(), srs);

              }`
  I think it is      `map.put(hereName, srs);`
if it is not a bug, I cann't understand why put "there.getName"

base on fix these bugs, it is still have some strange phenomenon : 
My intention is to check "is the host1 can reach to host3?"
1, I run the command as below, it is work
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="host3",dstIps=["192.168.8.0/24"]
Status: SUCCESS
Question: reachability actions=[ACCEPT] | dstIps=[192.168.8.0/24]

Flow: ingress:host1 vrf:default 0.0.0.0->192.168.8.0 HOPOPT packetLength:0 state:NEW
  environment:BASE
    Hop 1: host1:eth0 -> R1:Ethernet0/0 --- [StaticRoute<192.168.8.0/0,nhip:192.168.1.2/24,nhint:dynamic>]
    Hop 2: R1:Ethernet0/1 -> R2:Ethernet0/0 --- [StaticRoute<192.168.8.0/24,nhip:10.10.10.1/24,nhint:dynamic>]
    Hop 3: R2:Ethernet0/1 -> R3:Ethernet0/0 --- [StaticRoute<192.168.8.0/24,nhip:10.10.11.1/24,nhint:dynamic>]
    Hop 4: R3:Ethernet0/1 -> host3:eth0 --- [ConnectedRoute<192.168.8.0/24,nhip:AUTO/NONE(-1l),nhint:Ethernet0/1>]
    ACCEPTED
Summary: 0 (non-assertion) results; 

2 
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="host3"
Status: SUCCESS
Question: reachability actions=[ACCEPT]

Flow: ingress:host1 vrf:default 0.0.0.0->10.10.11.0 HOPOPT packetLength:0 state:NEW
  environment:BASE
    Hop 1: host1:eth0 -> R1:Ethernet0/0 --- [StaticRoute<10.10.11.0/0,nhip:192.168.1.2/24,nhint:dynamic>]
    Hop 2: R1:Ethernet0/1 -> R2:Ethernet0/0 --- [StaticRoute<10.10.11.0/24,nhip:10.10.10.1/24,nhint:dynamic>]
    NO_ROUTE
cann't work
3 
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="R3",dstIps=["192.168.8.0/24"]
Status: SUCCESS
Question: reachability actions=[ACCEPT] | dstIps=[192.168.8.0/24]

Verified
I debug this ,below these code:
  ` public static AnswerElement computeReachability(IBatfish batfish, HeaderLocationQuestion q) {`

    PathRegexes p = new PathRegexes(q);
    Graph graph = new Graph(batfish);
    Set<GraphEdge> destPorts = findFinalInterfaces(graph, p);
    List<String> sourceRouters = PatternUtils.findMatchingSourceNodes(graph, p);
    inferDestinationHeaderSpace(graph, destPorts, q);

    Encoder enc = new Encoder(graph, q);
    enc.computeEncoding();`

 I find the "finalNodeRegex="host3"" make the var: destPorts is empty, if destPorts is empty,and we add the dstips constraints, the z3 will get satisfiable.
but finalNodeRegex="R3", make the var destPorts is not empty, actually it also make the dstips not empty, seem like "finalNodeRegex="host3",dstIps=["192.168.8.0/24"]", but the z3 get unsat. I do not know why?

**Comment by YuhuWang2002** [comment]
@rabeckett @ratulm

**Comment by rabeckett** [comment]
Thanks for the detailed example and debugging information! This should be fixed in #526. 

To clarify what is happening: the smt-reachability query requires start and end locations (ingressNodeRegex, finalNodeRegex, finalIfaceRegex) as well as packet header constraints (e.g., dstIps) as inputs. If you  don't provide any constraint on the destination IP, then it will try to infer reasonable values from looking at the final nodes / interfaces for the query.

Some example queries for this network:

**Check reachability to 192.168.8.2 -- should succeed**
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="host3",dstIps=["192.168.8.2"]

**Check reachability to 192.168.8.1 -- should fail since R3 has an interface with this address**
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="host3",dstIps=["192.168.8.1"]

**Check reachability to host3 -- should succeed**
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="host3"

In the last example, it will infer that it should check any packet with destination IP in the range 192.168.8.0/24 except not for 192.168.8.1

**Comment by YuhuWang2002** [comment]
@rabeckett 
Thanks for your response
To review your code, I realize print the "Verified" means can reach, and print the route tracker is can't reach.
I think it's behavior is inconsistent with "get reachability ingressNodeRegex="host1",finalNodeRegex="host3",dstIps=["192.168.8.3"]", it makes users are confused.
especially print "
get smt-reachability ingressNodeRegex="host1",finalNodeRegex="R3",dstIps=["192.168.8.2"]
Status: SUCCESS
Question: smt-reachability actions=[ACCEPT], dstIps=[192.168.8.2], finalNodeRegex=R3, ingressNodeRegex=host1

Flow: ingress:host1 vrf:default 0.0.0.0->192.168.8.2 HOPOPT packetLength:0 state:NEW
  environment:BASE
Environment{envName=BASE, testrigName=tr_5881a91d-b151-4284-8e73-79371c7059bd, edgeBlacklist=null, interfaceBlacklist=null, nodeBlacklist=null, bgpTables=null, routingTables=null, externalBgpAnnouncements=null}
    Hop 1: host1:eth0 -> R1:Ethernet0/0 --- [StaticRoute<0.0.0.0/0,nhip:192.168.1.2,nhint:dynamic>]
    Hop 2: R1:Ethernet0/1 -> R2:Ethernet0/0 --- [StaticRoute<192.168.8.0/24,nhip:10.10.10.1,nhint:dynamic>]
    Hop 3: R2:Ethernet0/1 -> R3:Ethernet0/0 --- [StaticRoute<192.168.8.0/24,nhip:10.10.11.1,nhint:dynamic>]
    Hop 4: R3:Ethernet0/1 -> host3:eth0 --- [ConnectedRoute<192.168.8.0/24,nhip:AUTO/NONE(-1l),nhint:Ethernet0/1>]
    ACCEPTED"

And I have other question:
To read your code:

`  
BoolExpr allReach = enc.mkTrue();

      for (String router : sourceRouters) {

        BoolExpr r = reach.get(router);

        allReach = enc.mkAnd(allReach, r);

      }
      enc.add(enc.mkNot(allReach));
`
the z3 code is: `(assert (not (and true |0__reachable_host1|)))`

I think it means "never reach to host1", it make me confused, why not "(assert (not (and true |0__reachable_host3|)))`"
if z3 cann't find answer(satisfiable) with "never reach to host3", that means "can reach to host3". so we print "Verified", it's more makes sense

Looking forward to your response :)
