### ISSUE TITLE
Cannot take snapshot of Cisco ASA interface config

### ISSUE THREAD

**Issue by mahoutukaisali** [batfish/batfish#5159]
Hi,

There are two types of configuration formats for the Cisco ASA interface. One succeeds in taking a snapshot, but the other fails. Here are configurations below.
※These config's IP address and mac address are masked to upload here

The succeed pattern
```
interface GigabitEthernet0/0
 nameif inside
 security-level 100
 ip address X.X.X.X 255.255.255.0
!
interface GigabitEthernet0/1
 nameif outside
 security-level 0
 ip address X.X.X.X 255.255.255.0
```

The fail pattern
```
interface inside
 mac-address X.X.X standby X.X.X
 nameif inside
 security-level 100
 ip address X.X.X.X 255.255.255.0 standby X.X.X.X 
!
interface mgmt
 mac-address X.X.X standby X.X.X
 nameif mgmt
 security-level 100
 ip address X.X.X.X 255.255.255.0 standby X.X.X.X
```

But when I delete the fail pattern interface configuration it succeed to take snapshot. 
But it cannot to test any testcases without interface configuration though. 

I think because the fail pattern configuration is unique type of configuration for Cisco ASA  so Batfish cannot read this pattern.

Do you know why it's failing?

Thanks,

**Comment by dhalperi** [comment]
Hi @mahoutukaisali - thanks! I will take a look at this tomorrow, I suspect the fix is *very* easy and we'll have a test container for you then.

**Comment by dhalperi** [comment]
@mahoutukaisali - in the fail pattern, can you please confirm that the first line of each interface is `interface inside` / `inside mgmt`? Not, say, `interface GigabitEthernet0/2`?

Confirming since I know you've edited these snippets manually...

**Comment by dhalperi** [comment]
If those snippets are correct, then yes I can see why Batfish does not yet handle them. I'm unable to find any documentation or example configs, yet, however.

**Comment by dhalperi** [comment]
Are you using HA Contexts?
 https://www.cisco.com/c/en/us/td/docs/security/asa/asa91/configuration/general/asa_91_general_config/ha_contexts.html#83745

If so, can you post (anonymized) versions of the entire interface config, including the physical interfaces, the contexts and allocations?

**Comment by mahoutukaisali** [comment]
What does mean HA Contexts?

**Comment by mahoutukaisali** [comment]
I understand HA Context means and yes it using HA Context.
The entire version is 
Hardware: ASA5585-SSP-40
ASA Version 9.6(2) <context>

**Comment by dhalperi** [comment]
Thanks for following up @mahoutukaisali . This is not quite as straightforward as I hoped, but will work on it.

**Comment by fatred** [comment]
I too have the problem with a Multi-context ASA not getting parsed. Happy to provide contrived configs from a test unit if you can let me know what config things you want to see in it?

**Comment by mahoutukaisali** [comment]
Batfish has adapted to ASA in the newest version so I closed this issue. Thanks.

**Comment by alphachris** [comment]
> Batfish has adapted to ASA in the newest version so I closed this issue. Thanks.

I cannot confirm this. I'm running the latest container version, yet I'm still having issues getting my ASA multi-context configs interpreted. When I'm changing the interface name from a logical name (e.g. "inside") to a physical one (e.g. GigabitEthernet0/0) while leaving the "nameif" and "description" inside the interface config, the configuration gets parsed accordingly. If it's needed I can upload an example config.

**Comment by dhalperi** [comment]
Thanks, @alphachris! Please file a new issue with config and we'll take a look.
