### ISSUE TITLE
Feature: implement configurable BDP debugging

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#520]
In addition to changes from #516 we should add command-line configurability to BDP debugging.
That is, the following constants should be changed to `DEFAULT_XXX`, and the runtime values should be configurable from the command line:
- `DEBUG_ALL_ITERATIONS`
- `DEBUG_MAX_RECORDED_ITERATIONS`
- `DEBUG_REPEAT_ITERATIONS`

**Comment by dhalperi** [comment]
Is this done now?

**Comment by arifogel** [comment]
Implemented in #523
