### ISSUE TITLE
bf_assert / assert_no_undefined_references fails on Cumulus L3 VPN (type-5) VxLAN VNI interfaces

### ISSUE THREAD

**Issue by petercrocker** [batfish/batfish#5306]
Finally making some time to test, playing around with your ansible playbooks,and you've got an example in the readme for Confirm there are no undefined references or incompatible BGP sessions
So seems it's complaining on my cumulus vxlan setup, what's the best way to dig in to this?

`TASK [Confirm there are no undefined references or incompatible BGP sessions] *******************************************
Wednesday 18 December 2019  17:03:18 +0000 (0:00:04.923)       0:00:12.031 ****
fatal: [localhost]: FAILED! => {"changed": false, "msg": "1 of 2 assertions failed", "result": [{"details": "Found undefined reference(s), when none were expected\n[{'File_Name': 'configs/exit01.cfg', 'Struct_Type': 'abstract interface', 'Ref_Name': 'vxlan4001', 'Context': 'bridge ports', 'Lines': FileLines(filename='configs/exit01.cfg', lines=[87])}, {'File_Name': 'configs/exit02.cfg', 'Struct_Type': 'abstract interface', 'Ref_Name': 'vxlan4001', 'Context': 'bridge ports', 'Lines': FileLines(filename='configs/exit02.cfg', lines=[86])}, {'File_Name': 'configs/leaf01.cfg', 'Struct_Type': 'abstract interface', 'Ref_Name': 'vxlan4001', 'Context': 'bridge ports', 'Lines': FileLines(filename='configs/leaf01.cfg', lines=[98])}, {'File_Name': 'configs/leaf02.cfg', 'Struct_Type': 'abstract interface', 'Ref_Name': 'vxlan4001', 'Context': 'bridge ports', 'Lines': FileLines(filename='configs/leaf02.cfg', lines=[98])}, {'File_Name': 'configs/leaf03.cfg', 'Struct_Type': 'abstract interface', 'Ref_Name': 'vxlan4001', 'Context': 'bridge ports', 'Lines': FileLines(filename='configs/leaf03.cfg', lines=[98])}, {'File_Name': 'configs/leaf04.cfg', 'Struct_Type': 'abstract interface', 'Ref_Name': 'vxlan4001', 'Context': 'bridge ports', 'Lines': FileLines(filename='configs/leaf04.cfg', lines=[98])}]", "name": "Confirm we have no undefined references", "status": "Fail", "type": "assert_no_undefined_references"}, {"details": "Assertion passed", "name": "Confirm we have no incompatible BGP sessions", "status": "Pass", "type": "assert_no_incompatible_bgp_sessions"}], "summary": "1 of 2 assertions failed"}`

Cumulus in Vagrant repo, but you can just get the batfish processed configs from here:
https://gitlab.com/petercrocker/cumulus-generic-setup/tree/batfish/automation/batfish

**Comment by ratulm** [comment]
Fixed in #5347 (or perhaps earlier). After that PR, Batfish shows no undefined references.
