### ISSUE TITLE
Arista - Invalid ACL syntax accepted

### ISSUE THREAD

**Issue by DamianZaremba** [batfish/batfish#5389]
I have some flow tests setup to run under CI and noticed a broken changed made it through.

It appears that Batfish accepts the following ACL syntax;
`permit <protocol> <ip> <ip> eq <port>`
`permit <protocol> <ip> host <ip> eq <port>`
`permit <protocol> host <ip> <ip> eq <port>`

This can be seen with the below example logic;
```
    bf_session.host = "localhost"
    bf_session.init_snapshot_from_text('ip access-list test\npermit tcp 127.0.0.1 host 127.0.0.2 eq 80',
                                       platform='arista',
                                       overwrite=True)
    load_questions()
    answer = bfq.testFilters(headers=HeaderConstraints(srcIps="127.0.0.1",
                                                       dstIps="127.0.0.2",
                                                       ipProtocols=["TCP"],
                                                       dstPorts=["80"]), filters="test").answer()
    print(answer)
```

The output of which is;
```
     Node Filter_Name                                               Flow  Action                               Line_Content                                              Trace
0  config        test  start=config [127.0.0.1:49152->127.0.0.2:80 TC...  PERMIT  permit tcp 127.0.0.1 host 127.0.0.2 eq 80  Flow permitted by extended ipv4 access-list na...
```

Unfortunately this isn't valid ACL syntax on Arista;
```lab01(config-s-sess-1)#ip access-list test
lab01(config-s-sess-1-acl-test)#permit tcp 127.0.0.1 host 127.0.0.2 eq 80
% Invalid input
```

The correct syntax being;
```
lab01(config-s-sess-1-acl-test)#permit tcp host 127.0.0.1 host 127.0.0.2 eq 80
lab01(config-s-sess-1-acl-test)#
```

Which is the syntax present in their documentation https://www.arista.com/en/um-eos/eos-section-24-7-acl-route-map-and-prefix-list-commands#ww1150997.

I'm guessing this is supported syntax on Cisco boxes, so needs a special case for Arista's.

**Comment by dhalperi** [comment]
@DamianZaremba - you hit the nail on the head. We are moving towards more precise parsing for different vendors, from an early "combined cisco parser". E.g., you'll see in the next release that we have completely rewritten the BGP stack for Arista.

We'll be able fix this soonish, but not immediately - migration without regressions takes time. Sorry for the pain.
