### ISSUE TITLE
PaloAlto BGP routes are not being forwarded with PA device as next hop

### ISSUE THREAD

**Issue by skeiffer** [batfish/batfish#5396]
Hello,

We heavily use BGP on our PA devices to force traffic going to different VRFs to pass through the FW for processing. When attempting to use batfish on our network's configuration, no routes are received on other devices from the PA device.

Based on the parsing warnings found when running it appears as if these key lines are not being taken into account:

```
set network virtual-router <vr_name> protocol bgp peer-group <pg_name> type ebgp remove-private-as yes
set network virtual-router <vr_name> protocol bgp peer-group <pg_name> type ebgp import-nexthop original
set network virtual-router <vr_name> protocol bgp peer-group <pg_name> type ebgp export-nexthop use-self
```
I suspect that since these lines are not being interpreted that the routes learned are not being sent  with the PA device as the next hop to other peers.

**Comment by dhalperi** [comment]
Hey @skeiffer - great! These should be fairly easy to fix, and you are right that we are currently ignoring them. You're the first to ask ;)

**Comment by skeiffer** [comment]
@dhalperi Hope all is well. Any update to this? I would really like to give batfish another try. :)

**Comment by dhalperi** [comment]
I think this should be fixed for a while now. We have multiple internally validated labs for BGP and several customers use it.

**Comment by dhalperi** [comment]
If your version of PAN has different behavior, there may still be problems. Please let us know.
