### ISSUE TITLE
F5-BIGIP parser expects "/" for Common keyword otherwise parsing fails. 

### ISSUE THREAD

**Issue by oneryalcin** [batfish/batfish#5487]
Hi Batfish team,

For some reason BIGIP configs I have, do not have lines `/Common/{something}` but `Common/{something}`, missing `/`  before `Common`. 

Batfish questions like `ipOwners()` or `routes()` failed to output any result (or no prefixes in `interfaceProperties()`) when that `/` is missing. I'm not entirely sure if the parser should handle cases without `/` or as Batfish users we need to ensure configs always have the forward slash.   

Below is the minimum working config for reproducing the issue. For testing please just remove the `/` before `Common`.
 
```
#TMSH-VERSION: 12.1.4

net vlan /Common/VLAN_100 {
    tag 100
}
net self /Common/example_self_interface {
    address 1.1.1.1/30
    vlan /Common/VLAN_100
}
sys global-settings {
    hostname example_f5_hostname
}
```

Thanks

**Comment by ratulm** [comment]
Cc: @arifogel

**Comment by arifogel** [comment]
I am unable to produce configs with `Common/...` instead of `/Common/..,` with BIG-IP version 12:
via tmsh:
```
root@(ADC-001a)(cfg-sync Standalone)(Active)(/Common)(tmos)# create net self Common/someself { address 9.9.9.9/30 vlan /Common/VLAN_100 }
01070734:3: Configuration error: Can't associate self IP (/Common/Common/someself) folder does not exist
```
From BIG-IP shell:
```
[root@ADC-001a:Active:Standalone] config # grep -A5 '^net self' bigip_base.conf | head -n7
net self /Common/192.168.123.13/32 {
    address 192.168.123.13/32
    allow-service {
        default
    }
    traffic-group /Common/traffic-group-local-only
--
```
Note the leading slash in the configuration.

How are you extracting configuration? Is your tool accidentally throwing away the leading `/`?

**Comment by oneryalcin** [comment]
Hi @arifogel 

Thanks for looking into this issue. Unfortunately I'm also not allowed to get configs directly from the box, but what I see is that `list recursive` command was run to get all BIG-IP configs. However `/` in front of `Common` seems to be missing in `list recursive` output.

**Comment by ratulm** [comment]
hey, @oneryalcin - it wouldn't be prudent for Batfish to support this syntax unless it were valid. can you help double-check if (and with what versions/commands) an F5 device produces '/'-less names? e.g., do you have a lab device similar to the one in prod that you can play with?  thanks.

**Comment by oneryalcin** [comment]
hey @ratulm. I tried to trace why we fail to get `/` before `Common`. After talking to few engineers, I understand that we don't get the configs  directly from the device, but running `list recursive` to get the  output. Thus it returns `Common` instead of `/Common`

I believe you can close this issue.

**Comment by ratulm** [comment]
hey, @oneryalcin - ok, thanks for confirming. 

do you have a workaround (e.g., getting configs in a different manner or patching the file using sed)?

**Comment by oneryalcin** [comment]
Yes, once I got the configs, I replace all instances of `Config` with '/Config'. We have an internal library (wrapper around batfish) and it is handled in a submodule there.
