### ISSUE TITLE
MPLS-L3VPN Traceroutes

### ISSUE THREAD

**Issue by markusju** [batfish/batfish#5565]
Hi,

I have been playing around with batfish and so far pretty much everything just worked out of the box. :D

Unfortunately, I do have a problem running traces inside of a VRF. While interfaces and networks associated with a VRF on different routers are correctly recognized, batfish does not seem to be able to calculate the forwarding path of a trace inside a MPLS-L3VPN (VRF) correctly.

I would expect batfish to recognize the target route on the distant PE router, find its loopback address and calculate the path and mpls label stack accordingly.

I could not find an information on this in the documentation and was wondering if this is supported at all.  Traceroutes inside the master/default instance work perfectly well.

Any help on this would be much appreciated.

Cheers,

Markus

**Comment by dhalperi** [comment]
Hey @markusju - unfortunately Batfish does not have MPLS support right now. L3VPN is on the roadmap, but not near-term.

I am glad to hear the rest of the functionality worked pretty well out of the box. Please jump on Batfish slack if you have questions about how you can use Batfish without MPLS-L3VPN support yet.

Thanks,
Dan

**Comment by markusju** [comment]
Hi @dhalperi. Thanks for your response.

I am rooting for MPLS support. ;) So far this seems like a really powerful tool already and I am looking forward to see more features being implemented in the future.

Keep up the good work!
