### ISSUE TITLE
Palo Alto aggregate interface parsing issue

### ISSUE THREAD

**Issue by oneryalcin** [batfish/batfish#5598]
Hi Batfish team, 

We have few palo alto devices and I noticed that batfish is able to parse interface IP addresses (hence successfully building `bfq.layer3Edges().answer().frame()` )  when the interface is not an aggregate interface, but it fails to parse when the interfaces is defined as an aggregate interface.
Therefore ip addresses under aggregate-ethernet interfaces doesn't show up in `l3Edges()`  

A very minimal example is given below:

- Parsing `ethernet1/3` is successful
- Parsing  `aggregate-ethernet ae1` is failing

```
devices {
  localhost.localdomain {
    network {
      interface {
        ethernet {
          ethernet1/3 {
            layer3 {
              ip {
                10.0.0.1/29;
              }
            }
          }
          ethernet1/21 {
            aggregate-group ae1;
            link-state auto;
            link-duplex auto;
            link-speed auto;
          }
          ethernet1/22 {
            aggregate-group ae1;
            link-state auto;
            link-duplex auto;
            link-speed auto;
          }
          aggregate-ethernet {
            ae1 {
              layer3 {
                units {
                  ae1.290 {
                    tag 290;
                    ip {
                      10.0.1.1/29;
                    }
                  }
                  ae1.200 {
                    tag 200;
                    ip {
                      10.0.2.1/29;
                    }
                  }
                  ae1.201 {
                    ip {
                      10.0.3.1/29;
                    }
                    tag 201;
                  }
                }
              }
              comment "Aggregate interface to "Core Router";
            }
          }
        }
      }
    }
  }
}
```

**Comment by dhalperi** [comment]
Thanks @oneryalcin - we'll take a look.

**Comment by dhalperi** [comment]
Hi @oneryalcin - Did you edit these configs or are they direct off the box? A few followups:

* In this config, `aggregate-ethernet` is inside of `network > interface > ethernet` ; on my box it's just under `network > interface`. Can you confirm?
* Is the comment at the end edited, or does it actually show up with three `"`?

Thanks.

**Comment by oneryalcin** [comment]
First of all thanks for your quick response @dhalperi, and secondly apologies. You are right, the config was quite long so I just wanted to get the relevant sections. Indeed the `aggreagate-ethernet` is inside of `network > interface`. I can confirm that. 

And the comment at the end edited, so in the original config there are no three double quotes. My bad.

Please see below the excerpt from the original config:
![Screenshot 2020-03-04 at 11 25 00 AM](https://user-images.githubusercontent.com/8620952/75875082-e998a380-5e0a-11ea-845f-6e18723bb8e2.png)

**Comment by oneryalcin** [comment]
Hi @dhalperi ,  is this `aggregate-ethernet` issue something you were able to reproduce in your environment?

**Comment by dhalperi** [comment]
Hi @oneryalcin - yes, and will be working on this issue again this week.

**Comment by oneryalcin** [comment]
Hi @dhalperi , I'm aware the situation with Covid19 is impacting your workflow and I appreciate you are having a look at it, do you have any rough timeline to check this particular issue? Thanks

**Comment by dhalperi** [comment]
@oneryalcin: surfacing from the depths again - long project just wrapping up.

I almost have this working, but I wanted to check one thing.

Of the interfaces in your mock example, what VRs are they assigned to (or not assigned to)?

**Comment by dhalperi** [comment]
Hi @oneryalcin - give batfish `test-463` a try when you get a chance, let us know :)
