### ISSUE TITLE
runing the original verison of java code

### ISSUE THREAD

**Issue by yangzhewen** [batfish/batfish#5683]
Hi there, I am a student learning network, and I have read your nsdi paper and i am trying to understand your first version of code which is batfish-nsdi15-submitted-for-review. I have built the environment but I don't know how to run the examples you gave, (by the way I am trying to run it on eclipes). I noticed that the driver requests args, but I don't know what I should feed in to the project. Wish you can give me some hits. Thanks a lot!

**Comment by dhalperi** [comment]
@arifogel @ratulm anything useful to provide here?

**Comment by ratulm** [comment]
@yangzhewen - running the original version of the code requires that version of the logicblox code (and an academic license for it). do you have that? 

BTW, why do you want to run the original code?

**Comment by yangzhewen** [comment]
> @yangzhewen - running the original version of the code requires that version of the logicblox code (and an academic license for it). do you have that?
> 
> BTW, why do you want to run the original code?

Yeah, I have got the logicblox's academic license and have run the example with your shell code on my linux machine however I can't run it completely, here is the bug: 
*** GENERATING Z3 CONCRETIZER QUERIES ***
Reading z3 datalog query output file: "/home/parallels/Desktop/ParallelsSharedFolders/Home/Downloads/z3-z3-4.5.0/build/example-query/example-query/multipath-inconsistency-query-as1border1.smt2.out"..OK
Parsing: "/home/parallels/Desktop/ParallelsSharedFolders/Home/Downloads/z3-z3-4.5.0/build/example-query/example-query/multipath-inconsistency-query-as1border1.smt2.out"..1 ERROR(S)
ERROR 1: parser: DatalogQueryResultParser: line 1:0: no viable alternative at input '<EOF>'
ERROR 1: Offending Token:  line 1:0  EOF:<EOF>  <== mode:DEFAULT_MODE
ERROR 1: Error parsing top (leftmost) parser rule in stack: '[result]'.
ERROR 1: Unconsumed tokens:
ERROR 1:  line 1:0  EOF:<EOF>  <== mode:DEFAULT_MODE
ERROR 1: Lexer mode at EOF: DEFAULT_MODE

batfish.main.BatfishException: Exiting due to parser errors
	at batfish.main.Batfish.parse(Batfish.java:1087)
	at batfish.main.Batfish.parse(Batfish.java:1102)
	at batfish.main.Batfish.concretize(Batfish.java:379)
	at batfish.main.Batfish.run(Batfish.java:1657)
	at batfish.main.Driver.main(Driver.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:342)
	at com.simontuffs.onejar.Boot.main(Boot.java:168)
parallel: This job failed:
batfish_generate_multipath_inconsistency_concretizer_queries_helper as1border1 /home/parallels/Desktop/ParallelsSharedFolders/Home/Downloads/z3-z3-4.5.0/build/example-query/example-query/multipath-inconsistency-query ;

Can you help me with it? Thanks a lot!
About the reason is that I am learning the computer network configure have just read your nsdi paper and found really interesting and thought that running the original code might be helpful for me to learn more and understand your paper better. Thanks again!

**Comment by ratulm** [comment]
Closing because its stale
