### ISSUE TITLE
Can batfish analyze vendor-independent config data model as input directly?

### ISSUE THREAD

**Issue by tongorz** [batfish/batfish#5716]
Can batfish accept vendor-independent config data model as input instead of config file?
By this way, batfish could support third party network device vendors without wirting the antlr4 parser of config file. Network Engineer can use the vendor-independent config data model and jinja2 template generate config file and load generated config to network device. Rendering config from data model is much easier than parsing data model from config file.

Thanks.

**Comment by ratulm** [comment]
Hey, @tongorz - Batfish does not consume vendor-independent config data model at the moment. The internal model that we map device configs to is vendor-independent, but we haven't standardized it for external use because it evolves rapidly. 

I am curious, however, about your use case and workflow. How were you thinking the VI configs would be generated and maintained by engineers -- by hand or via some other source-of-truth? Is your problem solved if you had a way to map VI configs to one of the vendors supported by Batfish (in addition to mapping them to your vendor which Batfish does not presumably support)? 

Also, which vendor do you want to analyze?

**Comment by tongorz** [comment]
@ratulm Hey, Thanks you for your reply and help. I got it.

Engineer could generated and maintained self-defined VI config on an internally used web app and upload the generated config to the target network device. 
Yes, It can be solved by  map my VI configs to one of vendors supported by Batfish, but it would  be great if I could directly map my VI model or to Batfish VI model.
Batfish does not presumably support that I want to analyze:  Huawei(VRP), H3C(HP Comware), Ruijie(Cisco like). We also maintain Juniper, Cisco IOS and Cisco Nexus device. There all also some config command differnces among different hardware model and software versions of the same vendor,  which may be much diffcult to support by config parser.

**Comment by ratulm** [comment]
I might be wrong, but my sense is that converting a custom VI model to a Batfish VI model is similar amount of work to converting that custom model to, say, (simplified) Cisco IOS. Off-the-shelf tools won't be available for either conversion--you'd have to write it--and the work involved would be similar. 

If Batfish supported OpenConfig, would that help? That is something we've thought about but never did it. If that is helpful to you, we welcome contributions of that nature.

**Comment by tongorz** [comment]
@ratulm  
Yes, it will be a great feature if batfish can support OpenConfig.

Amout of work is similar. I just feel that translating pure unstructured config text is a little more troublesome than converting VI model. For example, different vendors have different way naming interface, which could be a problem if the Cisco IOS config-parser of batfish cannot recongize other vendor's interface naming format. (Tengigabitethernet0/0/1 for ios, 10GE0/0/1 for huawei, xe-0/0/1 for Juniper, X-GigabitEthernet for H3C).

**Comment by ratulm** [comment]
Ok, make sense, and thanks for the input. We'll consider OpenConfig, though in all likelihood, it is not something that we'll be able to get to any time soon.

**Comment by dhalperi** [comment]
Is there a standarized version of OpenConfig that has won yet? Every time I look, the answer is clearly no.

That is, is there a single version of OpenConfig that can be used as the sole source of truth for Cisco, Arista, Juniper, PAN, and more devices?

Until that happens, OpenConfig is mostly a dead-end.

**Comment by tongorz** [comment]
@dhalperi  
Hey,  maybe OpenConfig is not a good enough network vendor independent config model and maybe there wont be a good enough network vendor independent config model. But the need of maintaining multi-vendor-network-device environment is alaways.
But it will help if batfish could support any structured vendor-independent config data model as input, not necessarily OpenConfig.
