### ISSUE TITLE
Cisco ASA route parsing

### ISSUE THREAD

**Issue by racsoce** [batfish/batfish#5729]
Some static routes on Cisco ASA are not parsed, in the following example first 3 routes are not parsed:

```
**route management 0.0.0.0 0.0.0.0 10.xxx.xxx.xxx 1
route iad-xxx 0.0.0.0 0.0.0.0 159.xxx.xxx.xxx1
route iad-xxx 10.0.0.0 255.0.0.0 10.xx.0.xx1**
route iad-xxxn 10.xxx.xxx.xxx 255.255.255.224 10.xx.xx.xx1
route iad-xxxn 10.xxx.xxx.0 255.255.254.0 10.xx.xx.xx 1
route iad-xxxn 159.xxx.xxx.0 255.255.255.0 10.xx.xx.x 1
route iad-xxxn 159.xxx.xxx.0 255.255.255.0 10.xx.xx.x 1
route iad-xxxn 159.xxx.xxx.0 255.255.255.128 10.xx.xx.x 1
route iad-xxxn 159.xxx.xxx.224 255.255.255.224 10.xx.xx.x 1
```

batfish routes:
In [127]: result[result.Protocol == 'static']                                                                                                                          
Out[127]: 
              Node      VRF             Network Next_Hop  Next_Hop_IP Next_Hop_Interface Protocol Metric Admin_Distance   Tag
2   iadxxx  default     10.xxx.xxx.xx/27     None  10.xxx.xxx.x  iadxxx   static      0              1  None
7   iadxxx  default    159.xxx.xx.0/24     None  10.xxx.xxx.x  iadxxx   static      0              1  None
9   iadxxx  default    159.xxx.xx.0/24     None  10.xxx.xxx.x  iadxxx   static      0              1  None
13  iadxxx  default  159.xxx.xx.xx/27     None  10.xxx.xxx.x  iadxxx   static      0              1  None
15  iadxxx  default    159.xxx.xx.0/25     None  10.xxx.xxx.x  iadxxx   static      0              1  None
16  iadxxx  default      10.xxx.xx.0/23     None  10.xxx.xxx.x  iadxxx   static      0              1  None

**Comment by dhalperi** [comment]
(For reference: https://www.cisco.com/c/en/us/td/docs/security/asa/asa84/configuration/guide/asa_84_cli_config/route_static.html)

@arifogel - I suspect this is going to be an issue with lexing multiple tokens instead of one, and complicated by ASA-specificity. What's the best way to fix?
