### ISSUE TITLE
Multiple VTY Line Entries Cause Import Failure

### ISSUE THREAD

**Issue by rickdonato** [batfish/batfish#5831]
The following syntax within the configuration causes the config to not be imported.
```
line 0/0/15 0/1/5
 exec-timeout 0 0
 no exec
 transport preferred none
 transport input all
 transport output all
```

Device: `flash:c2900-universalk9-mz.SPA.152-4.M9.bin`.
Sanitized configuration sent to Ratul.

**Comment by dhalperi** [comment]
Thanks for the report, @rickdonato. The fix is in at HEAD and will be in the next release.

To get access via Docker before that, the currently-building version of the `batfish/batfish:test-519` or `batfish/allinone:test-519` containers will also contain the fix.

**Comment by rickdonato** [comment]
Thanks for the rapid response. When is the next release planned for? And the container builds you provided. Will they contain any other development fixes or _only_ `master` + fix.
