### ISSUE TITLE
Eclipse project changes?

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#592]
Is anyone else running into this? When I run 'update maven' on my eclipse project, it looks like the builders are getting reordered. I end up with diffs like this:

```
--- a/projects/batfish/.project
+++ b/projects/batfish/.project
@@ -11,12 +11,12 @@
                        </arguments>
                </buildCommand>
                <buildCommand>
-                       <name>org.eclipse.m2e.core.maven2Builder</name>
+                       <name>org.eclipse.jdt.core.javabuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
                <buildCommand>
-                       <name>org.eclipse.jdt.core.javabuilder</name>
+                       <name>org.eclipse.m2e.core.maven2Builder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
```

**Comment by arifogel** [comment]
Yeah I run into this. I just revert changes to the project files after updating maven / importing projects. It's kind of obnoxious, but I don't know any solution other than this crappy workaround. We need the maven builder to be listed before the java builder (at least for any project with parsers), so we are kinda stuck.

**Comment by virtuald** [comment]
Heh. It works for me without reverting it -- though every time I update a parser, I have to do a refresh/clean cycle.
