### ISSUE TITLE
RuntimeData: support for multi-device config files

### ISSUE THREAD

**Issue by sfraint** [batfish/batfish#5951]
Currently, `RuntimeData` supports a map of interface name to `InterfaceRuntimeData` per configuration file, e.g. the following specifies default speeds for some ethernet interfaces in `config1`:
```
{
    "runtimeData": {
        "config1": {
            "interfaces": {
                "ethernet1/1": {
                    "speed": 200000000
                },
                "ethernet1/2": {},
                "Ethernet1/4": {
                    "speed": 200000000
                }
            }
        },
...
```

However, some vendors support specifying multiple devices in a single configuration (e.g. Palo Alto Panorama configs), and these devices may have overlapping interface names, e.g. two devices have ethernet1/1 configured in the following configuration file:
```
set template T1 config network interface ethernet ethernet1/1 layer3 ip 10.0.1.1/24
set template T2 config network interface ethernet ethernet1/1 layer3 ip 10.0.2.1/24

set template-stack TS1 templates T1
set template-stack TS1 devices 00000001

set template-stack TS2 templates T2
set template-stack TS2 devices 00000002
```
In this case, if same-named interfaces for the two devices have different runtime data, more granularity is needed in this runtime data specification.

cc: @corinaminer

**Comment by dhalperi** [comment]
Help me understand a little bit more? `SnapshotRuntimeData` is keyed at the top level on hostname, not on input filename.

**Comment by sfraint** [comment]
If that's the case, then this (from above) is wrong:
> RuntimeData supports a map of interface name to InterfaceRuntimeData per configuration file

I'll just close this then.

**Comment by corinaminer** [comment]
@dhalperi are you sure `SnapshotRuntimeData` is keyed on hostname? Based on this section of `Batfish.convertConfigurations`, it has the same keys as `vendorConfigurations`:
```
    for (Entry<String, VendorConfiguration> config : vendorConfigurations.entrySet()) {
      VendorConfiguration vc = config.getValue();
      ConvertConfigurationJob job =
          new ConvertConfigurationJob(
              _settings, runtimeData.getRuntimeData(config.getKey()), vc, config.getKey());
      jobs.add(job);
    }
```
And `vendorConfigurations` comes from `_storage.loadVendorConfigurations(snapshot)`, which based on the implementation in `FileBasedStorage` seems to be keyed on filenames.

**Comment by corinaminer** [comment]
The above comment is irrelevant as of batfish/batfish#5953. Now we pass the entire `SnapshotRuntimeData` to `ConvertConfigurationJob` and only look up runtime data within it from inside vendor configurations, where the lookups are keyed on hostname.
