### ISSUE TITLE
bfq.unusedStructures() return false positive on route-map used in BGP template

### ISSUE THREAD

**Issue by dannypetrov** [batfish/batfish#6053]
Hello,

The `TEST` route map used within the following example is reported by `unusedStructures()` 

```bash
route-map TEST permit 10
!
router bgp 12345
   neighbor SOME_NAME peer-group
   neighbor SOME_NAME route-map TEST in
   neighbor SOME_NAME route-map TEST out
!
```

**Comment by dhalperi** [comment]
For this exact text, the only unusedStructure I see is

```
   Structure_Type Structure_Name        Source_Lines
0  bgp peer-group      SOME_NAME  configs/config:[6]
```

which seems correct. I does this reproduce for you?

Maybe there are some mis-handled lines between `router bgp` and `neighbor SOME_NAME route-map TEST in` that are causing Batfish to not even parse those lines.

**Comment by dannypetrov** [comment]
It may as well be the case. I noticed all the route maps used in BGP peer-group templates are reported as unused. Let me have another look & see what's wrong with it. What would you advice me to check?

**Comment by dhalperi** [comment]
There were two issues here.

1. old version of Batfish
2. #6058
