### ISSUE TITLE
bfq.unusedStructures() return false positive on IPv4 ACLs used for multicast config

### ISSUE THREAD

**Issue by dannypetrov** [batfish/batfish#6054]
bfq.unusedStructures() return false positive on the following configurations:

Vendor is Arista. For cisco some configuration will be different, some will be the same.

- case 1

```bash
ip access-list some_acl_1
    10 permit host 239.0.0.1
!
ip pim rp-address 1.1.1.1 access-list some_acl_1
!
```

- case 2

```bash
ip access-list some_acl_2
    10 permit host 239.0.0.1
!
interface Ethernet10
   ip mluticast boundary some_acl_2
!
```

- case 3

```bash
ip access-list some_acl_3
    deny ip any
!
interface Ethernet10
   ip pim neighbor-filter some_acl_3
!
```

**Comment by dhalperi** [comment]
Can we talk about Case 1?

Is that `10 permit host 239.0.0.1` correct? I would have expected something like `10 permit ip any host 239.0.0.1`.

If I use the latter, then I get no unused structures:

```
TEXT="""
ip access-list some_acl_1
    10 permit ip any host 239.0.0.1
!
ip pim rp-address 1.1.1.1 access-list some_acl_1
!
"""
bf.init_snapshot_from_text(TEXT, platform='arista', snapshot_name='case1', overwrite=True)
```

**Comment by dhalperi** [comment]
After following up online, I believe there were some syntax errors in the snippets above, and these are now fixed.
