### ISSUE TITLE
Juniper apply-path regex failing

### ISSUE THREAD

**Issue by craized** [batfish/batfish#6059]
Hi,

The following regex causes my Juniper configs to fail parsing

`            prefix-list snmp-connect {
                apply-path "snmp community <*> clients <*[^/][^0]>";
            }`

Please let me know if you need more information

`                {
                    "Details": "java.lang.IllegalArgumentException: Unhandled input: *[^/][^0]\n\tat org.batfish.representation.juniper.Group
Wildcard.toJavaRegex(GroupWildcard.java:116)\n\tat org.batfish.grammar.flatjuniper.Hierarchy.matchWithJuniperRegex(Hierarchy.java:829)\n\tat
org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree$HierarchyLiteralNode.isMatchedBy(Hierarchy.java:119)\n\tat org.batfish.grammar.flatju
niper.Hierarchy$HierarchyTree$HierarchyWildcardNode.matches(Hierarchy.java:276)\n\tat org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree
.getApplyPathPrefixes(Hierarchy.java:719)\n\tat org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree.getApplyPathPrefixes(Hierarchy.java:7
27)\n\tat org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree.getApplyPathPrefixes(Hierarchy.java:727)\n\tat org.batfish.grammar.flatjuni
per.Hierarchy$HierarchyTree.getApplyPathPrefixes(Hierarchy.java:727)\n\tat org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree.getApplyPa
thPrefixes(Hierarchy.java:727)\n\tat org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree.getApplyPathPrefixes(Hierarchy.java:707)\n\tat org.batfish.grammar.flatjuniper.Hierarchy$HierarchyTree.getApplyPathLines(Hierarchy.java:679)\n\tat org.batfish.grammar.flatjuniper.Hierarchy.getApplyPathLines(Hierarchy.java:802)\n\tat org.batfish.grammar.flatjuniper.ApplyPathApplicator.enterPoplt_apply_path(ApplyPathApplicator.java:73)\n\tat org.batfish.grammar.flatjuniper.FlatJuniperParser$Poplt_apply_pathContext.enterRule(FlatJuniperParser.java:28536)\n\tat org.batfish.grammar.BatfishParseTreeWalker.enterRule(BatfishParseTreeWalker.java:27)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)\n\tat org.batfish.grammar.flatjuniper.PreprocessJuniperExtractor.preprocess(PreprocessJuniperExtractor.java:125)\n\tat org.batfish.grammar.flatjuniper.FlatJuniperControlPlaneExtractor.processParseTree(FlatJuniperControlPlaneExtractor.java:36)\n\tat org.batfish.job.ParseVendorConfigurationJob.parseFile(ParseVendorConfigurationJob.java:358)\n\tat org.batfish.job.ParseVendorConfigurationJob.parse(ParseVendorConfigurationJob.java:431)\n\tat org.batfish.main.Batfish.getOrParse(Batfish.java:2682)\n\tat org.batfish.main.Batfish.lambda$serializeNetworkConfigs$59(Batfish.java:2753)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\n\tat java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)\n\tat java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)\n\tat java.util.stream.AbstractTask.compute(AbstractTask.java:327)\n\tat java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\n",
                    "Line_Text": "apply-path \"snmp community netconanRemoved14 clients <*[^/][^0]>\"",
                    "Nodes": null,
                    "Parser_Context": "[poplt_apply_path po_prefix_list s_policy_options s_common statement set_line_tail set_line flat_juniper_configuration]",
                    "Source_Lines": [
                        {
                            "filename": "configs/nrd1.pao1",
                            "lines": [
                                2565
                            ]
                        }
                    ],
                    "Type": "Parse error"
                },
`

**Comment by saparikh** [comment]
@craized can you give more context on what you are trying to match with that regex? For apply-path/groups, I haven't seem complex regexes in use often - just <*>.

Thanks.

Samir

**Comment by craized** [comment]
Yes, of course.

All of our SNMP communities get a clients list applied that first denies
0/0, then allows valid clients. In order to build the client list for use
later with an apply path, 0.0.0.0/0 must be excluded (hence the regex that
allows anything that does not end in "/0")

community <*> {
    authorization read-only;
    clients {
        0.0.0.0/0 restrict;
        64.x.x.x/24;
    }
}

I'm of course happy to provide any more details if you would like, and
thank you for looking

**Comment by craized** [comment]
@saparikh was the above enough additional explanation? I don't really know what the expected response time on my post should be, but I'm wondering if it got lost since I didn't tag you.

Thanks, happy to continue being patient if it's already on your radar

**Comment by saparikh** [comment]
@craized no worries. it is on our radar, but don't have an ETA on when we can fix it. btw, the `prefix-list snmp-connect` are you using that in firewall-filter or routing policy? 

also, if you can share a more complete config, that makes it easier for us so that we don't have to try to build configs from various snippets. you can anonymize the config with netconan (https://github.com/intentionet/netconan)

**Comment by craized** [comment]
At this time I can't post the entire config, but I hope this is enough to prevent some work on your end. Below is how this prefix-list is both generated and applied

`

set groups std-config-v7 policy-options prefix-list snmp-connect apply-path "snmp community <*> clients <*[^/][^0]>"
set snmp community REDACT authorization read-only
set snmp community REDACT clients 10.100.0.10/32
set snmp community REDACT clients 0.0.0.0/0 restrict

set apply-groups std-config-v7

set firewall family inet filter loopback-input term restrict-snmp-traffic from source-prefix-list snmp-connect
set firewall family inet filter loopback-input term restrict-snmp-traffic from source-prefix-list snmp-connect-client-lists
set firewall family inet filter loopback-input term restrict-snmp-traffic from destination-prefix-list router-ipv4
set firewall family inet filter loopback-input term restrict-snmp-traffic from destination-prefix-list router-ipv4-logical-systems
set firewall family inet filter loopback-input term restrict-snmp-traffic from protocol udp
set firewall family inet filter loopback-input term restrict-snmp-traffic from destination-port 161
set firewall family inet filter loopback-input term restrict-snmp-traffic then count restrict-snmp-traffic
set firewall family inet filter loopback-input term restrict-snmp-traffic then accept
set firewall family inet filter loopback-input term deny-all then count deny-all
set firewall family inet filter loopback-input term deny-all then log
set firewall family inet filter loopback-input term deny-all then syslog
set firewall family inet filter loopback-input term deny-all then discard
`

**Comment by dhalperi** [comment]
@craized - thanks so much!

Dumb question: does this actually work? Note that Juniper documents that you should use `!` instead of `^` for negation inside a character class. https://www.juniper.net/documentation/en_US/junos/topics/topic-map/configuration-groups-usage.html

**Comment by dhalperi** [comment]
Worked for me in a vqfx emulator.

**Comment by craized** [comment]
Definitely not a dumb question, I had to test it myself the first time I came across it (I was not the origin of this config). I hadn't realized that using a "!" instead was supported, or I probably would have skirted this issue with a quick config change.

**Comment by craized** [comment]
Thank you so much for the fix! Most of my configs have this in there, so the adjustment is a great help.

**Comment by dhalperi** [comment]
@craized - will be in the next release, and the next nightly build. I just kicked off build `680` which will contain the fix in a container with tag `test-680` (instead of `:latest`, use `:test-680`).

**Comment by dhalperi** [comment]
(test-680 will probably be ready in about 20 minutes).

**Comment by craized** [comment]
Thanks again. I think my day is full so I will likely test tomorrow morning.

**Comment by craized** [comment]
Verified working for my network
