### ISSUE TITLE
Cisco IOS will redistribute (without `subnets` keyword) shorter prefixes than their class

### ISSUE THREAD

**Issue by brotobia** [batfish/batfish#6066]
When redistributing routes into OSPF with the command `redistribute static` without specifying `subnets`, Batfish will not redistribute routes which should actually be redistributed. In the attached configs, router 0 contains a static route towards `128.0.0.0/2` which should be redistributed into OSPF. However, these routes are missing in Batfish.
[configs.zip](https://github.com/batfish/batfish/files/5051320/configs.zip)

**Comment by dhalperi** [comment]
As far as I can tell, this is correct behavior. 128.0.0.0/2 is not a classful route - it should be 128.0.0.0/16. Without the `subnets` keyword, it will be not be redistributed.

**Comment by dhalperi** [comment]
From Slack, it looks like Cisco IOS will redistribute prefixes that are larger (aka, smaller prefix-length) than their class.
