### ISSUE TITLE
Parser crash when using large local-preference in route-map

### ISSUE THREAD

**Issue by brotobia** [batfish/batfish#6077]
Batfish's parser reports an error, specifically a Java NumberFormatException, when using a route map which sets the local-preference to a large value. An example config is attached where the local-preference is set to 4294967295 in the route map `map1`.
[configs.zip](https://github.com/batfish/batfish/files/5051715/configs.zip)

**Comment by dhalperi** [comment]
Hey @brotobia - thanks for all these reports. Are you on Slack by any chance? If not, please come join and we can chat more interactively.
