### ISSUE TITLE
Implement configurable compatibility with RFCs #1583 and #2383

### ISSUE THREAD

**Issue by progwriter** [batfish/batfish#609]
Address TODO introduced in #595:
Cisco IOS has two modes of computing Inter-area OSPF summaries (see [link][1])
according to two different RFCs. Faithful implementation requires parsing of 
`[no] compatible rfc1583` command in the configs.

[1]: https://www.cisco.com/c/en/us/support/docs/ip/open-shortest-path-first-ospf/7039-1.html#t29

**Comment by dhalperi** [comment]
Fixed by #617
