### ISSUE TITLE
eBGP routes distribution not happened in a CLOS topology network

### ISSUE THREAD

**Issue by laodulaodu** [batfish/batfish#6197]
in a leaf spine topology network,  (2 spine called LC in configuration file, 4 leaf nodes called LA's in configuration file),  it is observed that spine didn't redistribute route of LA's to another LA.

[routing_table_for each_device_in_batfish_via_routing_question.xlsx](https://github.com/batfish/batfish/files/5213828/routing_table_for.each_device_in_batfish_via_routing_question.xlsx)
[LA2.TXT](https://github.com/batfish/batfish/files/5213846/LA2.TXT)
[LA1.txt](https://github.com/batfish/batfish/files/5213848/LA1.txt)
[LA3.txt](https://github.com/batfish/batfish/files/5213850/LA3.txt)
[LA4.txt](https://github.com/batfish/batfish/files/5213851/LA4.txt)
[LC1.txt](https://github.com/batfish/batfish/files/5213853/LC1.txt)
[LC2.txt](https://github.com/batfish/batfish/files/5213855/LC2.txt)

Since they are cisco IOS configuration files, may be firstly check them out by take them in and see the outcome. 
Thanks a lot

**Comment by ratulm** [comment]
Slack thread: https://batfish-org.slack.com/archives/C8XKQNHAQ/p1599714602097900

**Comment by ratulm** [comment]
After fixing an issue with interfaces not being recognized because of an unsupported name, I see that the spine routers are sending BGP advertisements from LA{1,2} to LA{3.4}, but those are being rejected by LA{3,4}. 

Are you expecting route policy at LA{3,4} to permit those advertisements?

<img width="1057" alt="Screen Shot 2020-09-13 at 7 06 23 PM" src="https://user-images.githubusercontent.com/4723124/93036479-d3a73f00-f5f4-11ea-94a4-1a1151922bc9.png">

**Comment by saparikh** [comment]
Could be an issue with community values on BGP routes originated via network statements. The LAs have a community list that determines what routes are sent to the LC and accepted from the LC. The only routes that I can see that have a community value that is in the configured community list are the ones covered by the network statement under router bgp.

**Comment by ratulm** [comment]
Samir is right about the community issue, but not about the originated routes. The issue seems to be that LC routers are not propagating communities received from LA routers. If I add the the `send-community` command, route propagation happens just fine and you can traceroute from one spine to another.

<img width="1022" alt="Screen Shot 2020-09-14 at 12 35 41 AM" src="https://user-images.githubusercontent.com/4723124/93057410-b7ba9200-f622-11ea-8861-0304a0456bdc.png">

Since communities are not propagated by default in IOS (XE), I believe that Batfish is doing the right thing. Let me know if I am mistaken on that front.

**Comment by laodulaodu** [comment]
Hi Ratul,

Per your last comments, is my  following understanding correct?   

the issue is that in the configurations, we missed "send-community" ?
our "original" configuration is not Cisco, they are SONiC (FRR BGP), so we don't need the send-community in our real network configurations,  it seems that if I send those SONiC (FRR) based configuration for verification, I need to add "send-community" to the normalized Cisco configuration so batfish can verify the network correctly.

just FYI

In order to use Batfish to analyze our network, we convert our SONiC NOS configurations to Cisco,  it seems that we need to figure out some gap between Cisco and SONiC BGP configuration

**Comment by saparikh** [comment]
You could just convert this to the Cumulus configuration format, so the FRR config will be handled via the FRR parser. If you try to convert this to Cisco IOS, you will likely continue to run into differences in behavior between FRR and IOS. But assuming you are using same FRR version as what is supported on latest Cumulus devices, you would be fine if you modeled them as Cumulus devices.

This link shows you the format of a file that is needed for Batfish to use the Cumulus parser - https://batfish.readthedocs.io/en/latest/formats.html#cumulus-configuration-files-preferred

**Comment by laodulaodu** [comment]
> After fixing an issue with interfaces not being recognized because of an unsupported name, I see that the spine routers are sending BGP advertisements from LA{1,2} to LA{3.4}, but those are being rejected by LA{3,4}.
> 
> Are you expecting route policy at LA{3,4} to permit those advertisements?
> 
> <img alt="Screen Shot 2020-09-13 at 7 06 23 PM" width="1057" src="https://user-images.githubusercontent.com/4723124/93036479-d3a73f00-f5f4-11ea-94a4-1a1151922bc9.png">

Per our configuration,  we expect the community number would be set and propagated out by LC's, so community should be matched ok and not rejected by L3/L4

**Comment by ratulm** [comment]
As I mentioned in the later comment, it was getting filtered about LCs are wiping out the communities attached by LAs.

**Comment by laodulaodu** [comment]
> You could just convert this to the Cumulus configuration format, so the FRR config will be handled via the FRR parser. If you try to convert this to Cisco IOS, you will likely continue to run into differences in behavior between FRR and IOS. But assuming you are using same FRR version as what is supported on latest Cumulus devices, you would be fine if you modeled them as Cumulus devices.
> 
> This link shows you the format of a file that is needed for Batfish to use the Cumulus parser - https://batfish.readthedocs.io/en/latest/formats.html#cumulus-configuration-files-preferred

that is good point,  we should  check it out

**Comment by ratulm** [comment]
Closing this issue since there isn't a bug to chase. (But you can of course keep the conversation going.)
