### ISSUE TITLE
Allow hostnames for destinations (dstIps now) in questions like traceroute

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#622]

**Comment by dhalperi** [comment]
There are a number of places where we take things that users may want to express in multiple ways. Services, hosts, etc. As a general principle, we should try to accept and recognize more types of input.

In other places this is hard. (E.g.,Is 53 a protocol number or a port?)

**Comment by ratulm** [comment]
Lets break this down into different issues. Opened #809 for groups of nodes. Open more for other concepts.
