### ISSUE TITLE
Arista source NAT -- Invalid Range Exception

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#6230]
From a Slack user -- The config file snippet below appears to lead to the exception below:

![image (6)](https://user-images.githubusercontent.com/4723124/94043336-a5a6c500-fd81-11ea-9a50-f57f7124e566.png)
![image (5)](https://user-images.githubusercontent.com/4723124/94043337-a63f5b80-fd81-11ea-8222-8ecae8fa525c.png)

I'll dig a little but if someone (@dhalperi?) knows what is happening off the top of their head, let me know.

**Comment by ratulm** [comment]
Looks like it stems from Batfish avoiding network and broadcast addresses ....

**Comment by dhalperi** [comment]
Fixed by https://github.com/batfish/batfish/pull/6108 and available in the latest dev build

**Comment by ratulm** [comment]
ah, thanks. no wonder i couldn't repro on master :)
