### ISSUE TITLE
Cisco IOS EIGRP distribute-list not recognized

### ISSUE THREAD

**Issue by AlexLardschneider** [batfish/batfish#6237]
Batfish doesn't seem to properly recognize the `distribute-list` command under the EIGRP configuration.
In the following example, the ACL `DISTRIBUTE-LIST-1` is marked as unused, which shouldn't be the case.
I also get an error about the `DISTRIBUTE-LIST-2` being undefined.

```
router eigrp 1
 redistribute static
 passive-interface default
 ...
 distribute-list prefix DISTRIBUTE-LIST-2 out FastEthernet0/0
 distribute-list DISTRIBUTE-LIST-1 in
!
ip access-list standard DISTRIBUTE-LIST-1
 ...
!
ip prefix-list DISTRIBUTE-LIST-2 seq 5 deny 0.0.0.0/0
```

Can't find any errors regarding the ACL in the diagnostics files.

I get the following error regarding `DISTRIBUTE-LIST-2` in the file `__initInfo`, notice the missing space between `prefix` and the name:

```
{
    "tag": "MISCELLANEOUS",
     "text": "distribute-list refers an undefined access-list `prefixDISTRIBUTE-LIST-2`, it will not filter anything"
}
```

**Comment by ratulm** [comment]
prefix-list tracking is still missing

**Comment by AlexLardschneider** [comment]
This issue still persists in the latest release of batfish. The error message I mentioned above is gone, but batfish still marks the associated `prefix-list` as unused.

Calling `bfq.unusedStructures().answer().frame()` outputs the following:
```
             Structure_Type            Structure_Name        Source_Lines
0            ipv4 prefix-list          DISTRIBUTE-LIST-2     configs/HOSTNAME.txt:[377, 378]
```

However, the prefix-list is used in the EIGRP config:

```
router eigrp 1
 distribute-list prefix DISTRIBUTE-LIST-2 out FastEthernet0/1.1604
```

**Comment by ratulm** [comment]
Fixed by https://github.com/batfish/batfish/pull/6345
