### ISSUE TITLE
IOS-XE: service-policy configured under EFP not recognized

### ISSUE THREAD

**Issue by AlexLardschneider** [batfish/batfish#6323]
The following `service-policy` command is not being recognized by batfish, thus marking the associated `policy-map` as unused:

```
interface GigabitEthernet0/0/0
 ...
 service instance XXXX ethernet
  service-policy output POLICY-MAP
```

Batfish outputs the following error:

```json
{
    "Details": "This syntax is unrecognized",
    "Line_Text": "service-policy output POLICY-MAP",
    "Nodes": null,
    "Parser_Context": "[cisco_configuration]",
    "Source_Lines": [
        {
            "filename": "configs/HOSTNAME.txt",
            "lines": [
                1006
            ]
        }
    ],
    "Type": "Parse warning"
}
```

**Comment by ratulm** [comment]
Parser_Context suggests that that particular line may not be to blame but something else before it is making the parser leave the parent context (service instance or interface). The code suggests the same -- parsing for that service-policy line is supported (though reference tracking does not, which we'll fix). 

Do you see a contiguous sequence unrecognized lines before the one you reported? Which is the first one in the sequence?
