### ISSUE TITLE
BGP maximum prefix on Cisco Routers

### ISSUE THREAD

**Issue by brotobia** [batfish/batfish#6332]
Batfish does not correctly take the bgp maximum prefix configuration into account. In the attached configurations, Router1 should not receive BGP route announcements from Router0, however in Batfish the BGP routes are present.
[configs-max-prefix.zip](https://github.com/batfish/batfish/files/5408869/configs-max-prefix.zip)

**Comment by dhalperi** [comment]
This feature is intentionally not supported, and I think there is also a warning to this effect; in almost every case the `maximum-prefix` should be very far from the actual number of routes. When they are close, the behavior is almost impossible to predict - which route will be installed vs dropped?

Users who don't want routes at all from a neighbor do this via import policy deny.
