### ISSUE TITLE
How to get started with Minesweeper?

### ISSUE THREAD

**Issue by yili-JIN** [batfish/batfish#6346]
I read your paper about Minesweeper and I want to try it.
While in the website (https://www.batfish.org/minesweeper/), I don't know how to follow the turtorial.
The Batfish's tutorial is based on PyBatfish (https://batfish.readthedocs.io/en/latest/getting_started.html), but there are nothing about Minesweeper in it.
So how can I get started with Minesweeper?

**Comment by njayinthehouse** [comment]
Is this still true today? I noticed that the repository has a new tag `2021-03-16-minesweeper`.

(Sorry to ask on a closed thread! I didn't think this question warranted opening a new issue.)

**Comment by dhalperi** [comment]
We have now basically deleted the Minesweeper and Bonsai code, as they were not maintained as the Batfish model evolved. There's a tag for the last compiling version (https://github.com/batfish/batfish/releases/tag/2021-03-16-minesweeper).
