### ISSUE TITLE
IOS - track structure not recognized

### ISSUE THREAD

**Issue by AlexLardschneider** [batfish/batfish#6347]
Batfish doesn't recognize the `track` structure. This leads to batfish assuming that the object referencing it is using an undefined structure.

```
interface Fa0/0
 standby 1 track 1 decrement 20
 ...
!
track 1 ip route 0.0.0.0 0.0.0.0 reachability
```

Batfish then warns about the `track 1` being undefined, even though it is.

**Comment by AlexLardschneider** [comment]
Seems like track boolean objects (`or / and`) are still not recognized fully. In the following example, batfish shows tracking objects 2 and 3 as being unused:

```
track 1 list boolean or
object 2
object 3
!
track 2 interface FastEthernet1/0 line-protocol
track 3 interface FastEthernet2/0 line-protocol
```

**Comment by ratulm** [comment]
Of course, there are always variants :) 

Are there other variants you use in the network? Or, a Cisco doc with all the options?

**Comment by AlexLardschneider** [comment]
No, at the moment we only use the variant in the example above, with either `and` or `or`.

I found a command reference [here](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp/command/iap-cr-book/iap-t1.html#wp1121388069), if that's what you're looking for.

**Comment by AlexLardschneider** [comment]
Hey @ratulm, I'm having difficulties getting batfish to recognize the following track objects. According to batfish, object `2` is undefined. Is tracking of `ip routing` on a `Dialer` interface not yet supported?

```
track 1 interface GigabitEthernet8 line-protocol
!
track 2 interface Dialer1 ip routing
!
track 3 list boolean and
 object 1
 object 2
```

**Comment by ratulm** [comment]
@AlexLardschneider  - the `ip routing` variant was not supported. added in https://github.com/batfish/batfish/pull/6530
