### ISSUE TITLE
How to make some adaptations to new devices not supported yet

### ISSUE THREAD

**Issue by tuyu95** [batfish/batfish#6363]
Hi，
Batfish supports configurations for a large and growing set of (physical and virtual) devices, like Cisco and Juniper. I'd like to ask that where can I add some new files or codes to let batfish learn more new devices not supported yet? Is there a configuration parser for each manufacturer so that I can make some adaptations to new devices.

**Comment by ratulm** [comment]
Hey, @tuyu95 - notes on adding a new vendor or new constructs for an existing vendor are here https://github.com/batfish/batfish/wiki/Developer-notes

(Closing this issue. If something is unclear, please open a more specific one, or better yet, find us on Slack.)
