### ISSUE TITLE
Store the original (non-normalized) interface name in the data model

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#639]
In particular, with the cisco/quagga interfaces, ethX is converted to EthernetX. It would be useful to have access to the original interface name for display purposes. Maybe you could call it `originalName` or `displayName`?

**Comment by dhalperi** [comment]
Ari, please follow up on this thread.

**Comment by arifogel** [comment]
Fixed by #821

**Comment by arifogel** [comment]
There is now a set in the data model of names by which an interface is referred to: `declaredNames`
