### ISSUE TITLE
Does batfish support Layer 2 switches

### ISSUE THREAD

**Issue by tuyu95** [batfish/batfish#6533]
Hello,
I'd like to ask if batfish supports Layer 2 switches?

**Comment by ratulm** [comment]
What is your exact setup?  If you have L2 switches and you supply physical topology (https://pybatfish.readthedocs.io/en/latest/formats.html#layer-1-topology-file), Batfish should be able to create L3 edges that go via that switch, and from there you should be able to perform L3 analysis.

**Comment by tuyu95** [comment]
> What is your exact setup? If you have L2 switches and you supply physical topology (https://pybatfish.readthedocs.io/en/latest/formats.html#layer-1-topology-file), Batfish should be able to create L3 edges that go via that switch, and from there you should be able to perform L3 analysis.

Thank you for your response！ For example, in a switch, there are some L2 configurations like "vlan", "trunk". Is Batfish able to analyse these configurations without L1  topology json files？

**Comment by tuyu95** [comment]
> What is your exact setup? If you have L2 switches and you supply physical topology (https://pybatfish.readthedocs.io/en/latest/formats.html#layer-1-topology-file), Batfish should be able to create L3 edges that go via that switch, and from there you should be able to perform L3 analysis.

Hey,
I have two more questions.
1. Does Batfish support SWITCH STACKS?
2. If given arp, Mac, lldp or cdp information, could Batfish draw the L2 topology?

**Comment by ratulm** [comment]
Looks like the conversation moved to Slack. That is a better place to discuss these things.
