### ISSUE TITLE
Add tests for #654

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#655]
Add more full-featured tests for #654

**Comment by dhalperi** [comment]
Tax for @sfraint

**Comment by sfraint** [comment]
Looked at this with Victor and could not figure out what actually needs to be tested

**Comment by arifogel** [comment]
Issues fixed by this PR that need proper testing:
- Test correct behavior of `ibgp` flag in `BgpAdvertisementsQuestion`
- Test proper conversion of conversion of standard to expanded community lists (in `org.batfish.representation.cisco`.
- For each `ConfigurationFormat` handled by `CiscoCombinedParser`, test that example community-list definitions in the vendor source language produce the correct vendor-independent community-list structures.
