### ISSUE TITLE
dose batfish support  m-lag and vrrp ?

### ISSUE THREAD

**Issue by Daisy0979** [batfish/batfish#6560]

**Comment by saparikh** [comment]
@Daisy0979 yes, it does. Btw... for questions like this, please use the Slack channel. You can join by following this link:

https://join.slack.com/t/batfish-org/shared_invite/enQtMzA0Nzg2OTAzNzQ1LTcyYzY3M2Q0NWUyYTRhYjdlM2IzYzRhZGU1NWFlNGU2MzlhNDY3OTJmMDIyMjQzYmRlNjhkMTRjNWIwNTUwNTQ
