### ISSUE TITLE
Question: Running multiple instances of batfish container in kubernetes cluster using replica sets

### ISSUE THREAD

**Issue by vparames86** [batfish/batfish#6565]
can we run multiple instances of the batfish container? In the docs it is mentioned that batfish needs a 32GB ram quadcore processor, is it feasible to split them into multiple containers and run them?

**Comment by dhalperi** [comment]
Hi @vparames86 - you are welcome to do so - docker gives you all the hooks you need.
* limit RAM
* remap ports
* run multiple instances of the same image

The only other thing you need to is to make pybatfish use different ports for the container you want it to use: https://github.com/batfish/pybatfish/blob/master/pybatfish/client/session.py#L310-L311

**Comment by dhalperi** [comment]
As for the 32 GiB of RAM, that is just a good recommendation for most networks - easily OSPF+BGP networks of many thousands of nodes have been handled there, though network structure and aggregation matter a lot. Feel free to tailor this to your network.
