### ISSUE TITLE
L3 Topology: models not taking into consideration L1

### ISSUE THREAD

**Issue by matozga** [batfish/batfish#6616]
When we supply the layer1 topology, the L3 modeling is not taking this into the calculations, resulting in "routing islands".
In the example attached we have a switch placed in between two routers:
[r1] --- [sw1] --- [r2]

Gig0/0 interface at R1 is potiting to SW1
Gig0/0 interface at R2 is potiting to SW1

Gig0/0 interface at R1 has 10.0.12.1/24 addressing
Gig0/0 interface at R2 has 10.0.12.2/24 addressing

The L1 topology is built correctly (according to the layer1_topology.json):
```
>>> bfq.edges(edgeType="layer1").answer().frame()
                 Interface         Remote_Interface
0   r2[GigabitEthernet0/0]  sw1[GigabitEthernet1/2]
1  sw1[GigabitEthernet1/2]   r2[GigabitEthernet0/0]
2   r1[GigabitEthernet0/0]  sw1[GigabitEthernet1/1]
3  sw1[GigabitEthernet1/1]   r1[GigabitEthernet0/0]
>>>
```

However, for L3 topology, there is missing information:
```
>>> bfq.edges(edgeType="layer3").answer().frame()
Empty DataFrame
Columns: [Interface, IPs, Remote_Interface, Remote_IPs]
Index: []
>>>
```

The same behavior was observed on Firewalls in transparent mode (e.g. using virtual-wire links).

[snapshot.zip](https://github.com/batfish/batfish/files/5960968/snapshot.zip)

**Comment by dhalperi** [comment]
Thanks @matozga!

What is the L2 config like on the switch? Are the interfaces in trunk mode, etc?

What does `bf.q.interfaceProperties()` look like for the relevant switch interfaces?

**Comment by saparikh** [comment]
Your switch config is not correct. You need to put the routers interfaces in a VLAN (can be setup as a native VLAN) and then have the switch ports be configured as trunks which carry the VLAN. 

Batfish does not model L2 forwarding, but if you have a trunk interface it will extend the L2 domain and then build a L3 edge on top of it.

**Comment by matozga** [comment]
Yes, this make sense!
As soon as I changed the interfaces to Access/Trunk in the config, I received populated L3 topology.

I think this can be closed now.
