### ISSUE TITLE
Not seing domain name in Panos bfq.nodeProperties().answer().frame()

### ISSUE THREAD

**Issue by kmjmartin** [batfish/batfish#6676]
Hi, 

We're not seeing the device domain name setting from any of our Paloa Alto firewalls.
The batfish query is:
df = bfq.nodeProperties().answer().frame()

The result for the Domain_Name value is None for all firewall nodes.
Have tested from both PALO_ALTO_NESTED and ALO_ALTO Configuration_Format's

using version:
pybatfish==2020.10.8.667

in the configs the domain name is between ntp and snmp-settings:

          ntp-servers {
            primary-ntp-server {
              ntp-server-address xxxxxx;
              authentication-type {
                none;
              }
            }
            secondary-ntp-server {
              ntp-server-address xxxxxx;
              authentication-type {
                none;
              }
            }
          }
          domain domainname.com.au;  <- here
          snmp-setting {
            access-setting {
              version {
                v2c {
                  snmp-community-string xxxxxx;
                }
              }
            }
            snmp-system {
              location xxxxxx;
              contact xxxxxx;
            }
          }

**Comment by dhalperi** [comment]
Thanks @kmjmartin - we'll take a look!

**Comment by dhalperi** [comment]
Hi @kmjmartin , this should be fixed now and will be testable either at HEAD or in tonight's development build of Batfish.

**Comment by kmjmartin** [comment]
thanks @dhalperi, appreciate it! I will test asap

**Comment by kmjmartin** [comment]
Hi @dhalperi ,

Sorry.. quick question, how do I get the latest version? pip is only showing a version from what looks like last week - 2021.2.26.830

Thanks again,

Kane

**Comment by dhalperi** [comment]
Hi @kmjmartin - pull the latest `test-<build#>` version of the `batfish/batfish` or `batfish/allinone` container.

The list of versions is here: https://hub.docker.com/r/batfish/batfish/tags?page=1&ordering=last_updated, and the last one is the highest number. (Docker hub seems to not consistently put the last one on the top or the bottom, but `test-835` is the build that was pushed 9 hours ago at time of writing).

For example,

`docker pull batfish/batfish:test-835` or `docker pull batfish/allinone:test-835`.

**Comment by kmjmartin** [comment]
thanks @dhalperi , I was able to test this just now and it's working.
