### ISSUE TITLE
Questions about old batfish

### ISSUE THREAD

**Issue by liyahui-thu** [batfish/batfish#674]
I have read the paper "A General Approach to Network Configuration Analysis (NSDI 2015)". It 's very marvelous.   I have two question about batfish . 
  1. Datalog is a specific First Order Logic. The ability of model in First Order Logic Formula is much more powerful. Does it mean that: if we encode in First Order Logic Formula and solve it with SMT Solver, it will be better?  Why not First Order Logic Formula? Compare with First Order Logic Formula, what's the advantages that we model control plane in Datalog?
   2. The control plane model in paper is written in Datalog. Z3 supports solve Datalog program which are encoded in the smt2 format? Can we encode control model (e.g., NOD[NSDI 2015] directly encode their data plane model in µZ3)?  Why we encode the control model in Logical language?

**Comment by ratulm** [comment]
Good questions. Answers are tied to the expressiveness of any encoding and if you can solve it using an efficient solver. 

1. The original Batfish encoding goes beyond Datalog in reality, e.g., it has arithmetic, which is needed to encoding routing computations. I don't think you can do that with pure first-order logic.

2. See answer above :) Encoding control model directly in a logic language is possible, but if you don't want to run the "model" as original Batfish does, you need to describe the fixed point. (NoD does not compute the fixed point.) The Minesweeper paper (SIGCOMM 2017) shows one way to do that.

**Comment by liyahui-thu** [comment]
Yes, Minesweeper proposed combinational search (not message set computation).

**Comment by ratulm** [comment]
Closing this issue, assuming that your questions were answered. Re-open if needed.
