### ISSUE TITLE
ip as-path access-lists on Arista EOS

### ISSUE THREAD

**Issue by bellresearch** [batfish/batfish#6758]
I think I may have found something worth review by the Batfish dev team:

While doing some route analysis with Batfish, I noticed that in my "live" network, I was able to recieve a bgp route announcement at the ultimate destination, six routers away.  However, the announcement was not getting past the third router of the six, in my Batfish test setup. After much investigation, there was a route map set up on a BGP peer using an as-path access list and here's the key: it had the "any" keyword at the end. According to Arista EOS docs (https://www.arista.com/en/um-eos/eos-border-gateway-protocol-bgp#xx1116711) the "any" keyword denotes the origin type and it seems like it may have been causing an issue for Batfish. Running the Test Route Policy question against the route map returned that the prefix would be denied by the route map (which is why the announcement wasn't making it past the third router) when in fact the as-path regex was correct to permit the advertisement of the prefix. I removed the "any" keyword from the end of the as-path access list in the config file, and ran Batfish again. This time all worked as expected and the routing mirrored that of my live network. It took me some time to t-shoot and debug this one, so passing it along with the hope that it helps.

**Comment by dhalperi** [comment]
Thanks @bellresearch ! I opened a quick fix for the issue, which will be available for testing in a day or two.

For now I only implemented the `any` keyword, as that is trivial for us.

**Comment by bellresearch** [comment]
Excellent, thanks!
