### ISSUE TITLE
Cisco NX-OS: Area summary route missing due to parse warning, resulting in missing BGP route

### ISSUE THREAD

**Issue by racsoce** [batfish/batfish#6794]
We have several Cisco Nexus 7k with BGP sessions that advertises aggregated networks without the "aggregate-address" statement, this causes Batfish to don't export the network in the topology.

This is a small example between one cisco nx7k and a juniper mx104,
functioning in production we have this config in the Nexus exporting 10.148.0.0/16 properly:

router bgp 64521
  router-id 10.148.150.204
  address-family ipv4 unicast
    network 10.148.27.10/16 route-map BGP_ORIGIN
  template peer-policy BACKBONE_BE
    send-community both
    route-map BACKBONE_BE_IN in
    route-map BACKBONE_BE_OUT out
    next-hop-self
    soft-reconfiguration inbound

but in Batfish we need to add "aggregate-address 10.148.27.10/16" as follows:

router bgp 64521
  router-id 10.148.150.204
  address-family ipv4 unicast
    network 10.148.27.10/16 route-map BGP_ORIGIN
    **aggregate-address 10.148.27.10/16**
  template peer-policy BACKBONE_BE
    send-community both
    route-map BACKBONE_BE_IN in
    route-map BACKBONE_BE_OUT out
    next-hop-self
    soft-reconfiguration inbound
  template peer-policy iBGP
    send-community both
    next-hop-self
    soft-reconfiguration inbound

Tested with the configurations attached, after making the snapshot you will obtain:
bfq.routes(rib='bgp').answer().frame()
         Node      VRF          Network    Next_Hop_IP Next_Hop_Interface Protocol  ...    Communities Origin_Protocol Origin_Type   Originator_Id Cluster_List    Tag
0  eu1-core01  default  10.156.152.0/24  10.148.151.79            dynamic      bgp  ...  ['64521:200']             bgp         igp  10.156.152.209         None  64500

Adding the line in the Nexus 7k and making again the snapshot:
bfq.routes(rib='bgp').answer().frame()
         Node      VRF          Network    Next_Hop_IP Next_Hop_Interface   Protocol  ...    Communities Origin_Protocol Origin_Type   Originator_Id Cluster_List    Tag
0  eu1-core01  default    10.148.0.0/16        0.0.0.0            dynamic  aggregate  ...             []       aggregate  incomplete  10.148.150.204         None   None
1  eu1-core01  default  10.156.152.0/24  10.148.151.79            dynamic        bgp  ...  ['64521:200']             bgp         igp  10.156.152.209         None  64500
2  eu1-dcbr01  default    10.148.0.0/16  10.148.151.78            dynamic        bgp  ...  ['64500:521']             bgp         igp  10.148.150.204         None   None

Thanks,
[config.zip](https://github.com/batfish/batfish/files/6215008/config.zip)

**Comment by dhalperi** [comment]
Hey @racsoce - thanks for the nice report.

I'm trying to reproduce on our N7k emulator, and I'm having a hard time. Here's what I've tried:

```
switch(config-router-af)# show run | sec route-map
route-map permit-all permit 10
  set community 1:2 
switch(config-router-af)# show run | sec bgp
feature bgp
router bgp 1
  address-family ipv4 unicast
    network 10.0.0.0/16 route-map permit-all
switch(config-router-af)# show run | sec loopback
interface loopback0
  ip address 10.0.0.1/32
switch(config-router-af)# show run | sec "ip route"
ip route 0.0.0.0/0 Null0
ip route 10.0.0.0/15 Null0
ip route 10.0.0.0/17 Null0
```

No matter what I do, I can't get the device to generate `10.0.0.0/16` unless I explicitly add `ip route 10.0.0.0/16 null0` to the config. That is, I have to have that exact route (not a more specific) in the main RIB before the `network` statement will take effect.

Since you have these configs running in production, can you please confirm that there's no other `10.148.0.0/16` route on the box? It really is being generated solely from the /26, like an `aggregate-address` would?

Thanks!

**Comment by racsoce** [comment]
Hello @dhalperi,
The configs uploaded was anonymized using 'netconan', what we have in production is this:

several SVIs on the net 10.74.x.x/16 like these:
eu1-core01# sh run | inc "ip address 10.74."
  ip address 10.74.224.2/23
  ip address 10.74.216.2/21
  ip address 10.74.4.2/24
  ip address 10.74.0.2/26
**** some output committed ****

for routes:

eu1-core01# sh run | sec "ip route"
ip route 0.0.0.0/0 10.74.255.21
  ip route 0.0.0.0/0 10.68.253.1
  ip router ospf eu1nx7k-priv area 10.74.0.0
  ip router ospf eu1nx7k-priv area 10.74.0.0
**** some output committed ****

and that advertises our /16 to the bgp neighbor with:

router bgp 64521
  router-id 10.74.255.254
  address-family ipv4 unicast
    network 10.74.0.0/16 route-map BGP_ORIGIN
  template peer-policy BACKBONE_BE
    send-community both
    route-map BACKBONE_BE_IN in
    route-map BACKBONE_BE_OUT out
    next-hop-self
    soft-reconfiguration inbound
  template peer-policy iBGP
    send-community both
    next-hop-self
    soft-reconfiguration inbound
  template peer-session BACKBONE_BE
    remote-as 64500
    password
  template peer-session iBGP
    remote-as 64521
    password
  neighbor 10.74.254.64 remote-as 64500
    low-memory exempt
    inherit peer-session BACKBONE_BE
    no shutdown
    address-family ipv4 unicast
      inherit peer-policy BACKBONE_BE 1
  neighbor 10.74.255.10 remote-as 64521

eu1-core01# sh ip bgp neighbors 10.74.254.64 advertised-routes 

Peer 10.74.254.64 routes for address family IPv4 Unicast:
BGP table version is 38138, local router ID is 10.74.255.254
Status: s-suppressed, x-deleted, S-stale, d-dampened, h-history, *-valid, >-best
Path type: i-internal, e-external, c-confed, l-local, a-aggregate, r-redist, I-injected
Origin codes: i - IGP, e - EGP, ? - incomplete, | - multipath, & - backup

   Network            Next Hop            Metric     LocPrf     Weight Path
*>l10.74.0.0/16       0.0.0.0                           100      32768 i
eu1-core01# 

hope this helps, or let me know if you need more details,

Regards,
Oscar,

**Comment by dhalperi** [comment]
Can you show the main rib and look for `10.74.0.0/16`?

**Comment by racsoce** [comment]
like this?

eu1-core01# sh ip route 10.74.0.0/16
IP Route Table for VRF "default"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%<string>' in via output denotes VRF <string>

10.74.0.0/16, ubest/mbest: 1/0
    *via Null0, [220/40], 31w0d, ospf-eu1nx7k-priv, discard
eu1-core01#

**Comment by dhalperi** [comment]
Thanks @racsoce ! That tells me we're not modeling that OSPF summary route, and if we did that I bet that the `network` would be there. (confirming @chiragvyas50 suspicion)

I think that `aggregate-address` is a red herring, and the issue is that summary route.

Will see if we can get this going :).
