### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by adiapel** [batfish/batfish#6901]
Hi!
While running checkstyle with some certain modules names, I found a few changes I would like to make in some files in the project.
I have 2 questions:
1. Do I need to open a issue before making a pull request?
2. which branch should I commit to?
Thank you!
Adi

**Comment by dhalperi** [comment]
Just go for it, thanks!
Dan

**Comment by adiapel** [comment]
so a pull request from "detect loops" branch to "master" would be OK?
Adi
