### ISSUE TITLE
compareFilters not working for Juniper SRX

### ISSUE THREAD

**Issue by racsoce** [batfish/batfish#7013]
trying to use compareFilters for Juniper policies behaves abnormally and looks like is inverting the policy lines and the differences are twice the number of policies per filter, as example **using the same file**:

`result = bfq.compareFilters(nodes='iad1-dcfw-core-01', filters='zone~backbone~to~zone~iad1-mad-be-np-app').answer(snapshot='ToTest',reference_snapshot='online').frame()`

having 41 policies the compareFilters has 81 differences, but check the output:

![image](https://user-images.githubusercontent.com/24923565/119171335-0af2a900-ba2a-11eb-8efb-fd376c2bafbf.png)

![image](https://user-images.githubusercontent.com/24923565/119171363-17770180-ba2a-11eb-8ce0-14c58a66cc96.png)

Thanks,
[iad1-dcfw-core-01.zip](https://github.com/batfish/batfish/files/6523971/iad1-dcfw-core-01.zip)

**Comment by anothermattbrown** [comment]
Thanks for the report @racsoce! We've found the bug and will have a fix you can try out shortly.
