### ISSUE TITLE
Arista - unrecognized NAT syntax

### ISSUE THREAD

**Issue by rmcmilli** [batfish/batfish#7032]
I get the following in the batfish diagnostics log for this static source NAT syntax from an Arista EOS device: 

```
>>> result.iloc[3]
Filename                                        configs/coreswitch1
Line                                                            693
Text              ip nat source static 10.40.50.104 access-list ...
Parser_Context    [if_ip_nat_source if_ip if_inner s_interface s...
Comment                                 This syntax is unrecognized
Name: 3, dtype: object
```

A sanitized version of this configuration: 

```
hostname CoreSwitch1
!
int eth1
    ip address 10.10.10.1/24
    ip nat source static 10.40.50.104 access-list ACL-NAT-1-OUT 192.168.10.4
    !
!
ip access-list ACL-NAT-1-OUT
    10 permit ip any 10.200.0.0/24
!
```

The syntax works in production and is consistent with Arista documentation.

**Comment by rmcmilli** [comment]
I can also confirm that the dynamic syntax is unrecognized as well. 
```
Nodes                                                          None
Source_Lines                            [configs/coreswitch1:[693]]
Type                                                  Parse warning
Details                                 This syntax is unrecognized
Line_Text         ip nat source dynamic ACL-DYN-NAT-601-OUT pool...
Parser_Context    [if_ip_nat_source if_ip if_inner s_interface s...
Name: 2, dtype: object
```

Sanitized configuration

```
hostname CoreSwitch1
!
int eth1
    ip address 10.10.10.1/24
    ip nat source dynamic 10.40.50.104 access-list ACL-DYN-NAT-1-OUT pool NAT-POOL-1
    !
!
 ip access-list ACL-DYN-NAT-1-OUT
   10 permit ip host 10.40.50.105 10.200.0.0/24
!
ip nat pool NAT-POOL-1
   range 192.168.10.4 192.168.10.4
```

As before, this syntax works in production and is consistent with Arista documentation

**Comment by dhalperi** [comment]
Hey @rmcmilli - thanks, we're taking a look at this. The static NAT is definitely not parsed today, but I'm surprised that the dynamic NAT is not handled. That should be there. Are you sure the file is being recognized as Arista? You can find this by checking the `fileParseStatus` question.

One thing that makes it complicated is I can't find a virtual Arista platform that supports NAT. Hard to test implementations.

**Comment by rmcmilli** [comment]
Hi @dhalperi ignore the post about the dynamic NAT. My configuration was incorrect. I later realized and removed it.

**Comment by dhalperi** [comment]
Hey @rmcmilli , thanks. I have a "working" fix but it will not catch bugs or strange behavior yet, as I have been unable to test the behavior of corner cases on an Arista platform. Can you look at https://github.com/batfish/batfish/issues/7047 and confirm that the ACL you use is simple and of the expected form?

Thanks.

**Comment by rmcmilli** [comment]
Hi @dhalperi , the ACL included is pulled directly from my configuration. Formatting included, this is running in production and is in the form in the document linked in #7047  
```
ip access-list ACL-NAT-1-OUT
    10 permit ip any 10.200.0.0/24
!
```

**Comment by dhalperi** [comment]
Great. That means that the stuff we can't determine yet won't affect you :)

**Comment by dhalperi** [comment]
@rmcmilli - this is merged to master now and will be available in the next nightly release of Batfish. It may not be correct under misconfiguration / complex configuration (#7047), but for the simple case you have it should be great.

Please let me know how it goes.
