### ISSUE TITLE
Can Batfish parse the configuration of Internet2?

### ISSUE THREAD

**Issue by xiaozheshao** [batfish/batfish#7036]
I put the configuration of Internet2 (https://vn.net.internet2.edu/Internet2/configs/configs.html) into a few .cfg files. I compile the source code to generate the jar package, allinone-bundle-0.36.0.jar. It works well when I load the configuration files of the example networks. 
When I load the configuration files of Internet2, I always get the following errors. 

Parsing now.
21:32:31.286 [Thread-4] ERROR org.batfish.common.BatfishLogger - Failure running job after elapsed time: 00:00:00.19
-----BEGIN JOB LOG-----

-----END JOB LOG-----:
	org.batfish.common.BatfishException: Conversion error for node with hostname 'rtsw.alba-re1'
	at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:304)
	at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.batfish.representation.juniper.JuniperConfiguration.toRibGroup(JuniperConfiguration.java:2598)
	at org.batfish.representation.juniper.JuniperConfiguration.createBgpProcess(JuniperConfiguration.java:586)
	at org.batfish.representation.juniper.JuniperConfiguration.toVendorIndependentConfiguration(JuniperConfiguration.java:3437)
	at org.batfish.representation.juniper.JuniperConfiguration.toVendorIndependentConfigurations(JuniperConfiguration.java:2976)
	at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:272)
	... 7 more

{"answerElements":[{"class":"org.batfish.datamodel.answers.InitInfoAnswerElement","parseStatus":{"configs/alba.cfg":"PARTIALLY_UNRECOGNIZED","rtsw.alba-re1":"FAILED"}}],"status":"SUCCESS","summary":{"numFailed":0,"numPassed":0,"numResults":0}}

Should I make some modifications to the configuration files of Internet2 before I use Batfish to load them?

**Comment by ratulm** [comment]
hey, @xiaozheshao - the stack trace suggests that you are not running the latest code. if that is right, the first thing you should probably do is to try with the latest code. 

if the error persists, try narrowing down the problem:
  - you already know the file to focus on -- the one that belongs to `rtsw.alba-re1` 
  - see what configuration commands in there are problematic. the function names suggest something to do with ribgroups. note that you'll have to do this to modify configs. 

please share the problematic config snippets, or the full file if you are not able to narrow things down, so someone can take a look.

**Comment by xiaozheshao** [comment]
> hey, @xiaozheshao - the stack trace suggests that you are not running the latest code. if that is right, the first thing you should probably do is to try with the latest code.
> 
> if the error persists, try narrowing down the problem:
> 
> * you already know the file to focus on -- the one that belongs to `rtsw.alba-re1`
> * see what configuration commands in there are problematic. the function names suggest something to do with ribgroups. note that you'll have to do this to modify configs.
> 
> please share the problematic config snippets, or the full file if you are not able to narrow things down, so someone can take a look.

Thanks for your prompt response!  I try the latest code and get the same stack trace. 
The issue might be related to the BGP configuration. I try to narrow down the problem by removing some configuration snippets.  If I remove all neighbors from peer groups of BGP, then the error disappears. 
Please refer to attached the configuration files of Internet2. 

[configs.zip](https://github.com/batfish/batfish/files/6581828/configs.zip)

**Comment by ratulm** [comment]
hey, @xiaozheshao - can you provide a small config that shows the exception? perhaps leave one neighbor in the group in the offending file, and also remove config snippets that do not matter. thanks.

**Comment by xiaozheshao** [comment]
Hi, @ratulm  I fixed the errors in the configuration files. Now, Bagfish can parse the configuration files. I really appreciate your help in resolving the problem.

**Comment by ratulm** [comment]
was there an error in the files? can you share what it was?

**Comment by xiaozheshao** [comment]
@ratulm Some sections of those configuration files are removed for security purposes. I think some errors happen in the removal. In the configuration files, the lines around "SNMP Stanza Removed" are not valid. Please refer to the ending of each configuration file. When I fix the errors in the files, Batfish works well.
