### ISSUE TITLE
verify correct implementation of additional-paths in bdp

### ISSUE THREAD

**Issue by arifogel** [batfish/batfish#704]
Right now when additional-paths is on, all bgpMultipath routes are sent. Perhaps a check should be added for each such route that it is also in the mainRib.

**Comment by dhalperi** [comment]
cc: @progwriter. fyi, maybe you want to see this old issue. Up to you to determine if done, needs addressing, or low priority.

**Comment by progwriter** [comment]
My assessment of this issue:

1. This is low priority, add-path is rarely used.
2. We spotty support for this pipeline anyway. We only parse `additional-paths ALL` while there are also `additional-path BEST N` and `additional-paths group-best`. And that's only Cisco. Juniper can have a prefix-policy associated with `add-path send`.

Good to be aware for this. Un-assigning myself for now, happy to come back to it if there is pressure for full `add-path` support.

**Comment by dhalperi** [comment]
Stale, not there.
