### ISSUE TITLE
Run batfish server on IDEA

### ISSUE THREAD

**Issue by yrll** [batfish/batfish#7051]
when i follow the [https://github.com/batfish/batfish/wiki/Building-and-running-Batfish-service](url) to run the batfish server on IDEA, there comes a mistake and i don't know how to fix it and continue run the server:

this is the commond:
> java -jar projects/allinone/target/allinone-bundle-0.36.0.jar -runclient false -coordinatorargs "-templatedirs questions"

it's the error:
> 17:53:57.159 [batfishThread] ERROR org.batfish.common.BatfishLogger - FATAL ERROR: Failed to s
tart Grizzly HTTP server: Address already in use: bind
> FATAL ERROR: Failed to start Grizzly HTTP server: Address already in use: bind

**Comment by yrll** [comment]
After i edit "Allinone" configuration like this: (followed this doc [https://github.com/batfish/batfish/wiki/IntelliJ#4-running-batfish-from-inside-intellij](url) )

> -runmode
> interactive
> -loglevel
> debug
> -batfishmode
> workservice
> -coordinatorargs
> "-templatedirs questions"
> -runclient
> false

then i run the Allinone, it turn out :
`This is not a supported client for Batfish. Please use pybatfish following the instructions in the README: https://github.com/batfish/batfish/#how-do-i-get-started
六月 05, 2021 9:15:28 下午 org.jline.utils.Log logr
警告: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Could not initialize client: 系统找不到指定的路径。
java.io.IOException: 系统找不到指定的路径。
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1023)
	at org.batfish.client.Client.<init>(Client.java:777)
	at org.batfish.client.Client.<init>(Client.java:800)
	at org.batfish.allinone.AllInOne.run(AllInOne.java:101)
	at org.batfish.allinone.Main.main(Main.java:6)
Client initialization failed with args:  -loglevel debug -runmode interactive -tracingenable false -cmdfile dummy_allinone
ExceptionMessage: null`

I'm wondering how can i use pybatfish on Pycharm and run the batfish server locally on IDEA ？:)

**Comment by ratulm** [comment]
hey, @yrll - your first comment suggests that the ports batfish needs (9996, 9997) are taken (perhaps by the container?). if you kill the occupier that command should have worked. 

where did you get the command options in the second comment? (the URL doesn't go anywhere and I can't find the commands in the page I think you are pointing at.) the options you used in the first comment are  the ones to use. 

PS: it might be easier to post such questions on #dev channel of our Slack workspace: https://join.slack.com/t/batfish-org/shared_invite/enQtMzA0Nzg2OTAzNzQ1LTcyYzY3M2Q0NWUyYTRhYjdlM2IzYzRhZGU1NWFlNGU2MzlhNDY3OTJmMDIyMjQzYmRlNjhkMTRjNWIwNTUwNTQ

**Comment by yrll** [comment]
Hey, @ratulm , thanks for your explanation. yeah, after i check the running log i found the "starting server port 9999" was occupied by my VPN server, and i killed it then the batfish can run. :)

**Comment by ratulm** [comment]
ok, great, closing this issue then. let us know if you run into anything else.
