### ISSUE TITLE
Bulk upload on batfish container results in 'Connection aborted.'

### ISSUE THREAD

**Issue by vparames86** [batfish/batfish#7110]
I am trying to upload around 4000 configuration files to the batfish container. The batfish container runs as a replica set with 10 instance in a kubernetes cluster. What I notice is all the files were uploaded properly by checking the persistent storage 'data' location. But the connection gets aborted in the middle. 

**"Result: Failure\nException: ConnectionError: HTTPSConnectionPool(host='x.x.x.x', port=9995): Max retries exceeded with url: /batfishworkmgr/uploadsnapshot (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))\**

Note: There is no retry as the upload snapshot is a post call.

Since batfish is doing both upload and snapshot init using a single api call, if the init takes a very long time the server drops the connection. The request connection timeout at the pybatfish client is infinite I guess since we haven't set one.

I feel separating the upload and init snapshot functionality would be better for these type of scenarios. 

Also when I query the snapshot status, the response is "UNINITIALIZED". So I guess the processing of the configuration files took a very long time and the connection gets aborted.

**Comment by dhalperi** [comment]
The upload and init is already separated.

My guess is that the backend does not have enough RAM.

**Comment by dhalperi** [comment]
Also, if you are replicating in kubernetes I assume you are properly able to do connection pinning? How otherwise do you ensure the same backend instance processes all requests for the same network?
