### ISSUE TITLE
public_ips["west2_public"] = "54.191.42.182" # of i-02cae6eaa9edeed70 ，i-02cae6eaa9edeed70 with publicIp[54.191.42.182] cannot connect internet

### ISSUE THREAD

**Issue by ikv163** [batfish/batfish#7138]
#Instances in AWS in each region and VPC type (public, private)
hosts = {}
hosts["east2_private"] = "i-04cd3db5124a05ee6"
hosts["east2_public"] = "i-01602d9efaed4409a"
hosts["west2_private"] = "i-0a5d64b8b58c6dd09"
hosts["west2_public"] = "i-02cae6eaa9edeed70"

#Public IPs of instances in AWS
public_ips = {}
public_ips["east2_public"] = "13.59.144.125" # of i-01602d9efaed4409a
public_ips["west2_public"] = "54.191.42.182" # of i-02cae6eaa9edeed70

'Flow: start=i-02cae6eaa9edeed70 [10.40.2.80:49152->0.0.0.0:80 TCP length=512]'

DENIED_OUT
1. node: i-02cae6eaa9edeed70
  ORIGINATED(default)
  FORWARDED(ARP IP: 10.40.2.1, Output Interface: eni-087e18628dadd9b48, Routes: [static (Network: 0.0.0.0/0, Next Hop IP:10.40.2.1)])
  PERMITTED(~EGRESS_ACL~eni-087e18628dadd9b48 (EGRESS_FILTER))
  SETUP_SESSION(Incoming Interfaces: [eni-087e18628dadd9b48], Action: Accept, Match Criteria: [ipProtocol=TCP, srcIp=0.0.0.0, dstIp=10.40.2.80, srcPort=80, dstPort=49152])
  TRANSMITTED(eni-087e18628dadd9b48)
2. node: subnet-06005943afe32f714
  RECEIVED(to-instances)
  FORWARDED(ARP IP: 169.254.0.1, Output Interface: vpc-00b65e98077106059-vrf-igw-0a8309f3192e7cea3, Routes: [static (Network: 0.0.0.0/0, Next Hop IP:169.254.0.1)])
  PERMITTED(acl-087574e8620270842_egress (EGRESS_FILTER))
  TRANSMITTED(vpc-00b65e98077106059-vrf-igw-0a8309f3192e7cea3)
3. node: vpc-00b65e98077106059
  RECEIVED(subnet-06005943afe32f714-vrf-igw-0a8309f3192e7cea3)
  FORWARDED(ARP IP: 169.254.0.1, Output Interface: igw-0a8309f3192e7cea3, Routes: [static (Network: 0.0.0.0/0, Next Hop IP:169.254.0.1)])
  TRANSMITTED(igw-0a8309f3192e7cea3)
4. node: igw-0a8309f3192e7cea3
  RECEIVED(vpc-00b65e98077106059)
  PERMITTED(~DENY~UNASSOCIATED~PRIVATE~IPs~ (INGRESS_FILTER))
  FORWARDED(ARP IP: 169.254.0.1, Output Interface: backbone, Routes: [bgp (Network: 0.0.0.0/0, Next Hop IP:169.254.0.1)])
  TRANSFORMED(SOURCE_NAT srcIp: 10.40.2.80 -> 54.191.42.182)
  TRANSMITTED(backbone)
5. node: isp_16509
  RECEIVED(To-igw-0a8309f3192e7cea3-backbone)
  FORWARDED(ARP IP: 169.254.0.1, Output Interface: To-Internet, Routes: [bgp (Network: 0.0.0.0/0, Next Hop IP:169.254.0.1)])
  DENIED(Block outgoing traffic using reserved addresses (EGRESS_FILTER))

**Comment by ikv163** [comment]
# traceroute between instances across region using the destination's private IP
ans = bfq.traceroute(startLocation=hosts["west2_public"], 
                     headers=HeaderConstraints(dstIps="internet",
                                              applications="http")).answer()
show_first_trace(ans.frame())

**Comment by ratulm** [comment]
The destination IP that the traceroute is using is `0.0.0.0`, which is probably not what you intended and is being filtered (as intended).  This IP is being auto-selected based on your dstIps specification of "internet". You may want to use a more specific IP.

**Comment by ikv163** [comment]
yeah, that's true
