### ISSUE TITLE
Some Panos firewalls are not collecting data

### ISSUE THREAD

**Issue by kmjmartin** [batfish/batfish#7177]
Hi,

We're running Batfish on a number of Panos devices, but are seeing a small number of those are not returning any values from the configuration except a couple of policy related columns. If looks like the device config command is not being parsed.

I can't see any obvious differences in the configs that batfish is using, between devices that work and those that don't.
Using batfish-test-848, but have tested with batfish-test-980 to see if this has been resolved already.

What data could I provide to allow this to be looked into?

Thanks,

Kane

**Comment by ratulm** [comment]
Did you at initIssues for devices that don't work and compare with those that work?

**Comment by kmjmartin** [comment]
Hi @ratulm 

thanks, I can find a line that references the firewalls that can't be parsed, seems to be related to the login-banner.
Parse warning, This syntax is unrecognized, ***********************************************************************", [set_line_tail set_line palo_alto_configuration]

though looking other firewalls have the same banner between the quotes, but are working.

config {
  devices {
    localhost.localdomain {
      deviceconfig {
        system {
          login-banner " .... ";

I could organise a change to remove * from the banners, but ideally all of the characters should be ignored between those quotes.

**Comment by dhalperi** [comment]
Some versions of PanOS fail to escape their own syntax properly 🙄 . For those ones, we have two solutions:

1. Manually fix the configs.
2. Export as XML, then run the XML through their Python library that converts XML to show output. @sfraint can probably describe this...  (and document it?)

**Comment by kmjmartin** [comment]
Hi, 

Thanks, I did some more testing and found that removing descriptions from rules fixed half of the firewalls, but the rest still don't work.
I'll see what I can get with XML.

Thanks

**Comment by kmjmartin** [comment]
Hi, 

Looks like the XML formatting for 'show config pushed-shared-policy' is broken on the firewall, none of the tags are present so it outputs as a huge block of text.

The instructions here:
https://batfish.readthedocs.io/en/latest/formats.html
- don't really work, in that the output is no in 'set' format, but just in the default 'json-ish' panos format.
But that said, that is the output that works for 90% of our firewalls.

**Comment by dhalperi** [comment]
Hey @kmjmartin - sorry, this sounds frustrating.

Here's what I would do:
1. isolate the file that is causing problems in its own snapshot.  `foo/configs/bad-fw.txt` or whatever.
2. Run the annotation tool on that file: `bazel run //tools:annotate foo foo-annotated`
3. Look at the output `foo-annotated/configs/bad-fw.txt`. That will show you how Batfish is understanding that file. You may be able to tell from there where things went wrong with the flattening, with the string parsing, etc.

**Comment by kmjmartin** [comment]
Hi @dhalperi 

I got bazel run working, and it annotates some of the configs. The ones that can't be parse though have a 'Failed to parse' error:

12:38:15.004 [ForkJoinPool.commonPool-worker-3] ERROR org.batfish.main.annotate.Annotate - Failed to parse: /home/ubuntu/projects/scripts/batfish/configs/panos/configs/xyz.cfg
12:39:28.583 [main] ERROR org.batfish.main.annotate.Annotate - Failed to parse: /home/ubuntu/projects/scripts/batfish/configs/panos/configs/xyz.cfg
12:40:00.730 [ForkJoinPool.commonPool-worker-3] ERROR org.batfish.main.annotate.Annotate - Failed to parse: /home/ubuntu/projects/scripts/batfish/configs/panos/configs/xyz.cfg
12:41:00.805 [main] ERROR org.batfish.main.annotate.Annotate - Failed to parse: /home/ubuntu/projects/scripts/batfish/configs/panos/configs/xyz.cfg
12:41:27.061 [ForkJoinPool.commonPool-worker-3] ERROR org.batfish.main.annotate.Annotate - Failed to parse: /home/ubuntu/projects/scripts/batfish/configs/panos/configs/xyz.cfg

any idea how to see why they fail?

**Comment by dhalperi** [comment]
@arifogel - I've never seen this before. Any idea how to debug?

**Comment by kmjmartin** [comment]
Hi @dhalperi
found the issue was being caused by freestyle descriptions and comments, and was able to parse configs after stripping those out.
The descriptions could include quotes or semi colons within the quotes that are in the show command output. E.g something like
- description "this firewall rule created in change "12345"";
etc
