### ISSUE TITLE
Invalid container use in RoutesQuestionPlugin

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#719]
Inside pretty-printing, so likely not that harmful.

https://github.com/batfish/batfish/blob/d503834def99ee16880c6135aaeeaf39f7929cd8/projects/question/src/main/java/org/batfish/question/RoutesQuestionPlugin.java#L282-L294

`_added` cannot contain objects of type `AbstractRoute`

**Comment by dhalperi** [comment]
This bug is still present. @progwriter I know you may be looking at `RoutesQuestionPlugin` -- maybe take a look?

**Comment by progwriter** [comment]
Will do.
