### ISSUE TITLE
How to check route items in BGP and IS-IS?

### ISSUE THREAD

**Issue by kefins** [batfish/batfish#7239]
Hi, 

We're running Batfish on a number of core Cisco network devices, and we configured BGP and IS-IS on some nodes at the same time. 
We found some issues while executing verification of traceroute, and we thought the reason was that the node playing BGP reflactor had no BGP route items which were overlapped by IS-IS route items, this was because IS-IS route items had higher priority. And it would cause the reflactor did not send BGP routes to its clients. 
So I wonder if there is some interfaces to obtain BGP routes and IS-IS routes respectively. Just as what we get when implementing following commands in IOS.

as100border1# **show ip bgp ipv4 unicast**
BGP table version is 8457, local router ID is 2.2.2.2
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal,
              r RIB-failure, S Stale
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight Path
*> 2.2.2.2/32       0.0.0.0                  0         32768 i
r>i3.3.3.3/32       3.3.3.3                  0    100      0 i
*>i4.4.4.4/32       3.3.3.3                  0    100      0 200 i
as100border1#
as100border1# **show isis rib**

Thanks.

**Comment by kefins** [comment]
I have found the interface that I want in pybatfish doc

**Comment by dhalperi** [comment]
Awesome, thanks!
