### ISSUE TITLE
FRR: Missing `allowas-in` command

### ISSUE THREAD

**Issue by ton31337** [batfish/batfish#7680]
http://docs.frrouting.org/en/stable-8.0/bgp.html#clicmd-neighbor-A.B.C.D-X-X-X-X-WORD-allowas-in-1-10-origin

```
    Accept incoming routes with AS path containing AS number with the same value as the current system AS.

    This is used when you want to use the same AS number in your sites, but you can’t connect them directly. This is an alternative to neighbor WORD as-override.

    The parameter (1-10) configures the amount of accepted occurences of the system AS number in AS path.

    The parameter origin configures BGP to only accept routes originated with the same AS number as the system.

    This command is only allowed for eBGP peers.
```

Examples: 
```
neighbor 10.10.10.1 allowas-in
neighbor 10.10.10.1 allowas-in 3
```

**Comment by ratulm** [comment]
hey, @ton31337 - I took at look there.  Batfish has support for allowas-in but under the address-family stanza.

I did some experiments and found that FRR will indeed accept the following
```
  router bgp 1
  neighbor 1.1.1.1 remote-as 2
  neighbor 1.1.1.1 allowas-in
```

But the output of show run will produce the following canonical form:
```
router bgp 1
 neighbor 1.1.1.1 remote-as 2
 !
 address-family ipv4 unicast
  neighbor 1.1.1.1 allowas-in
 exit-address-family
```

Is it possible for you to generate the second form?

**Comment by ton31337** [comment]
The second one is the correct one (under address-family) because the first one is just for backward compatibility (a hidden command).

**Comment by ratulm** [comment]
The second one is already supported I believe. Are you seeing something different?

**Comment by ton31337** [comment]
> The second one is already supported I believe. Are you seeing something different?

Yeah, I didn't check it deep :smile:

**Comment by ratulm** [comment]
OK to close this issue?
