### ISSUE TITLE
AWS aggregates should contain other aggregates

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#769]
E.g., [this VPC](https://github.com/batfish/batfish/blob/818ecff6aa9861007b1792617ede00c357df47c4/tests/basic/topology-example-aws.ref#L21-L27) should contain all the subnet aggregates

**Comment by dhalperi** [comment]
@ratulm can you take a look? Thoughts?

**Comment by ratulm** [comment]
Not sure I understand. You suspect that the output is wrong (or, that you want the backend to recursively resolve aggregate contents)?

**Comment by ratulm** [comment]
Got it now. The way the code is currently, only nodes show up as contained entities. I'll fix.
