### ISSUE TITLE
Instructions are too vague on how to upload existing network configs into Batfish

### ISSUE THREAD

**Issue by no-good-usernames-left** [batfish/batfish#7720]
Batfish team, 
I love the concept of this app, but the instructions are too vague on how to upload my network infrastructure config into it. 

Expectation:
WebUI to upload files into the Batfish and one-click or simple queries to execute for mapping out the network 

Reality:
Vague Python playbooks with no real clear direction on how to achieve the above

**Comment by ratulm** [comment]
@no-good-usernames-left - Did you see the documentation at https://pybatfish.readthedocs.io/en/latest/getting_started.html? It has step-by-step instructions on installing/running Batfish service and interacting with it using Python. The open source version of Batfish does not have a WebUI. 

If something is unclear in the documentation, let us know and help us improve the documentation. 

Closing this issue for now; please re-open if unresolved.
