### ISSUE TITLE
antlr reuse 

### ISSUE THREAD

**Issue by bk1te** [batfish/batfish#778]
Hello is  there any possibility to reuse antlr grammars for different programming languages.
I tried to built python parser from provided grammar but there is java specific parts in it.
Here is the  [link](https://github.com/antlr/antlr4/blob/master/doc/targets.md) for different code generation targets

**Comment by ratulm** [comment]
That is not something that we've looked into and don't know if its possible to do so cleanly. If you can suggest (e.g., through a PR) a way to refactor the code for multiple targets, without impacting the Java functionality, we'd be open to it.
