### ISSUE TITLE
Batfish does not recognize prefix-list apply-path while looking for Filter Line Reachability

### ISSUE THREAD

**Issue by rugvedapande** [batfish/batfish#7782]
Here is example of an output when Filter Line Reachability is used on a router snapshot. 

```
Found unreachable filter line(s), when none were expected
                       Sources     Unreachable_Line Unreachable_Line_Action Blocking_Lines Different_Action                     Reason Additional_Info
0  ['router1: FAKE_ACL']   fake_term1                  PERMIT             []            False  INDEPENDENTLY_UNMATCHABLE            None
1  ['router1: FAKE_ACL']  fake_term2                  PERMIT             []            False  INDEPENDENTLY_UNMATCHABLE            None
Unreachable lines =  False
```

Notice that it says
Reason Additional_Info

I have also noticed that batfish works for apply-path used in this prefix list
`set policy-options prefix-list match-interface_ips apply-path "interfaces <*> unit <*> family inet address <*>"`
But does not work for this prefix list
`set policy-options prefix-list match-peers apply-path "protocols bgp group <*> neighbor <*>"`

Both prefix lists are matching IPs, I checked with "display inheritance" command.

**Comment by dhalperi** [comment]
Hi @rugvedapande , can you confirm that there are IPv4 neighbors? If there are not any, then the prefix list will be considered empty for the purposes of an IPv4 ACL.

**Comment by dhalperi** [comment]
Hi @rugvedapande - did you see the question above?

**Comment by dhalperi** [comment]
Hi @rugvedapande - did you see the question above?

We will close this issue in 1 week if not.
