### ISSUE TITLE
Support for partial topology input

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#781]
Batfish currently doesn't allow the user to partially specifying the topology as an input. If a topology file is present, then it is assumed (and required) to be correct and complete. 

Batfish should use the topology provided as merely an input into the topology computation process. The computed topology should be merged with the provided one in order to construct a complete picture. Any edges that are "disputed", where the provided topology and computed topology are different should be surfaced so the user can take appropriate action.

A use-case for this is when a user provides Batfish with the physical connectivity for the part of the network that has Layer 2 switches, so that Batfish can accurately reason about link failures.

**Comment by progwriter** [comment]
We no longer take L3 topology as input. 
We *do* support partial L1 topology as input. 
@saparikh can this be closed?

**Comment by saparikh** [comment]
Yes, this can be closed. There are probably still cases of partial input that we don't handle, but we can file those as they arise.
