### ISSUE TITLE
Reachability does not take VLANs into account

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#783]
Given the configuration below... I would expect communications to fail from `r1:eth0` to `r2:eth0`... I haven't tried it on a 'real' network, but batfish is storing the VLAN information internally.

hosts/r1.cfg

```
interface eth1
  ip address 10.0.1.1/24
!
interface eth0
  ip address 10.0.0.1/24
  switchport access vlan 5
!
router ospf 1
  router-id 10.0.1.1
  network 10.0.1.0/24 area 0
  network 10.0.0.0/24 area 0
!
```

hosts/r2.cfg

```
interface eth1
  ip address 10.0.2.1/24
!
interface eth0
  ip address 10.0.0.2/24
  switchport access vlan 6
!
router ospf 1
  router-id 10.0.2.1
  network 10.0.2.0/24 area 0
  network 10.0.0.0/24 area 0
!
```

hosts/n1.json

```
{
  "hostname": "n1",
  "hostInterfaces": {
    "eth0": {
      "name": "eth0",
      "prefix": "10.0.1.10/24",
      "gateway": "10.0.1.1"
    }
  }
}
```

hosts/n2.json

```
{
  "hostname": "n2",
  "hostInterfaces": {
    "eth0": {
      "name": "eth0",
      "prefix": "10.0.2.10/24",
      "gateway": "10.0.2.1"
    }
  }
}
```

And the traceroute question + results:

```
Question: traceroute ingressNode=n1, dstIp=10.0.2.10, srcIp=10.0.1.10
... 

    Hop 1: n1:eth0 -> r1:Ethernet1 --- [StaticRoute<0.0.0.0/0,nhip:10.0.1.1,nhint:eth0>_fnhip:10.0.1.1]
    Hop 2: r1:Ethernet0 -> r2:Ethernet0 --- [OspfIntraAreaRoute<10.0.2.0/24,nhip:10.0.0.2,nhint:dynamic>_fnhip:10.0.0.2]
    Hop 3: r2:Ethernet1 -> n2:eth0 --- [ConnectedRoute<10.0.2.0/24,nhip:AUTO/NONE(-1l),nhint:Ethernet1>_fnhip:null]
    ACCEPTED
```

And you can see that r1 has a vlan configuration associated with it:

```
get nodes summary=false,nodeRegex=r1

...

      "interfaces" : {
        "Ethernet0" : {
          "name" : "Ethernet0",
          "accessVlan" : 5,
          "active" : true,
          "allPrefixes" : [
            "10.0.0.1/24"
          ],
          "autostate" : true,
          "bandwidth" : 1.0E9,
          "isisL1InterfaceMode" : "unset",
          "isisL2InterfaceMode" : "unset",
          "mtu" : 1500,
          "nativeVlan" : 1,
          "ospfArea" : 0,
          "ospfCost" : 1,
          "ospfDeadInterval" : 0,
          "ospfEnabled" : true,
          "ospfHelloMultiplier" : 0,
          "ospfPassive" : false,
          "ospfPointToPoint" : false,
          "prefix" : "10.0.0.1/24",
          "proxyArp" : false,
          "ripEnabled" : false,
          "ripPassive" : false,
          "spanningTreePortfast" : false,
          "switchportMode" : "ACCESS",
          "switchportTrunkEncapsulation" : "DOT1Q",
          "type" : "PHYSICAL",
          "vrf" : "default"
        },

``

**Comment by virtuald** [comment]
I ran a simple topology through GNS3 and was able to set a set of similar nodes working. I set the link that connects the two routers to a particular VLAN, and pinging between hosts worked. Then I changed the VLAN ID for one of the interfaces, and ping stopped working. When I ran the configs through batfish, batfish claimed that the two hosts could reach each other.

Interestingly, the Cisco CSR1000v stores it's vlan configuration a bit differently than what I had originally expected, so batfish doesn't even store the right vlan information in the vendor independent model. Here's what the interface configuration looks like:

```
interface GigabitEthernet2
 no ip address
 negotiation auto
 no mop enabled
 no mop sysid
!
interface GigabitEthernet2.1
 encapsulation dot1Q 23
 ip address 10.0.0.2 255.255.255.0
!
```

A full testrig with configurations is attached: [vlan.tar.gz](https://github.com/batfish/batfish/files/1573352/vlan.tar.gz)

From that experiment, I assume that batfish does not take vlans into account when computing reachability. Is that on the roadmap?

**Comment by ratulm** [comment]
@arifogel, can you take a look at this issue?

**Comment by arifogel** [comment]
This is important functionality, but we don't know when we will be able to take it on.

Some context:
Batfish used to take VLANs into account for computing layer-3 adjacencies, back when LogicBlox was used for data plane computation.
Unfortunately that code was never ported. A quick reference check on the `getNativeVlan()` and `getAllowedVlans()` methods of `Interface` shows that this information is only used for turning off VLANs with no underlying interfaces.
Other than that, VLAN interfaces themselves are treated like any other interface, and the underlying physical interfaces do not currently take part in data plane analysis.

In order to include VLANs and their underlying physical interfaces in reachability analysis, a few things need to happen:
1. The PHYSICAL topology must be manually provided with the testrig to prevent automatically making adjacencies for each interface in the same subnet.
2. Effective layer-3 adjacencies (like adjacencies between VLAN interfaces) will need to be considered separately from physical layer-2 adjacencies (which at the moment we mostly just invent based on subnets).
3. Reachability packet relations (see my comments in #112) need to be implemented with this distinction in mind.

If you want to take this on, I can at least supply you with the old `LogicBlox` datalog code we had for VLAN adjacencies as a starting point.

Let me know if you need any help.

**Comment by jkhourybbn** [comment]
@arifogel @ratulm we would like to help get this going but this will require your direct support. 

There are a couple tickets here #201, #887, and #783 that are bumping against the lack of layer 2 support. Do we want to discuss what sort of Layer 2 capabilities we want/care to model so we have a clean design before we take on pieces?

Here is are some of the basic features I think are lacking now, and some thoughts
 
 * if we have a layer 2 switch (managed or unmanaged), it is ignored. Layer 3 adjacencies are inverted from subnets, so all nodes on a subnet are connected in a mesh. We are not able to describe the actual physical topology even by passing a topology file (#201). This for example leads to an explosion in the number of "edges" O(n^2) and the size of the corresponding logic formula

 * VLAN behavior is ignored. Perhaps we can account for VLANs by pre-processing the layer 2 configs, creating the right layer 3 adjacencies, and then simulating that and encoding the resulting data plane? Is this what you meant in your comment (2)?

**Comment by ratulm** [comment]
It looks like the right way to do this would be model L2 properly.  I believe this shouldn't be that hard because we used to do that (and because of some recent changes). 

@arifogel - can you point @jkhourybbn to the old code as a reference?

**Comment by dimbleby** [comment]
Hi, 

Just checking batfish out... is the status of this issue still as per February's comments?  Which I understand as being:

* L2 support would certainly be desirable
* it's not there today
* there's no fundamental block to this, it 'just' needs someone to do the work

Thanks!

**Comment by ratulm** [comment]
Hey, @dimbleby - Yes, fortunately and unfortunately, all of that is still correct.

**Comment by dhalperi** [comment]
As of now, given a proper L1 topology and L2 configuration on switches/routers, Batfish will add the transitive L3 edges (and not add L3 edges that are not on the same L2 broadcast domain).

**Comment by dhalperi** [comment]
For more information on L1 topology, see https://github.com/batfish/batfish/wiki/Packaging-snapshots-for-analysis#format-for-the-topology-file-experimental
