### ISSUE TITLE
Regex error when using searchRoutePolicies 

### ISSUE THREAD

**Issue by djbabar** [batfish/batfish#7973]
Running through the routing example using Juniper config gives a regex error. When using testRoutePolicies I don't see an issue.

Here's the code I was using:

`# Verify that no route for our address space is ever denied by to_provider policies
    ownedSpace = ["1.2.3.0/24", '1.2.4.0/24']
    inRoutes4 = BgpRouteConstraints(prefix=ownedSpace)
    result = bf.q.searchRoutePolicies(policies="export-to-isps",
                                      inputConstraints=inRoutes4,
                                      action="deny").answer().frame()
    show(result)
`

Believe this is the part of the config it's not happy with, have uploaded router2.txt to reproduce the issue.

`as-path Microsoft .*8075.*;`

Error:
`Caused by: org.batfish.common.BatfishException: Failed to answer question
	at org.batfish.main.Batfish.answer(Batfish.java:652)
	... 3 more
Caused by: org.batfish.common.BatfishException: Regex ^( \d+)* 8075( \d+)*$ does not match any strings`

[router2.txt](https://github.com/batfish/batfish/files/7960774/router2.txt)

**Comment by ratulm** [comment]
@millstein - are you able to take a look at this?

SRP doesn't work for everything, but this error message is odd: `Regex ^( \d+)* 8075( \d+)*$ does not match any strings`

**Comment by dhalperi** [comment]
Recalling that (I believe) all strings are prepended with ` ` when matched against regex, this seems like it should work.

**Comment by millstein** [comment]
This issue is resolved by the recent PRs #7977 and #7984
