### ISSUE TITLE
4 Bytes ASN not supported in Route-map

### ISSUE THREAD

**Issue by BouchardClaude** [batfish/batfish#8009]
I look like 4 Bytes ASN support was added but not for route map.
Example that will fail the device parsing (ARISTA  or CISCO at least) is :

```
route-map TEST permit 10
   match ip address prefix-list TEST1
   set as-path prepend 4294967294 4294967294
```

Device will parse if 4 bytes AS is in the bgp configuration, but not in a route-map

**Comment by dhalperi** [comment]
@BouchardClaude specific list of operating systems, please?

**Comment by dhalperi** [comment]
Also, are there any global configuration options that change how ASNs are handled or displayed in your configs?

Ideally, just share a full config with the issue (anonymized with [netconan](https://github.com/intentionet/netconan) is okay).

**Comment by BouchardClaude** [comment]
I just looked at your commit and I think you understood the issue :)  will let know as soon as I can test it so we can close this one.
