### ISSUE TITLE
Feature request: Cisco IOS BGP as-path replace command support

### ISSUE THREAD

**Issue by kefins** [batfish/batfish#8059]
Hi, I got some warning while parsing Cisco IOS snapshot, here is the detail warning.
```bash
>>> bfq.initIssues().answer().frame()
status: TRYINGTOASSIGN
.... no task information
status: TERMINATEDNORMALLY
.... 2022-02-16 16:04:29.108000+08:00 Begin job.
  Nodes                                                                                         Source_Lines           Type                                  Details                           Line_Text                                                                                       Parser_Context
0  None                                                                   [configs/100.127.131.94.cfg:[550]]  Parse warning              This syntax is unrecognized           set as-path replace 65031                                [set_rm_stanza rm_stanza route_map_stanza stanza cisco_configuration]
1  None                                                                   [configs/100.127.131.95.cfg:[556]]  Parse warning              This syntax is unrecognized           set as-path replace 65032                                [set_rm_stanza rm_stanza route_map_stanza stanza cisco_configuration]
2  None  [configs/11.240.108.181.cfg:[1020, 1025, 1030, 1035, 1042, 1047], configs/11.240.107.51.cfg:[102...  Parse warning              This syntax is unrecognized           set as-path replace 65010                                [set_rm_stanza rm_stanza route_map_stanza stanza cisco_configuration]
3  None                                [configs/11.240.108.181.cfg:[1147], configs/11.240.107.51.cfg:[1147]]  Parse warning              This syntax is unrecognized   maximum-paths eibgp as-path-relax  [dec maximum_paths_bgp_tail bgp_tail address_family_inner address_family_rb_stanza router_bgp_st...
4  None  [configs/11.240.108.181.cfg:[1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1...  Parse warning  This feature is not currently supported  advertise-map RP_DENY_IBGP_PEER_IP  [agg_advertise_map aggregate_address_rb_stanza address_family_inner address_family_rb_stanza rou...
5  None              [configs/11.240.108.181.cfg:[954, 959, 964], configs/11.240.107.51.cfg:[954, 959, 964]]  Parse warning              This syntax is unrecognized           set as-path replace 65313                                [set_rm_stanza rm_stanza route_map_stanza stanza cisco_configuration]
```
And the unrecognized commands are `set as-path replace 65031` and `maximum-paths eibgp as-path-relax`,  the *feature is not currently supported* command is `aggregate-address 11.20.144.0 255.255.240.0 summary-only advertise-map RP_DENY_IBGP_PEER_IP attribute-map RP_DR_OPEN_SET_COMM`.

After talking about these commands with @arifogel , who said some of them had been support on FRR. I wonder if they can be migrated to Cisco IOS.

![image](https://user-images.githubusercontent.com/41069536/154392507-b5eea930-da33-4824-bb4c-ed93b607c3ef.png)

+ set as-path replace
<img width="819" alt="企业微信截图_16450648384202" src="https://user-images.githubusercontent.com/41069536/154392868-e6b7c582-cf6a-45d2-ba64-5cb645b74ee5.png">

+ maximum-paths eibgp as-path-relax
<img width="819" alt="企业微信截图_1645064895679" src="https://user-images.githubusercontent.com/41069536/154392953-23d660c3-3323-4f1c-8fcf-5c618b447d80.png">

+ aggregate-address 11.20.144.0 255.255.240.0 summary-only
<img width="822" alt="企业微信截图_16450649649389" src="https://user-images.githubusercontent.com/41069536/154393092-39c389db-042d-4aa3-a2ec-a09fd636f573.png">

**Comment by arifogel** [comment]
@kefins Thanks for this.
- `set as-path replace` sounds like something we should be able to implement without much difficulty. IOS's version of this command is similar enough to FRR's that I think it should be a relatively simple change.
-  I believe the magic hidden IOS command you are looking for is `bgp bestpath as-path multipath-relax` at the `router bgp` level. It appears we support this. Regarding the slack thread about maximum-paths support: We simply treats the numerical argument as either `1` or `infinity`, i.e. single path or multipath.
- `aggregate-address 11.20.144.0 255.255.240.0 summary-only advertise-map RP_DENY_IBGP_PEER_IP attribute-map RP_DR_OPEN_SET_COMM`
    - this command is _mostly_ supported, but we don't support `advertise-map` at this time. More generally, Batfish currently doesn't support setting properties of aggregate routes based on a combination of properties of contributors.  Supporting this feature will require significant changes to Batfish's aggregate generation pipeline. Adding this support is not on the horizon at this time.

**Comment by kefins** [comment]
Hi, @arifogel 
May I ask when will this patch be released? I need to verify a loop which was produced by `bgp as-path replace`.

**Comment by arifogel** [comment]
Turns out it was nothing like the FRR construct, but I was able to churn out support anyhow. May take some time for review, but should be in soon.

**Comment by kefins** [comment]
OK, thank you so much.
