### ISSUE TITLE
BGP asdot is not recognized

### ISSUE THREAD

**Issue by adosztal** [batfish/batfish#8075]
Hello,

Batfish container: batfish/allinone:test-1221
pybatfish version: 2022.2.18.1216
Network device: Cisco IOS-XE (although this is probably not relevant)

I have the following BGP configuration (not relevant parts were removed):
```text
router bgp 65000
 bgp asnotation dot
 neighbor 19.211.115.35 remote-as 65000.65000
```

I get a warning during init_snapshot that Batfish can't recognize the asdot format and it's missing the remote-as for the neighbor.
__initInfo:
```json
{
	"Comment": "This syntax is unrecognized",
	"Line": 298,
	"Parser_Context": "[router_bgp_stanza_tail router_bgp_stanza stanza cisco_configuration]",
	"Text": "bgp asnotation dot"
},

{
	"Comment": "This syntax is unrecognized",
	"Line": 315,
	"Parser_Context": "[remote_as_bgp_tail neighbor_flat_rb_stanza router_bgp_stanza_tail router_bgp_stanza stanza cisco_configuration]",
	"Text": "neighbor 19.211.115.35 remote-as 65000.65000"
},

"mynode": {
	"Error details": null,
	"Parse warnings": [],
	"Pedantic complaints": [],
	"Red flags": [
		{
			"tag": "MISCELLANEOUS",
			"text": "No remote-as set for peer: 19.211.115.35"
		},
	],
	"Unimplemented features": []
},
```

**Comment by dhalperi** [comment]
Interesting - the command `bgp asnotation dot` is causing Batfish to drop out of `router bgp`. I've never seen this command in a config off a device; it's the default. I bet if you remove it, things will work.

An easy fix tho, in PR.

**Comment by adosztal** [comment]
Thank you!
