### ISSUE TITLE
Juniper SRX: parse not detecting address-set entries?

### ISSUE THREAD

**Issue by jhammond-git** [batfish/batfish#8129]
I ran into this and wasn't sure if it was a parse error or my error.

```
Source_Lines                                                      None
Type                                         Convert warning (redflag)
Details           Missing destination address-book entry 'ntp_servers'
Line_Text                                                         None
Parser_Context                                                    None
Name: 11, dtype: object
```

From the SRX in question in the destination zone:
```
> show configuration | display set | match ntp_servers
set security policies from-zone A to-zone Z policy ntp_policy_in match destination-address ntp_servers
set security policies from-zone B to-zone Z policy ntp_policy_in match destination-address ntp_servers
set security zones security-zone Z address-book address-set ntp_servers address 192.168.1.1-32

> show configuration security zones security-zone Z address-book address 192.168.1.1-32
192.168.1.1/32;
```

Please let me know if I can provide more information.

**Comment by jhammond-git** [comment]
I wonder if this is related to this old naming convention of ours - <IP>-<CIDR length>.  I seem to see a lot of parse errors on policies related to those objects.

**Comment by arifogel** [comment]
When I run these four lines:
```
set security zones security-zone Z address-book address 192.168.1.1-32 192.168.1.1/32
set security policies from-zone A to-zone Z policy ntp_policy_in match destination-address ntp_servers
set security policies from-zone B to-zone Z policy ntp_policy_in match destination-address ntp_servers
set security zones security-zone Z address-book address-set ntp_servers address 192.168.1.1-32
```
 I get only the following warnings:
```
missing action in firewall filter: 'zone~A~to~zone~Z', term: 'ntp_policy_in'
missing action in firewall filter: 'zone~B~to~zone~Z', term: 'ntp_policy_in'
```
If I add these two lines:
```
set security policies from-zone A to-zone Z policy ntp_policy_in then permit
set security policies from-zone B to-zone Z policy ntp_policy_in then permit
```
Then when I run again I get no warnings.
I suspect that the warning you are getting is either:
- from using an old version of Batfish
- related to some other part of your config

Are you using a container or building from source? Which version/commit?
Does anything else in the config jump out that you haven't pasted here?

**Comment by jhammond-git** [comment]
I installed into a fresh Ubuntu 20.04 server using these instructions: https://batfish.readthedocs.io/en/latest/getting_started.html

Cycling through more of the issues, I run into a lot of these:
```
Type                                                                                                                                             Parse warning
Details                                                                                                                            This syntax is unrecognized
Line_Text                                                         set security zones security-zone mgmt address-book address 192.168.161.0-24 192.168.161.0/24
Parser_Context    [sezsa_address sezs_address_book sez_security_zone se_zones s_security s_common statement set_line_tail set_line flat_juniper_configuration]
Name: 68, dtype: object
```
So, not that the address-set entries aren't recognized, just that the addresses within them haven't been accepted, so they end up empty.

**Comment by arifogel** [comment]
Based on the instructions you linked, you are using the latest official release container.
It is possible the the issues you are encountering have already been fixed in master since that release. Please try instead using the latest nightly build, and let me know if you still get the same warnings.

Do:
```
docker pull batfish/allinone:test-1236
docker run --name batfish -v batfish-data:/data -p 8888:8888 -p 9997:9997 -p 9996:9996 batfish/allinone:test-1236
```
Note the `:test-1236`, which refers to the allinone image built last night.

**Comment by jhammond-git** [comment]
Thank you.  I believe that did take care of it.

**Comment by dhalperi** [comment]
Thanks @jhammond-git  - we hope to make a new release real soon so you don't have to use nightly builds.
