### ISSUE TITLE
Why does traceroute returns multiple routes?

### ISSUE THREAD

**Issue by rosstex** [batfish/batfish#828]
This is more of a comment rather than an issue, but we're trying to understand how the traceroute function works. What causes traceroute to return multiple routes? Is it non-deterministic, or does it find all possible routes? How are ties broken/handled?

Thanks!

**Comment by ratulm** [comment]
It shows all possible paths that a flow can take in the network.

**Comment by rosstex** [comment]
Ah, thanks a lot for your reply! Is there an ordering to the results that will let us determine which route packets would actually take, assuming standard BGP preference ranking?

**Comment by ratulm** [comment]
All the paths that traceroute shows are equally likely and the exact one depends on the ECMP hashing at the routers. We are talking multi-path routing here. 

You are talking about BGP path selection, which (by default) picks one best path. In those case, traceroute will show just that one path. 

Is the distinction clear now?

**Comment by rosstex** [comment]
Yes! I have a much better understanding of the networks we are analyzing now.

**Comment by ratulm** [comment]
Great, closing this issue. Re-open or open another one if you have further questions.
