### ISSUE TITLE
Junos QFX vlan-id none issue

### ISSUE THREAD

**Issue by davedotdev** [batfish/batfish#8308]
I've been working with Batfish with Juniper QFX switches and I've found an issue where when vlans do not have an integer tag, Batfish doesn't list them, despite them being legit VLANs.

Some example configuration Junos set notation configuration:

```text
set interfaces irb unit 111 proxy-macip-advertisement
set interfaces irb unit 111 virtual-gateway-accept-data
set interfaces irb unit 111 family inet address 10.116.10.50/30 preferred
set interfaces irb unit 111 virtual-gateway-v4-mac 00:00:5e:01:00:01

set vlans bd-10036 description "vlan-id not working example"
set vlans bd-10036 vlan-id none
set vlans bd-10036 l3-interface irb.111
set vlans bd-10036 vxlan vni 10036
```

If I now extract the switchedVlanProperties from Batfish, the VLAN will be missing. However, if I change the tag to an arbitrary number in the accepted VLAN range, say 42, it works just fine.

I'm using the allinone docker image with tags below:
```text
"org.batfish.allinone-tag": "29a5b57_d201a58",
"org.batfish.batfish-tag": "29a5b57",
"org.batfish.batfish-version": "2022.04.06.1263"
```

Is this a bug or a feature? I suspect Batfish needs to handle this style of VLAN ID properly, but I understand with a tag of `none`, that may be problematic.

Thanks,
David

**Comment by dhalperi** [comment]
Hey David,

Hmm, interesting that JunOS still calls those VLANs. They are not VLANs on other boxes - VLAN is a pure L2 concept. (E.g., NX-OS has L3VNIs but not vlans.)

`switchedVlanProperties` only reports L2 vlans.

**Comment by davedotdev** [comment]
Hey, 

Thanks for coming back!

I get the naming thing. It's confusing. It really should be called EVPN-SIGNALLED-VLAN or something more intuitive! 

We have some ongoing development work going on with Batfish and I'll reach out to that team. It's specifically on EVPN anyway, so will figure it out in context.

If you come up with a better name than me for an EVPN fake L2 VLAN let me know!
