### ISSUE TITLE
PAN: asn 4byte asdot+

### ISSUE THREAD

**Issue by xenque2** [batfish/batfish#8346]
Can't recognize a as number with a dot (format asdot+)
https://datatracker.ietf.org/doc/html/rfc5396

```python
from pybatfish.client.session import Session
txt = """
set deviceconfig system hostname pan_testing
set network virtual-router TEST protocol bgp local-as 64976.140
"""
bf = Session()
bf.set_network("test")
bf.init_snapshot_from_text(txt, snapshot_name="pan_testing", overwrite=True)
issues = bf.q.initIssues().answer()
issues
```

**Comment by dhalperi** [comment]
Hi @xenque2 - Palo Alto Networks does not display 4-byte ASNs as dotted. Instead, you have to set a special option to turn on 4-byte ASNs, and then after that they are displayed as numbers 1-4B.

See: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClxiCAC

This is implemented in Batfish [here](https://github.com/batfish/batfish/blob/b99263c772bc18195041ec4d19687201028941a5/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L3454-L3461) and tested [here](https://github.com/batfish/batfish/blob/b99263c772bc18195041ec4d19687201028941a5/projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/bgp#L15).
