### ISSUE TITLE
assert_no_duplicate_router_ids fails with multiple VRFs on BGP - Arista

### ISSUE THREAD

**Issue by JulioPDX** [batfish/batfish#8587]
**Describe the bug and expected behavior**

When using  **assert_no_duplicate_router_ids** on Arista node, fail is reported when the same router ID is set on the default and alternate VRF in BGP configuration

**Runnable example**
```py
from pybatfish.client.commands import *
from pybatfish.question import load_questions
from pybatfish.client.asserts import assert_no_duplicate_router_ids

NETWORK_NAME = "NET"
SNAPSHOT_NAME = "snapshot00"
SNAPSHOT_DIR = "./snapshots"
bf_session.host = "localhost"
bf_set_network(NETWORK_NAME)
init_snap = bf_init_snapshot(SNAPSHOT_DIR, name=SNAPSHOT_NAME, overwrite=True)
load_questions()
assert_no_duplicate_router_ids(
    snapshot=init_snap,
    protocols={"ospf", "bgp"},
)
```

`snapshots/configs`

<details>
<summary>leaf1</summary>
<br>
<pre>
!RANCID-CONTENT-TYPE: arista
!
vlan internal order ascending range 1006 1199
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname leaf1
dns domain atd.lab
!
ntp server 192.168.0.1 iburst local-interface Management1
!
no spanning-tree vlan-id 4093-4094
!
no enable password
no aaa root
!
vlan 10
   name Tenant_A_VMOTION
!
vlan 100
   name Tenant_A_MGMT_Zone_1
!
vlan 150
   name Tenant_A_DATA_Zone_1
!
vlan 3010
   name MLAG_iBGP_Tenant_A
   trunk group LEAF_PEER_L3
!
vlan 4093
   name LEAF_PEER_L3
   trunk group LEAF_PEER_L3
!
vlan 4094
   name MLAG_PEER
   trunk group MLAG
!
vrf instance Tenant_A
!
interface Port-Channel1
   description MLAG_PEER_leaf2_Po1
   no shutdown
   switchport
   switchport trunk allowed vlan 2-4094
   switchport mode trunk
   switchport trunk group LEAF_PEER_L3
   switchport trunk group MLAG
!
interface Port-Channel4
   description host1_PortChannel
   no shutdown
   switchport
   switchport trunk allowed vlan 10,100,150
   switchport mode trunk
   mlag 4
!
interface Ethernet1
   description MLAG_PEER_leaf2_Ethernet1
   no shutdown
   channel-group 1 mode active
!
interface Ethernet2
   description P2P_LINK_TO_SPINE1_Ethernet2
   no shutdown
   mtu 1500
   no switchport
   ip address 172.31.255.9/31
!
interface Ethernet3
   description P2P_LINK_TO_SPINE2_Ethernet2
   no shutdown
   mtu 1500
   no switchport
   ip address 172.31.255.11/31
!
interface Ethernet4
   description host1_Ethernet1
   no shutdown
   channel-group 4 mode active
!
interface Ethernet6
   description MLAG_PEER_leaf2_Ethernet6
   no shutdown
   channel-group 1 mode active
!
interface Loopback0
   description EVPN_Overlay_Peering
   no shutdown
   ip address 192.168.1.5/32
!
interface Loopback1
   description VTEP_VXLAN_Tunnel_Source
   no shutdown
   ip address 192.168.54.5/32
!
interface Management1
   description oob_management
   no shutdown
   ip address 192.168.0.12/24
!
interface Vlan100
   description Tenant_A_MGMT_Zone_1
   no shutdown
   vrf Tenant_A
   ip address virtual 10.1.100.1/24
!
interface Vlan150
   description Tenant_A_DATA_Zone_1
   no shutdown
   vrf Tenant_A
   ip address virtual 10.1.150.1/24
!
interface Vlan3010
   description MLAG_PEER_L3_iBGP: vrf Tenant_A
   no shutdown
   mtu 1500
   vrf Tenant_A
   ip address 10.255.251.4/31
!
interface Vlan4093
   description MLAG_PEER_L3_PEERING
   no shutdown
   mtu 1500
   ip address 10.255.251.4/31
!
interface Vlan4094
   description MLAG_PEER
   no shutdown
   mtu 1500
   no autostate
   ip address 10.255.252.4/31
!
interface Vxlan1
   description leaf1_VTEP
   vxlan source-interface Loopback1
   vxlan virtual-router encapsulation mac-address mlag-system-id
   vxlan udp-port 4789
   vxlan vlan 10 vni 10010
   vxlan vlan 100 vni 10100
   vxlan vlan 150 vni 10150
   vxlan vrf Tenant_A vni 11
!
ip virtual-router mac-address 00:1c:73:00:dc:01
!
ip routing
ip routing vrf Tenant_A
!
ip prefix-list PL-LOOPBACKS-EVPN-OVERLAY
   seq 10 permit 192.168.1.0/24 eq 32
   seq 20 permit 192.168.54.0/24 eq 32
!
mlag configuration
   domain-id DC1_LEAF1
   local-interface Vlan4094
   peer-address 10.255.252.5
   peer-link Port-Channel1
   reload-delay mlag 300
   reload-delay non-mlag 330
!
ip route 0.0.0.0/0 192.168.0.1
!
route-map RM-CONN-2-BGP permit 10
   match ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
!
route-map RM-MLAG-PEER-IN permit 10
   description Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
   set origin incomplete
!
router bfd
   multihop interval 1200 min-rx 1200 multiplier 3
!
router bgp 65101
   router-id 192.168.1.5
   no bgp default ipv4-unicast
   distance bgp 20 200 200
   graceful-restart restart-time 300
   graceful-restart
   maximum-paths 4 ecmp 4
   neighbor EVPN-OVERLAY-PEERS peer group
   neighbor EVPN-OVERLAY-PEERS update-source Loopback0
   neighbor EVPN-OVERLAY-PEERS bfd
   neighbor EVPN-OVERLAY-PEERS ebgp-multihop 3
   neighbor EVPN-OVERLAY-PEERS send-community
   neighbor EVPN-OVERLAY-PEERS maximum-routes 0
   neighbor IPv4-UNDERLAY-PEERS peer group
   neighbor IPv4-UNDERLAY-PEERS send-community
   neighbor IPv4-UNDERLAY-PEERS maximum-routes 12000
   neighbor MLAG-IPv4-UNDERLAY-PEER peer group
   neighbor MLAG-IPv4-UNDERLAY-PEER remote-as 65101
   neighbor MLAG-IPv4-UNDERLAY-PEER next-hop-self
   neighbor MLAG-IPv4-UNDERLAY-PEER description leaf2
   neighbor MLAG-IPv4-UNDERLAY-PEER send-community
   neighbor MLAG-IPv4-UNDERLAY-PEER maximum-routes 12000
   neighbor MLAG-IPv4-UNDERLAY-PEER route-map RM-MLAG-PEER-IN in
   neighbor 10.255.251.5 peer group MLAG-IPv4-UNDERLAY-PEER
   neighbor 10.255.251.5 description leaf2
   neighbor 172.31.255.8 peer group IPv4-UNDERLAY-PEERS
   neighbor 172.31.255.8 remote-as 65100
   neighbor 172.31.255.8 description spine1_Ethernet2
   neighbor 172.31.255.10 peer group IPv4-UNDERLAY-PEERS
   neighbor 172.31.255.10 remote-as 65100
   neighbor 172.31.255.10 description spine2_Ethernet2
   neighbor 192.168.1.1 peer group EVPN-OVERLAY-PEERS
   neighbor 192.168.1.1 remote-as 65100
   neighbor 192.168.1.1 description spine1
   neighbor 192.168.1.2 peer group EVPN-OVERLAY-PEERS
   neighbor 192.168.1.2 remote-as 65100
   neighbor 192.168.1.2 description spine2
   redistribute connected route-map RM-CONN-2-BGP
   !
   vlan 10
      rd 192.168.1.5:10010
      route-target both 10010:10010
      redistribute learned
   !
   vlan 100
      rd 192.168.1.5:10100
      route-target both 10100:10100
      redistribute learned
   !
   vlan 150
      rd 192.168.1.5:10150
      route-target both 10150:10150
      redistribute learned
   !
   address-family evpn
      neighbor EVPN-OVERLAY-PEERS activate
   !
   address-family ipv4
      no neighbor EVPN-OVERLAY-PEERS activate
      neighbor IPv4-UNDERLAY-PEERS activate
      neighbor MLAG-IPv4-UNDERLAY-PEER activate
   !
   vrf Tenant_A
      rd 192.168.1.5:11
      route-target import evpn 11:11
      route-target export evpn 11:11
      router-id 192.168.1.5
      neighbor 10.255.251.5 peer group MLAG-IPv4-UNDERLAY-PEER
      redistribute connected
!
management api http-commands
   protocol https
   no shutdown
   !
   vrf default
      no shutdown
!
no aaa root
!
username admin privilege 15 role network-admin secret 5 $1$5O85YVVn$HrXcfOivJEnISTMb6xrJc.
username arista privilege 15 role network-admin secret 5 $1$4VjIjfd1$XkUVulbNDESHFzcxDU.Tk1
username arista ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAJXG/amD7nd3lDC2B6HeUlS0obuPc0app9sHMzY+jpoJfNlOv7z0/mxIrHjP1JG7l72+DZ9nC/VEgz7AunNCmZN6Rns+wRtUuO20JtF2d5m/+3NGFPL4Cnv/P9j6mAt077v28gBDwdbOX6r7/8K9xkk24lkGd27UhW54hqHzgViDSY+1C/gEfIM53nAVsDPnNqHmIqtxJ/IoMZB70G77vtgZkhSJ34C/6M17fgV7kH+XFA++8zbex69vkia/ZHh/gVcNT3mqGgXSCKP79wqaCDkY8coAfBFn1+WhN8vX92imhYRxR57QG5VIGrVcLL/BKHUH8Xx4KneCxC3aVxgqL arista@ansible-2022-1-5707e42b
!
daemon TerminAttr
  exec /usr/bin/TerminAttr -disableaaa -cvaddr=192.168.0.5:9910 -taillogs -cvauth=key,atd-lab -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  no shutdown
!
radius-server host 192.168.0.1 key 7 0207165218120E
!
aaa group server radius atds
  server 192.168.0.1
!
aaa authentication login default group atds local
aaa authorization exec default group atds local
aaa authorization commands all default local
!
ip radius source-interface Management1
!

!
end
</pre>
</details>

```shell
pybatfish.exception.BatfishAssertException: Found duplicate router-id(s), when none were expected
BGP:     Node       VRF    Router_ID Confederation_ID Confederation_Members Multipath_EBGP Multipath_IBGP Multipath_Match_Mode                                                                        Neighbors Route_Reflector Tie_Breaker
0  leaf1   default  192.168.1.5             None                  None           True           True          PATH_LENGTH  ['10.255.251.5', '172.31.255.8', '172.31.255.10', '192.168.1.1', '192.168.1.2']           False   ROUTER_ID
1  leaf1  Tenant_A  192.168.1.5             None                  None          False          False          PATH_LENGTH                                                                 ['10.255.251.5']           False   ROUTER_ID

```

**Comment by arifogel** [comment]
This is a pybatfish bug, not a batfish bug.
I filed https://github.com/batfish/pybatfish/issues/863 with a reference to this issue.

**Comment by arifogel** [comment]
This pybatfish PR: https://github.com/batfish/pybatfish/pull/875
will add an option `ignore_same_node` to `assert_no_duplicate_router_ids` you can use to avoid flagging duplicate router IDs across VRFs of the same node.
