### ISSUE TITLE
frr

### ISSUE THREAD

**Issue by xtz1826277** [batfish/batfish#8697]
I want to use pybatfish to directly read the FRR configuration file. How to change the device to ‘cumulus’

**Comment by dhalperi** [comment]
Assemble the data as described in #8696. Can you explain what you've tried and why it didn't work?

**Comment by dhalperi** [comment]
Did you follow the instruction I linked you in the prior issue for assembling the configuration file?

**Comment by dhalperi** [comment]
Follow the script given there. If you're not on cumulus, you can omit the `ports.conf` bits but you need the hostname, the sentinel comments, etc.

**Comment by xtz1826277** [comment]
1 hostname (single line)
 2 Contents of /etc/network/interfaces file
 3Contents of /etc/cumulus/ports.conf file
 4 Contents of /etc/frr/frr.conf file
I used these four combinations in one file. But I don't have 2, 3, only 1, 4

**Comment by dhalperi** [comment]
Did you include the comments that the script produces?

**Comment by xtz1826277** [comment]
hostname=$(cat /etc/hostname)
(
  # hostname
  echo $hostname

  # Signal start of /etc/network/interfaces
  echo "# This file describes the network interfaces"
  cat /etc/network/interfaces
  echo 

  # Signal start of /etc/cumulus/ports.conf
  echo "# ports.conf --"
  cat /etc/cumulus/ports.conf
  echo 

  # Signal start of /etc/frr/frr.conf
  echo "frr version"
  cat /etc/frr/frr.conf
  echo
) > $hostname.cfg

Sorry, I don't understand the meaning of this. I just put their content in a configuration file,like this 
frr version 7.2-sonic
frr defaults traditional
hostname r0
interface lo
 ip address 129.6.121.171/32
!
interface r0-eth0
 ip address 150.226.128.1/18
!
interface r0-eth1
 ip address 179.35.14.129/25

**Comment by dhalperi** [comment]
Here's an example from Batfish unit tests: https://github.com/batfish/batfish/blob/master/projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/bgp-passive/configs/frr-active
