### ISSUE TITLE
Questions for AWS

### ISSUE THREAD

**Issue by pomint** [batfish/batfish#8731]
Are there any questions to perform AWS configuration analysis?
i have been hitting the following error when attempting to perform analysis on AWSS configurations

Traceback (most recent call last):
  File "/home/kali/Desktop/BF Analysis/network analyzer.py", line 100, in <module>
    main()
  File "/home/kali/Desktop/BF Analysis/network analyzer.py", line 49, in main
    subnets = bfq.awsSubnetProperties().setRegion(region).setVpcId(vpc_id).answer().frame()
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pybatfish.question.bfq' has no attribute 'awsSubnetProperties'

**Comment by ratulm** [comment]
Where did you get this command: `bfq.awsSubnetProperties().setRegion(region).setVpcId(vpc_id).answer().frame()`? (Was it ChatGPT?) 

It is not valid Pybatfish command. See documentation at https://pybatfish.readthedocs.io/en/latest/questions.html or code examples at https://pybatfish.readthedocs.io/en/latest/public_notebooks.html

**Comment by pomint** [comment]
yes, it was ChatGPT
