### ISSUE TITLE
Change all AWS representations in Batfish to use Jackson instead of Jettison

### ISSUE THREAD

**Issue by haverma** [batfish/batfish#875]
This corresponds to all the classes in `org.batfish.representation.aws`

**Comment by dhalperi** [comment]
I might offer up an alternative: switch to the AWS S3 libraries and data entities. They're compatibly licensed, and presumably Amazon can keep them up to date better than we can.

(He says, hopefully.)

**Comment by dhalperi** [comment]
https://github.com/aws/aws-sdk-java

**Comment by dhalperi** [comment]
This was kind of crap, but here's code that uses the AWS SDK to build up the entity for us:

```java
  @Test
  public void testAwsDeserialize() throws Exception {
    String text =
        CommonUtil.readResource("org/batfish/representation/aws/ElasticsearchDomainTest.json");
    JsonParser p = BatfishObjectMapper.mapper().readTree(text).traverse();
    DescribeElasticsearchDomainsResponseUnmarshaller unmarshaller =
        DescribeElasticsearchDomainsResponseUnmarshaller.getInstance();
    DescribeElasticsearchDomainsResponse resp =
        unmarshaller.unmarshall(
            new JsonUnmarshallerContextImpl(p, JSON_SCALAR_UNMARSHALLERS, null));
    System.err.println(resp);
  }
```

This code was in ElasticsearchDomainTest.java

**Comment by progwriter** [comment]
@ratulm You were in this part of the code recently: is there a status update?

**Comment by ratulm** [comment]
Done here: https://github.com/batfish/batfish/pull/4301

Didn't know that i was closing an open issue :)
