### ISSUE TITLE
service-policy command not recognized under vlan configuration NXOS

### ISSUE THREAD

**Issue by jaswant6068** [batfish/batfish#8760]
**Describe the bug and expected behavior**
A clear and concise description of what the bug is and what you expect to happen instead.

**Runnable example**
```py
from pybatfish.client.session import Session
TXT = """
hostname device03
boot nxos bootflash:/nxos.9.3.11.bin

interface loopback0
 ip address 1.1.1.1/32

policy-map type qos qos-classify-lan
 class class-default
 set dscp 0

vlan configuration 100
 service-policy type qos input qos-classify-lan
"""

bf = Session()
bf.set_network("github-bug-report")
bf.init_snapshot_from_text(TXT)
# Verify that Batfish recognized the vendor format correctly
print(bf.q.fileParseStatus().answer())
          Nodes Source_Lines          Type   Details          Line_Text          Parser_Context

0        None  [configs/device03.cfg:[15]] Parse warning         This syntax is unrecognized          service-policy type qos input qos-classify-lan          [vlan_configuration s_vlan statement cisco_nxo...

print(bf.q.initIssues().answer())
```
File_Name    Status File_Format  Nodes

0        configs/device03.cfg          PARTIALLY_UNRECOGNIZED          CISCO_NX   ['device03']

**Comment by dhalperi** [comment]
Thanks! Just to make sure I understand, you want to get proper reference tracking for these qos policies?

**Comment by jaswant6068** [comment]
I am tracking unused references in network configuration presented for review and because this command is not recognized, batfish marks "qos-classify-lan" policy map as unused which is false indicator. So I am hoping that once this command is recognized, batfish will understand that this policy map is in use.

 

Structure_Type       Structure_Name      Source_Lines

0        policy-map type qos qos-classify-lan       configs/device03.cfg:[9, 10, 11, 12]


    On Thursday, July 27, 2023 at 02:14:46 PM EDT, Dan Halperin ***@***.***> wrote:  
 
 


Thanks! Just to make sure I understand, you want to get proper reference tracking for these qos policies?

**Comment by jaswant6068** [comment]
I am tracking unused references in network configuration presented for review and because this command is not recognized, batfish marks "qos-classify-lan" policy map as unused which is false indicator. So I am hoping that once this command is recognized, batfish will understand that this policy map is in use.

 

Structure_Type       Structure_Name      Source_Lines

0        policy-map type qos qos-classify-lan       configs/device03.cfg:[9, 10, 11, 12]

**Comment by jaswant6068** [comment]
print(bf.q.unusedStructures().answer())

        Structure_Type    Structure_Name                Source_Lines

0  policy-map type qos  qos-classify-lan  configs/config:[9, 10, 11]
