### ISSUE TITLE
Juniper apply-groups subtleties

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#8818]
Evolving understanding, but here's my belief:

1. Junos `apply-groups` typically don't override full config, e.g., `interfaces <*> mtu 1234` would not override `interface xe-0/0/0 unit 0 mtu 1500`
2. We saw an `apply-group` trying to add a final default deny:

    ```
    default-deny-template {
        security {
            policies {
                from-zone <*> to-zone <*> {
                    policy default-deny {
                        match {
                            source-address any;
                            destination-address any;
                            application any;
                        }
                        then {
                            deny;
                        }
                    }
                }
            }
        }
    }
    ```

    it seems logical that this config from a real device is putting this at the end.

We need to dig into this behavior. IIUC, the way that Batfish currently models apply-groups can't support both of these at once.

**Comment by saidvandeklundert** [comment]
This can be applied to a Juniper configuration as follows:
```
set groups default-deny-template security policies from-zone <*> to-zone <*> policy default-deny match source-address any
set groups default-deny-template security policies from-zone <*> to-zone <*> policy default-deny match destination-address any
set groups default-deny-template security policies from-zone <*> to-zone <*> policy default-deny match application any
set groups default-deny-template security policies from-zone <*> to-zone <*> policy default-deny then deny
set groups default-deny-template security policies from-zone <*> to-zone <*> policy default-deny then log session-init
set apply-groups default-deny-template
```

The behavior of this configuration is that this policy is additive to the list of policies already defined. Using a `show configuration security policies from-zone x to-zone x  | display inheritance` will show you how this expands.
