### ISSUE TITLE
Capability to display new flows that will be accepted in a differential analysis

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#891]
There are 2 types of differential reachability analysis that is interesting when comparing the current network configuration and proposed network configuration:

1) What flows will no longer be carried. This is implemented via reducedReachability()
2) What flows will now be carrier. For this, we need a new check expandedReachability()
     - it should be possible to implement this by simply inverting the setting of baseTestRig and deltaTestRig in relation to the reducedReachability() check.

**Comment by dhalperi** [comment]
Differential reachability captures both directions now.
