### ISSUE TITLE
Unexpectedly High Number of VLANs for Node in aristaevpn snapshot

### ISSUE THREAD

**Issue by amar-ox** [batfish/batfish#9044]
**Description:**
While running Batfish with the snapshot aristaevpn as used in the documentation, Batfish produced an unexpectedly high number of VLANs for a node. Example, for the node dc1-svc3a, Batfish generated 4086 VLANs ranging from VLAN ID 1 to 4092. However, the VLANs that are actually declared in the snapshot (120, 130, 140, 3001, 3002, 3003, 4093, and 4094) and not present in the VLAN dataframe.

**Runnable example**
```py
import requests
import os
from pybatfish.client.session import Session

SNAPSHOT_URL = "https://github.com/user-attachments/files/15539543/aristaevpn.zip"
SNAPSHOT_PATH = "aristaevpn.zip"
SNAPSHOT_NAME = "aristaevpn"

response = requests.get(SNAPSHOT_URL)

if response.status_code == 200:
    # Save the file to the local path
    with open(SNAPSHOT_PATH, 'wb') as file:
        file.write(response.content)

bf = Session(host="localhost")


bf.set_network("github-bug-report")
bf.init_snapshot(SNAPSHOT_PATH, name=SNAPSHOT_NAME, overwrite=True)

# Verify that Batfish recognized the vendor format correctly
print(bf.q.fileParseStatus().answer())

# Insert command(s) below to demonstrate the problem
vlans = bf.q.switchedVlanProperties(nodes=nodes).answer().frame()[['Node', 'VLAN_ID']]
vlans = vlans[vlans['Node'] == 'dc1-svc3a']
vlans      # about 4k Vlans are displayed
```

**Comment by dhalperi** [comment]
Hi @amar-ox - I think you are wrong here. Unmentioned VLANs are still valid in the configuration – for example, trunk will allow them. It's just that the mentioned ones have different behavior.

**Comment by dhalperi** [comment]
```
interface Port-Channel3
   description MLAG_PEER_DC1-SVC3B_Po3
   switchport trunk allowed vlan 2-4094
   switchport mode trunk
   switchport trunk group LEAF_PEER_L3
   switchport trunk group MLAG
!
```

On the mentioned `dc1-svc3a`. Are you saying this interface doesn't in fact allow vlan 2, say?

**Comment by dhalperi** [comment]
Digging in more, what do you mean by `However, the VLANs that are actually declared in the snapshot (120, 130, 140, 3001, 3002, 3003, 4093, and 4094) and not present in the VLAN dataframe.`? I see 4094 entries in the result, and here's the row for 120:

<img width="1279" alt="Screenshot 2024-10-18 at 8 49 26 AM" src="https://github.com/user-attachments/assets/5ed34c25-afc6-4c1e-b6d8-d56d448d37f0">

Here's the code:
```py
from pybatfish.client.session import Session
import pandas as pd
pd.set_option('display.max_colwidth', 200)
#
bf = Session()
#
ss = bf.init_snapshot('/Users/dhalperi/Downloads/aristaevpn/')
svc3a = bf.q.switchedVlanProperties(nodes='dc1-svc3a').answer().frame()
# Confirm that all valid vlans (1-4094) are in the result.
set(svc3a.VLAN_ID) == set(range(1,4095))
# Pull up the entry for vlan 120.
svc3a[svc3a.VLAN_ID == 120]
```

**Comment by amar-ox** [comment]
@dhalperi you're right. I was expecting to find only the named vlans in the table instead of all the 4094 (Maybe I missed that in the documentation). For the declared vlans, I remember I didn't find them in the table, but I checked now and they are effectively there. My apologies for the confusion.
