### ISSUE TITLE
Two questions on extending support for a new vendor configuration format and enhancing the knowledge base for checking rules

### ISSUE THREAD

**Issue by Zephyruswind** [batfish/batfish#9191]
1. What is the process for extending Batfish to support a new vendor configuration format or syntax, such as that of the Ericsson Router 6000?
2. Is there an extendable knowledge base in Batfish for defining checking rules or best practice guidelines?

Thank you.

**Comment by dhalperi** [comment]
1/ Please read https://github.com/batfish/batfish/tree/master/docs/parsing
2/ Please check out https://pybatfish.readthedocs.io/en/latest/questions.html and https://pybatfish.readthedocs.io/en/latest/asserts.html . More often, the "best practices" are built on top of questions as in those assertion helpers -- there's essentially no rule that's universal across networks.
