### ISSUE TITLE
Error handling: user input topology file

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#922]
If a user provides a topology file that has nodes that are not present in the testrig, Batfish will raise and exception and crash.

```
Parsing: "testrigs/tr_4a446564-ff5b-4b08-afa2-82f88327d37f/testrig/topology.net" ...Time taken for this task: 0.005 seconds
Testrig:tr_4a446564-ff5b-4b08-afa2-82f88327d37f in container:test has topology fileorg.batfish.common.BatfishException: Topology contains a non-existent node 'router_blah'
        at org.batfish.main.Batfish.checkTopology(Batfish.java:267)
        at org.batfish.main.Batfish.serializeIndependentConfigs(Batfish.java:3946)
        at org.batfish.main.Batfish.run(Batfish.java:3706)
        at org.batfish.main.Driver$2.run(Driver.java:563)
```

Batfish should support the user providing a topology file that has nodes that are not present in the testrig. The extra nodes should be called out in the log file.

Similarly if a node(s) in the testrig is missing from the provided topology, a warning should be generated and Batfish should augment the user supplied topology with the computed topology for the missing node(s)

**Comment by ratulm** [comment]
@sfraint - another user input vulnerability, which I am not sure if its still relevant. please close if not.

**Comment by dhalperi** [comment]
(NB: not a vulnerability in the security sense, just in the might crash sense)

**Comment by sfraint** [comment]
No longer an issue - fixed in https://github.com/batfish/batfish/pull/1808 (now filtering out invalid connections in `TopologyUtil.java`->`computeLayer1Topology`)
