### ISSUE TITLE
Non-CIDR subnet masks incompatible with Batfish flow analysis? v2024

### ISSUE THREAD

**Issue by gabdwr** [batfish/batfish#9230]
Hi team,

Perhaps this is an innocuous question but is Batfish v2024 known to be incompatible with non-CIDR subnet masks in ACL entries?

Inital ACL config (redacted lol):

        700 permit ip 20.21.22.23/27 1.2.3.4 255.255.255.224
        1500 deny ip any 20.0.0.0/8

I changed this to:

        700 permit ip 20.21.22.23/27 1.2.3.4/27
        1500 deny ip any 20.0.0.0/8

Only after I changed this did I get the attached response from batfish.
[suggested_fix_post.txt](https://github.com/user-attachments/files/17214286/suggested_fix_post.txt)

In the attached we can see the flow for two devices. The top flow works as expected (this is the one I manually changed). The bottom flow was left with non-CIDR notation and is snagging on that 700 entry.

NOTE: This entry doesnt even have relevance to the flow in question it seems as if batfish analysis simply stops at this point even returning PERMIT when it should return DENY.

Is there a way to enable compatibility for non-CIDR or is this something we will have to change network-wide to accomodate batfish? 

The configs we are looking at are Arista.
Batfish version information:

batfish/allinone        latest          f62d3a939b17   2 months ago    1.53GB
pybatfish           2024.7.22.1569

**Comment by dhalperi** [comment]
Hi @gabdwr -- this is expected to work. Can you share just a bit more of the config that we can use to repro? What vendor is the config for, for example?

Note that you can use [`netconan`](https://github.com/intentionet/netconan?tab=readme-ov-file#netconan) to automate this process.

**Comment by dhalperi** [comment]
Hi @gabdwr  -- Actually, I noticed you did mention Arista in there. Sorry I missed it the first time.

In this case, I think the issue is that you got the mask wrong! On Arista, `255.255.255.224` means the last 5 bits must be `0`, and everything else can be anything. I think you want `0.0.0.31` to represent a `/27`.

Note that ACLs use a "wildcard mask" not a "subnet mask": https://www.arista.com/en/um-eos/eos-ipv4#xx1142297
