### ISSUE TITLE
Add field for OSPF process ID and BGP AS number

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#925]
The vendor independent data-model does not currently store the following information:

- OSPF process ID
- BGP AS number
  - for each BGP neighbor, there is a `localAs` value stored
     - this is not sufficient to see what the configured AS is for the router, since `localAs` can
        be set for each individual peer

There is a dictionary for `ospfProcess`. This would be the logical place to store the `processId`
There is a dictionary for `bgpProcess`. This would be the logical place to store the `bgpAs`

**Comment by dhalperi** [comment]
Per a long discussion, we've decided that a "per-process" default BGP number is not a good fit for the vendor-independent data model at this time, because it's really Cisco-specific and neither necessary nor sufficient for the types of checks we want to write.
