### ISSUE TITLE
Docker Batfish/allinone heap space error with a lot of memory available.

### ISSUE THREAD

**Issue by DanteKara** [batfish/batfish#9252]
Hi team,

I'm currently running the latest Pybatfish version with the batfish/allinone container. We have no issues processing our Cisco and Arista configurations, aside from occasional ingestion failures and the container's memory usage being quite volatile, even when rerunning the same configurations. However, with a few retries, we manage to ingest those configurations.

The main issue I'm facing right now is trying to ingest our shared FortiOS firewall configuration files. The machine has 128GB of RAM and 32 CPU cores, so it shouldn't be a memory issue. I’ve attached in the (txt file) the docker-compose.yml file I’m using to set up the container.

In the attached log (txt file), you’ll see the output from running my ingestion script. Batfish attempts to convert the configuration, reaches the "converting configurations to vendor-independent format" step, and then throws a HEAP SPACE error, even when allocating 100GB for heap space. This occurs even with just one configuration file.

I can share the script if that would be helpful.

Thanks for your help!

[shared-firewall attempt.txt](https://github.com/user-attachments/files/17439870/shared-firewall.attempt.txt)

**Comment by dhalperi** [comment]
Hey, this is interesting. I'm less awesome at Docker and Linux than I wish I were, but I have a few thoughts:

1. It might help to just set mins and maxes the same so you actually use everything. So I'd set the k8s reservation and limit the same (say, 110 GB) and then `Xmx` and `Xms` the same (say, 100 GB) and see if things become more stable.

2. I'd throw in `-XX:+PrintFlagsFinal` in the java args, so you can look at the logs and confirm the JVM is getting the settings you expect. I've found ridiculous limits in the past.

3. I'd make sure the JVM you're using is dynamically disabling compressed OOPs for large RAM. All JVMs should do that now, I'd think, but you'll see it in those same args.

4. Lastly, given that it is a FortiOS firewall there's a chance that the way Batfish models FortiOS there's something silly we're doing that is causing exponential RAM use. For that, we'd have to see the data. This happened in the past where, for example, a route-map that had N terms that each had a `continue` would generate 2^N entries, but a quick refactor made it linear.

Please try those out and let me know how it goes, and I am also on Batfish Slack (linked from github readme / batfish.org) if you want to interact synchronously

**Comment by DanteKara** [comment]
Hey,

I haven't yet tried step 1 on my Cisco and Arista configs (the one where ingestion would sometimes fail but work after a retry). I'll give that a go later today.

I did try the first three steps on the shared firewall config, but I'm still seeing the same heap space issue. The args show that compressed OOPs are disabled, which makes sense given the large amount of RAM we're working with. It might be time to send you the data we're using so we can proceed with the refactor you suggested in step 4.

**Comment by dhalperi** [comment]
Resolving after discussion with user on Slack says that they can now initialize a snapshot successfully.
