### ISSUE TITLE
NX-OS parser: not finding use of named ACL for SNMP access

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#926]
NX-OS parser does not correctly identify the use of the named ACL for SNMP access. A sample configuration snippet is below:

```
ip access-list SNMP-RW
 10 permit ip 10.1.1.0/24 any
 20 permit ip 10.1.2.0/24 any
...
snmp-server community <blah> use-acl SNMP-RW
```

The IP access-list SNMP-RW shows up as an unused structure, when it is clearly not unused.

**Comment by sfraint** [comment]
Tried reproducing this on `batfish` master and it appears to work now.
