### ISSUE TITLE
frr configs parse error

### ISSUE THREAD

**Issue by liujona** [batfish/batfish#9300]
Why does it fail to parse when I use the Docker image batfish/allinone to process my FRR configuration files, showing the parser context as cisco?
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/d6a1706b-35f4-492d-b7b2-1b4b5c78016f" />

**Comment by dhalperi** [comment]
I predict you are not including the necessarily sentinel lines: https://pybatfish.readthedocs.io/en/latest/formats.html#cumulus-configuration-files-recommended

```
# This file describes the network interfaces
```

being the key one.

**Comment by liujona** [comment]
> I predict you are not including the necessarily sentinel lines: https://pybatfish.readthedocs.io/en/latest/formats.html#cumulus-configuration-files-recommended
> 
> ```
> # This file describes the network interfaces
> ```
> 
> being the key one.

Thank you！It works！
